### ISSUE TITLE
[Feature-Request] OM - Lineage - Tables

### ISSUE THREAD

**Issue by BessonEduardo** [open-metadata/OpenMetadata#10226] opened 2023-02-16 22:18 UTC
Hi OM Team!

Good day!

We had some problems about tests in the Lineage.
In the origin (GCP), we had erased a specific table and after the update we have observed that OM lost the conection and the same table still there (OM).

Thanks in advance.

**Comment by sureshms** [comment] 2023-06-28 19:12
This appears to be duplicate of #10225. Please provide more details on #10225.

**Closed by sureshms** 2023-06-28 19:12 UTC
Labels: enhancement
