### ISSUE TITLE
Athena query usage ingestion is not working as expected

### ISSUE THREAD

**Issue by vithushanms** [open-metadata/OpenMetadata#16367] opened 2024-05-21 12:14 UTC
**Affected module**
Query usage ingestion

**Describe the bug**
Although the query log duration is set to 100 and ingestion became successful, I couldn't able to see the queries used within last 100 days in the asssets.

<img width="1295" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/53653757/40cdf265-0003-410c-babd-7a4a2f79a991">

<img width="1639" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/53653757/3ba8123e-6b4c-4e05-841d-2b166a46e11e">

**To Reproduce**
1. Add any athena connection
2. Run queries in the source
3. Ingest after 1 day, specifying the query log duration set to the number of days which covers that time window

<img width="705" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/53653757/24144300-21db-46b3-8e1c-504c34400daf">

**Expected behavior**
I should see the executed queries in the assets within the specified timeframe

**Version:**
 - OS: Ubuntu
 - Python version: 3.10
 - OpenMetadata version: tested in both 1.2.5 and 1.3.3 
 - OpenMetadata Ingestion package version:  tested in both 1.2.5 and 1.3.3

**Comment by ulixius9** [comment] 2024-05-22 08:20
@vithushanms this is not reproducible for me, hence closing this issue you can reach out to us on slack: https://slack.open-metadata.org/ on support channel

I would need more information related to this to understand the root cause, need to check the logs 

![image](https://github.com/open-metadata/OpenMetadata/assets/39544459/972cdbfc-f955-4322-8b80-313a5824ade9)

closing this issue for now, we can reopen if we found anything over slack

**Closed by ulixius9** 2024-05-22 08:20 UTC
