### ISSUE TITLE
[Databricks – Metadata Ingestion] Name resolution of catalog and schema during `DESCRIBE` faulty

### ISSUE THREAD

**Issue by oynek** [open-metadata/OpenMetadata#10736] opened 2023-03-23 16:56 UTC
**Affected module**
Service: `Databricks`
Ingestion Type: `metadata`

**Describe the bug**
Apparently, the name resolution of catalogs and schema using Metadata Ingestion from Databricks does not work correctly:

<img width="1741" alt="image" src="https://user-images.githubusercontent.com/18418496/227285566-3989812b-71b0-484b-a2ab-2d98d6ae0b21.png">

Between the execution of the `DESCRIBE` commands the schema of the table is swapped (from `klapp_at` (correct) -> `sources` (wrong).

**To Reproduce**
My Databricks Unity Catalog is called `sources` and looks like this:

<img width="302" alt="image" src="https://user-images.githubusercontent.com/18418496/227272084-5c062c98-ee11-46b1-a5c0-efababd83a04.png">

I have set the following filters:

<img width="691" alt="image" src="https://user-images.githubusercontent.com/18418496/227272288-68c28fb7-36af-4c4f-b1b0-ad86187c13c6.png">

While with some tables everything works wonderfully...

<img width="908" alt="image" src="https://user-images.githubusercontent.com/18418496/227273983-fa8cb506-6083-43ed-b147-8386bf63a49a.png">

...it does not work smoothly for others:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/18418496/227273654-747db6af-8b1c-48e4-910c-a480fe7d3bea.png">

**Version:**
 - Python version: 3.7.10
 - OpenMetadata version: [e.g. 0.13.2]

**Comment by pmbrull** [comment] 2023-05-09 16:27
hi @oynek could you please let us know if you are still experiencing this issue in the 1.0 release?

cc @ulixius9, since we need to start a databricks cluster for other tasks, let's double-check if this is something we can validate.

Thanks

**Comment by ulixius9** [comment] 2023-05-31 14:53
I can confirm that this error has been fixed is already resolved with this pr https://github.com/open-metadata/OpenMetadata/pull/10469

![image](https://github.com/open-metadata/OpenMetadata/assets/39544459/4c222671-0dee-4c5e-9591-f69c004e9432)

**Closed by ulixius9** 2023-05-31 14:53 UTC
Labels: bug, Ingestion, validation
