### ISSUE TITLE
Data profiling as per data type

### ISSUE THREAD

**Issue by nanavaty** [open-metadata/OpenMetadata#12520] opened 2023-07-20 10:32 UTC
**Is your feature request related to a problem? Please describe.**
Current data profiling integration doesn't distinguish between VARCHAR, Integer and other data type. Even if data type is VARCHAR, profiler provides sum, average and aggregated vales

**Describe the solution you'd like**
Profiling tab should provide data according to data type such as data such as Sum, Average etc not valid for strings (varchar) while few others few others such as lower or upper case not valid for numeric values.

**Describe alternatives you've considered**
Written python script to generate report based on data type

**Additional context**
Attached screen-capture for varchar columns
Add any 
![Aggregation](https://github.com/open-metadata/OpenMetadata/assets/36784544/0360600f-fc61-4901-a1b8-261b2a69c654)
other context or screenshots about the feature request here.
![Data Quertiles for varchar](https://github.com/open-metadata/OpenMetadata/assets/36784544/8d0b28b4-0196-42e3-859e-4b74b14620d1)

**Comment by DovileKr** [comment] 2023-07-21 07:49
same as https://github.com/open-metadata/OpenMetadata/issues/11951

**Comment by harshach** [comment] 2024-03-17 17:12
duplicate of #11951

**Closed by harshach** 2024-03-17 17:12 UTC
Labels: enhancement
