### ISSUE TITLE
Snowflake Ingestion fails with 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by LucaMueller1** [open-metadata/OpenMetadata#7301] opened 2022-09-07 08:33 UTC
**Affected module**
- Ingestion Framework

**Describe the bug**
- Ingestion does not complete. Throws following error:
```
Traceback (most recent call last):
  File "/Users/<User>/opt/anaconda3/envs/openmetadata/bin/metadata", line 8, in <module>
    sys.exit(metadata())
  File "/Users/<User>/opt/anaconda3/envs/openmetadata/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/<User>/opt/anaconda3/envs/openmetadata/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/<User>/opt/anaconda3/envs/openmetadata/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/<User>/opt/anaconda3/envs/openmetadata/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/<User>/opt/anaconda3/envs/openmetadata/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/<User>/opt/anaconda3/envs/openmetadata/lib/python3.9/site-packages/metadata/cmd.py", line 73, in ingest
    run_ingest(config_path=config)
  File "/Users/<User>/opt/anaconda3/envs/openmetadata/lib/python3.9/site-packages/metadata/cli/ingest.py", line 47, in run_ingest
    workflow.execute()
  File "/Users/<User>/opt/anaconda3/envs/openmetadata/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 161, in execute
    for record in self.source.next_record():
  File "/Users/<User>/opt/anaconda3/envs/openmetadata/lib/python3.9/site-packages/metadata/ingestion/api/topology_runner.py", line 104, in next_record
    yield from self.process_nodes(get_topology_root(self.topology))
  File "/Users/<User>/opt/anaconda3/envs/openmetadata/lib/python3.9/site-packages/metadata/ingestion/api/topology_runner.py", line 89, in process_nodes
    yield from self.process_nodes(child_nodes)
  File "/Users/<User>/opt/anaconda3/envs/openmetadata/lib/python3.9/site-packages/metadata/ingestion/api/topology_runner.py", line 73, in process_nodes
    for entity_request in stage_fn(element) or []:
  File "/Users/<User>/opt/anaconda3/envs/openmetadata/lib/python3.9/site-packages/metadata/ingestion/source/database/common_db_source.py", line 139, in yield_database
    id=self.context.database_service.id,
AttributeError: 'NoneType' object has no attribute 'id'
```

**To Reproduce**
1. Run OpenMetadata ingestion `metadata ingest -c config.yaml` for a Snowflake Sample Database with the config below

**Expected behavior**
- Ingestion is supposed to complete and dump results into the file defined in the sink config

**Version:**
 - OS: MacOS (intel)
 - Python version: 3.9.13
 - OpenMetadata version: 0.11.5.3
 - OpenMetadata Ingestion package version: ???

**Additional context**
Ingestion config:
```yaml
source:
  type: snowflake
  serviceName: local_snowflake
  serviceConnection:
    config:
      type: Snowflake
      username: <Username>
      password: <Password>
      warehouse: COMPUTE_WH
      account: XYZ.eu-central-1
      role: ACCOUNTADMIN
      database: SAMPLEDATABASE
      
  sourceConfig:
    config:
      markDeletedTables: true
      includeTables: true
      includeViews: true
      # includeTags: true
      # databaseFilterPattern:
      #   includes:
      #     - database1
      #     - database2
      #   excludes:
      #     - database3
      #     - database4
      # schemaFilterPattern:
      #   includes:
      #     - schema1
      #     - schema2
      #   excludes:
      #     - schema3
      #     - schema4
      # tableFilterPattern:
      #   includes:
      #     - table1
      #     - table2
      #   excludes:
      #     - table3
      #     - table4
      # For DBT, choose one of Cloud, Local, HTTP, S3 or GCS configurations
      # dbtConfigSource:
      # # For cloud
      #   dbtCloudAuthToken: token
      #   dbtCloudAccountId: ID
      # # For Local
      #   dbtCatalogFilePath: path-to-catalog.json
      #   dbtManifestFilePath: path-to-manifest.json
      # # For HTTP
      #   dbtCatalogHttpPath: http://path-to-catalog.json/
      #   dbtManifestHttpPath: http://path-to-manifest.json/
      # # For S3
      #   dbtSecurityConfig:  # These are modeled after all AWS credentials
      #     awsAccessKeyId: KEY
      #     awsSecretAccessKey: SECRET
      #     awsRegion: us-east-2
      #   dbtPrefixConfig:
      #     dbtBucketName: bucket
      #     dbtObjectPrefix: "dbt/"
      # # For GCS
      #   dbtSecurityConfig:  # These are modeled after all GCS credentials
      #     type: My Type
      #     projectId: project ID
      #     privateKeyId: us-east-2
      #     privateKey: |
      #      -----BEGIN PRIVATE KEY-----
      #      Super secret key
      #      -----END PRIVATE KEY-----
      #     clientEmail: client@mail.com
      #     clientId: 1234
      #     authUri: https://accounts.google.com/o/oauth2/auth (default)
      #     tokenUri: https://oauth2.googleapis.com/token (default)
      #     authProviderX509CertUrl: https://www.googleapis.com/oauth2/v1/certs (default)
      #     clientX509CertUrl: https://cert.url/ (URI)
      #   dbtPrefixConfig:
      #     dbtBucketName: bucket
      #     dbtObjectPrefix: "dbt/"
sink:
  type: file
  config: 
    filename: /Users/<User>/Desktop/snowflake.sink.data
workflowConfig:
  # loggerLevel: DEBUG  # DEBUG, INFO, WARN or ERROR
  openMetadataServerConfig:
    hostPort: http://localhost:8585/api
    authProvider: no-auth
```

**Comment by LucaWeissbeck** [comment] 2022-09-07 11:36
I have the same issue...

**Comment by codingwithabhi** [comment] 2022-09-12 15:13
Hi @LucaMueller1 
I was not able to reproduce this error, can you check the config and database you are passing and let me know if you are still facing the same issue.?

**Comment by LucaWeissbeck** [comment] 2022-09-13 09:51
Hi @codingwithabhi 
Thank you for your response! I have updated open-metadata and it seems to be working just fine! :)

One thing: Why do I need to specify the **service-name from the OpenMetadata UI** in the config.yaml if I enter the credentials for the snowflake service regardless in the same yaml? 
Does it not build its own connection to the snowflake service? 

Thanks!

**Comment by pmbrull** [comment] 2022-09-16 05:19
Hi @LucaWeissbeck, the logic here is that if the serviceName does not exist yet in OM, we will create the service with the provided credentials. If it exists, we will use the credentials from the server.

We kept both serviceName and credentials in the same YAML to not force updating the configs if the service exists or not.

Will be closing the issue as there is no further action to take here. @LucaWeissbeck do let us know if you have any further questions.

Thanks!

**Closed by pmbrull** 2022-09-16 05:19 UTC
Labels: P0, Ingestion
