### ISSUE TITLE
Superset datamodels with slash ("/") cause ingest failure

### ISSUE THREAD

**Issue by joegoldbeck** [open-metadata/OpenMetadata#13732] opened 2023-10-26 16:11 UTC
**Affected module**
Ingestion

**Describe the bug**
Whenever a superset data model has a "/" in the name, during ingest, the server 500's, with `{"responseMessage":"An exception with message [OpenSearch exception [type=search_phase_execution_exception, reason=all shards failed]] was thrown while processing request."}%`. This stops the ingestion entirely.

**To Reproduce**

Easiest way
- navigate to such a url and you will see the error: `https://openmetadata/api/v1/search/query?q=fullyQualifiedName:foo/bar&from=0&size=10&index=table_search_index`
- however, you will not see the error at `https://openmetadata/api/v1/search/query?q=fullyQualifiedName:foobar&from=0&size=10&index=table_search_index`

Alternatively
- create a superset dashboard that relies on a data model with a "/" in the name
- run superset ingest

**Expected behavior**
- dashboards and lineage are properly ingested for any valid superset data model name

**Version:**

- Python version: 3.9.17
- OpenMetadata version: 1.1.5
- OpenMetadata Ingestion package version: openmetadata-ingestion==1.1.5

**Additional context**

The search failure does not happen with a generic query with `/` in it, but rather then the `fullyQualifiedName:` qualifier is used

**Comment by OnkarVO7** [comment] 2023-10-31 16:27
HI @joegoldbeck the issue is fixed with the 1.2 release. Please upgrade to the same and let us know.

Closing the issue

<img width="1216" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/28966081/3f165f46-269a-4939-b254-39bb50dc94eb">

**Closed by OnkarVO7** 2023-10-31 16:27 UTC
Labels: bug, Ingestion
