### ISSUE TITLE
Bigquery failing while ingesting via airflow

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#5238] opened 2022-05-31 15:26 UTC
Throwing below error
```
[2022-05-31 15:18:33,761] {sql_column_handler.py:90} WARNING - Cannot obtain unique constraints - NotImplementedError
[2022-05-31 15:18:34,172] {sqlalchemy_source.py:276} ERROR - get_database_entity() missing 1 required positional argument: 'database'
[2022-05-31 15:18:34,175] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/lib/python3.9/site-packages/openmetadata/workflows/ingestion/common.py", line 56, in metadata_ingestion_workflow
    workflow.raise_from_status()
  File "/usr/local/lib/python3.9/site-packages/metadata/ingestion/api/workflow.py", line 189, in raise_from_status
    raise WorkflowExecutionError(
metadata.config.common.WorkflowExecutionError: ('Source reported errors', SQLSourceStatus(warnings=[], failures=['BigQuery-ci-test-506007.asd', 'BigQuery-ci-test-506007.dual_eligible_enrollment_by_county_and_program', 'BigQuery-ci-test-506007.new_cities', 'BigQuery-ci-test-506007.new_cities_nine', 'BigQuery-ci-test-506007.newtable', 'BigQuery-ci-test-506007.newtable_test', 'BigQuery-ci-test-506007.test_policy_tags', 'BigQuery-ci-test-506007.badges', 'BigQuery-ci-test-506007.comments', 'BigQuery-ci-test-506007.new_cts_2', 'BigQuery-ci-test-506007.new_cts_final', 'BigQuery-ci-test-506007.post_history', 'BigQuery-ci-test-506007.post_links', 'BigQuery-ci-test-506007.posts_answers', 'BigQuery-ci-test-506007.posts_moderator_nomination', 'BigQuery-ci-test-506007.posts_orphaned_tag_wiki', 'BigQuery-ci-test-506007.posts_privilege_wiki', 'BigQuery-ci-test-506007.posts_questions', 'BigQuery-ci-test-506007.posts_tag_wiki', 'BigQuery-ci-test-506007.posts_tag_wiki_excerpt', 'BigQuery-ci-test-506007.posts_wiki_placeholder', 'BigQuery-ci-test-506007.stackoverflow_posts', 'BigQuery-ci-test-506007.tags', 'BigQuery-ci-test-506007.users', 'BigQuery-ci-test-506007.votes'], success=[], filtered=[]))
[2022-05-31 15:18:34,188] {taskinstance.py:1506} INFO - Marking task as UP_FOR_RETRY. dag_id=BigQuery-ci-test-506007_metadata, task_id=ingestion_task, execution_date=20220531T140500, start_date=20220531T151805, end_date=20220531T151834
[2022-05-31 15:18:34,218] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py:1522 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-05-31 15:18:34,470] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-05-31 15:18:34,489] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/jobs/local_task_job.py:227 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-05-31 15:18:34,501] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/models/dagrun.py:359 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-05-31 15:18:34,504] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-31 15:18:34,505] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/models/dag.py:814 SADeprecationWarning: Query.value() is deprecated and will be removed in a future release.  Please use Query.with_entities() in combination with Query.scalar() (deprecated since: 1.4)
[2022-05-31 15:18:34,505] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/models/dag.py:814 SADeprecationWarning: Query.values() is deprecated and will be removed in a future release.  Please use Query.with_entities() (deprecated since: 1.4)
```

**Comment by ayush-shah** [comment] 2022-06-23 06:35
@open-metadata/ingestion is this reproducible? if not we can close this ticket

**Comment by ShaileshParmar11** [comment] 2022-06-23 06:37
I think it is fixed as cypress is running fine for all PR

**Comment by pmbrull** [comment] 2022-06-23 07:28
@ShaileshParmar11 just tested and works for me, we can close this. Thanks!

**Closed by pmbrull** 2022-06-23 07:28 UTC
Labels: bug, Ingestion
