### ISSUE TITLE
Tableau connector doesn't ingest tags if there is a dot in tag name

### ISSUE THREAD

**Issue by gnomolio** [open-metadata/OpenMetadata#9708] opened 2023-01-12 12:39 UTC
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion framework

**Describe the bug**
WARNING  {Ingestion:metadata_rest:376} - Unexpected error writing tag category [name=TagName(__root__='TableauTags') displayName=None description=Markdown(__root__='Tags associates with tableau entities') mutuallyExclusive='false']: Invalid name TableauTags."author:[name.lastname@domain.com](mailto:name.lastname@domain.com)"

**To Reproduce**
Ingest tags from Tableau with dots in tag names 

**Expected behavior**
Tags will be added to OMD

**Version:**
OMD 0.13.0 
Tableau API 3.15

**Additional context**
Slack https://openmetadata.slack.com/archives/C02B6955S4S/p1673452949900439

**Comment by NiharDoshi99** [comment] 2023-01-17 06:29
Hi @gnomolio , we are unable to reproduce the above error. Looks like there seems to be issue with `antlr` in `0.13.0` . Please upgrade to latest version

**Comment by NiharDoshi99** [comment] 2023-01-17 10:29
Dashboard
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/51595473/212872715-e5114146-9a35-4324-95e7-3a1edee03210.png">

Chart
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/51595473/212875204-1a7a1f70-80cc-4c83-aa1b-ac3d0e2ec67e.png">

Added tags with dots(.) , colon(:) and `@`, seems to be ingested properly

**Comment by pmbrull** [comment] 2023-01-18 06:02
Thanks @NiharDoshi99 for checking this out. @gnomolio we'll close this for now as we cannot reproduce it. Please feel free to reopen this issue if the issue persists on your end after upgrading.

Thanks

**Closed by pmbrull** 2023-01-18 06:02 UTC
Labels: bug, Ingestion, support
