### ISSUE TITLE
fromColumns having list type in column lineage json even though it holds one value

### ISSUE THREAD

**Issue by Sai7656** [open-metadata/OpenMetadata#11528] opened 2023-05-10 14:13 UTC
**Affected module**
Does it impact the UI, backend or Ingestion Framework? -  Backend

**Describe the bug**
A clear and concise description of what the bug is. - The "fromColumns" section in the column lineage json is having list of values as below even though it holds one value and for many to one column mapping as well all lineage appears as single entities.

"fromColumns": [
							"AzureDatabricks_DataFabric.hive_metastore.humanresources.employee_department_history_silver.EndDate"
						] 

**To Reproduce** - NA

Screenshots or steps to reproduce

**Expected behavior**
A clear and concise description of what you expected to happen. - As all column level lineage are one to one it's better to have this field as string just like "toColumn" and change the column name from "fromColumns" to "fromColumn".

**Version:**
 - Python version: 3.8
 - OpenMetadata version: [e.g. 0.8] 1.0.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] 1.0.0

**Additional context**

**Comment by sureshms** [comment] 2023-05-11 01:25
We are capturing the column level lineage on the relationship edge from one table to another. Since this edge can have multiple column lineage for multiple columns from table 1 to table 2, this is an array. 

Closing this as not a bug. @Sai7656, it would be great if you can confirm that an issue is indeed a bug in OpenMetadata support channel before opening the bug. Thank you.

**Closed** 2023-05-11 01:25 UTC
Labels: Ingestion, backend, lineage

**Comment by Sai7656** [comment] 2023-05-11 06:49
> We are capturing the column level lineage on the relationship edge from one table to another. Since this edge can have multiple column lineage for multiple columns from table 1 to table 2, this is an array.
> 
> Closing this as not a bug. @Sai7656, it would be great if you can confirm that an issue is indeed a bug in OpenMetadata support channel before opening the bug. Thank you.

Hi @sureshms I spoke with @ulixius9 and raised the issue here. https://openmetadata.slack.com/archives/C02B6955S4S/p1683719317889769

Also, I have a lineage in OM UI which is as shown in the picture. Here two columns(startdate and enddate) are used to populate a column(Totalworkingdays). But when I get the lineage through API fromColumns doesn't hold array of values. It holds two different blocks as below.

![image](https://github.com/open-metadata/OpenMetadata/assets/60571532/1ee7e82e-b434-4c35-9cc7-b11aeccffb01)

					{
						"fromColumns": [
							"AzureDatabricks_DataFabric.hive_metastore.humanresources.employee_department_history_silver.EndDate"
						],
						"toColumn": "AzureDatabricks_DataFabric.hive_metastore.openmetadata_poc.employee_shift_vw.TotalWorkingDays"
					},
					{
						"fromColumns": [
							"AzureDatabricks_DataFabric.hive_metastore.humanresources.employee_department_history_silver.StartDate"
						],
						"toColumn": "AzureDatabricks_DataFabric.hive_metastore.openmetadata_poc.employee_shift_vw.TotalWorkingDays"
					},
