### ISSUE TITLE
UI - allow user to modify constraint for Schema or Table level

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#13396] opened 2023-10-02 06:02 UTC
**Is your feature request related to a problem? Please describe.**
Good to have option to modify constraint for Schema or Table from UI

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by harshach** [comment] 2024-06-23 18:48
closing this as duplicate of this https://github.com/open-metadata/OpenMetadata/issues/13820

**Closed by harshach** 2024-06-23 18:48 UTC
Labels: enhancement, UI
