### ISSUE TITLE
Profiler + Sample Data + DQ Issues

### ISSUE THREAD

**Issue by eimanghumman** [open-metadata/OpenMetadata#14544] opened 2024-01-02 12:07 UTC
- [x] Hello, my table is empty on source which means there are columns but no data against rows. But open metadata is displaying some of 35k rows. Please tell me how to fix this problem. Also, sharing a snapshot of the table directly from source. so you can validate this. Also, there is an issue with open metadata, whenever I run profiler for a specific table, it fetches others tables as well. Whereas I just include that specific table name. In this case I just included tbl_payment_request and it is running profiler against others as shown in snapshot. Please see into this thing.
![image (4)](https://github.com/open-metadata/OpenMetadata/assets/155446279/c9b9c361-dc38-4d58-b441-f012a0f815c3)
![image (3)](https://github.com/open-metadata/OpenMetadata/assets/155446279/c34290d1-ed6a-4cd6-8aab-c2160a5bac9e)
![image (2)](https://github.com/open-metadata/OpenMetadata/assets/155446279/4679b5fd-6c17-4bfd-9d83-39b16a16b9ec)
![image (1)](https://github.com/open-metadata/OpenMetadata/assets/155446279/edf54ba9-4109-47df-a3dc-09def31d7a5b)

Resolution: Validated on the main, the issue is not reproducible, upgrading to latest OM server should resolve the value count issue, whereas the TrinoUserError has already been fixed as part of 1.2

**Comment by ayush-shah** [comment] 2024-01-03 10:07
- [ ] Null Proportion not getting accounted for in oracle db

ref:https://openmetadata.slack.com/archives/C02B6955S4S/p1700807958192139

**Comment by ayush-shah** [comment] 2024-01-10 04:06
Sample data ingestion failure on sql server 2019 with data type: varbinary, timestamp and decimal.
To be validated, and provide a fix.
![image](https://github.com/open-metadata/OpenMetadata/assets/40225091/95ed87d7-08ab-4477-929c-725eb41c77d4)
<img width="564" alt="Screenshot 2024-01-10 at 9 36 25 AM" src="https://github.com/open-metadata/OpenMetadata/assets/40225091/14f095a8-5528-413e-a778-c338debb4c2e">

https://openmetadata.slack.com/archives/C02B6955S4S/p1704744506192689

**Comment by pmbrull** [comment] 2024-01-25 11:34
we can't reproduce the pending topic. Closing

**Closed by pmbrull** 2024-01-25 11:34 UTC
Labels: epic, Need more info, profiler
