### ISSUE TITLE
Showing table icon for glossary in user details page under owned data.

### ISSUE THREAD

**Issue by parthp2107** [open-metadata/OpenMetadata#3254] opened 2022-03-08 07:05 UTC
**Affected module**
UI

**Describe the bug**
Showing table icon for glossary in user details page under owned data.

**To Reproduce**

<img width="1201" alt="Screenshot 2022-03-08 at 12 31 23 PM" src="https://user-images.githubusercontent.com/83201188/157184294-b61168df-f06a-4a3d-90b2-ec087a18bf63.png">

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

**Comment by Sachin-chaurasiya** [comment] 2022-03-09 10:25
Duplicate of #3312

**Closed by Sachin-chaurasiya** 2022-03-09 10:25 UTC
Labels: idea, UI
