### ISSUE TITLE
A top-level search bar can be used to search from any page. It should default to the table or allow users to select a type while searching

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#364] opened 2021-09-02 06:21 UTC

**Comment by shahsank3t** [comment] 2021-09-03 05:01
While searching suggests should show suggestions for different categories for entities, such as Table, Topic, Dashboards, etc.
Also, show corresponding entity icons for the suggestions.

**Comment by Sachin-chaurasiya** [comment] 2021-09-06 14:43
Duplicate of #362

**Closed by Sachin-chaurasiya** 2021-09-06 14:43 UTC
