### ISSUE TITLE
Support Internationalization

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#5496] opened 2022-06-16 20:57 UTC
**Feature**
Add support for internationalization in OpenMetada UI. We should move all the standard text displayed in Open Metadata UI to a language constants file to support multiple languages.

**Comment by Arturo-Penas-Rial** [comment] 2022-07-14 12:37
I can help translating to Spanish language!

**Comment by mohoval** [comment] 2022-08-10 06:26
Thanks for your efforts. 
When this feature can be added (which release)?
And does this support RTL languages?
@vivekratnavel 
@harshach

**Comment by harshach** [comment] 2022-09-05 18:21
@mohoval we are shooting for 0.13 release slated for Oct 19th 2022

**Comment by Sachin-chaurasiya** [comment] 2022-10-06 06:09
Duplicate of #3474

**Closed by Sachin-chaurasiya** 2022-10-06 06:09 UTC
Labels: P0, UI
