### ISSUE TITLE
Review backend failing tests

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#8567] opened 2022-11-07 15:25 UTC
Looks like a few tests are dying when run locally:
- SecretManagerFactoryTest
- AirflowRESTClientIntegrationTest

**Comment by harshach** [comment] 2022-12-10 19:25
@pmbrull can't reproduce this on my local. Closing it, reopen if we see this again

**Closed by harshach** 2022-12-10 19:25 UTC
Labels: Ingestion, backend
