### ISSUE TITLE
Owner name not displayed on activity feed

### ISSUE THREAD

**Issue by kshinde2512** [open-metadata/OpenMetadata#3299] opened 2022-03-09 06:21 UTC
**Affected module**
UI

**Describe the bug**
Owner name is not displayed on activity feed on selecting owner.

**To Reproduce**
- Navigate to Database from table details page
- Click on Manage tab and select owner
- Click on Save
- Navigate to activity feed tab
- Owner name is not displayed

![Screenshot from 2022-03-09 11-24-19](https://user-images.githubusercontent.com/67048554/157384072-508852d2-f770-48cd-a219-10dab00ac3d5.png)

**Expected behavior**
Owner name should be displayed

**Version:**
 - OpenMetadata version: 0.9.0

**Additional context**
NA

**Comment by kshinde2512** [comment] 2022-03-09 06:21
@Sachin-chaurasiya @darth-coder00

**Comment by vivekratnavel** [comment] 2022-03-09 06:22
Duplicate of #3294

**Closed by vivekratnavel** 2022-03-09 06:22 UTC
