### ISSUE TITLE
UI is blocking user with permission error for glossary term details page

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#15639] opened 2024-03-21 05:00 UTC
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
Even when user is the owner of the glossary term, ui is blocking the user with permission error!
**To Reproduce**

Below are the steps to reproduce:
- Remove the default role and  policy from the organisation team
- Create a new policy with the information provided in the screenshot
- add the newly created policy to the organisation
- Add one glossary and glossary term,
- Create new user, and make him owner of glossary and glossary term
- Visit glossary term details page from explore -> glossary term -> glossary term details page
![image (5)](https://github.com/open-metadata/OpenMetadata/assets/71748675/e2a3af29-39d5-4f1d-a2d7-6a71e58b85a7)

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by karanh37** [comment] 2024-03-26 05:13
Duplicate of #15677

**Comment by chirag-madlani** [comment] 2024-04-17 08:46
Closing since duplicate of #15677

**Closed by chirag-madlani** 2024-04-17 08:46 UTC
Labels: bug, UI
