### ISSUE TITLE
UI - Provide keyboard shortcuts

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#3392] opened 2022-03-14 04:25 UTC
**Feature**
As we are getting more complex UI interactions it will be great to have keyboard bindings
1. CMD + K should open the search box2. 2. 
2. Escape/Enter to should support cancel/save of dialog boxes or other interactions3. 

**Describe the task**
cc @vivekratnavel please add any other options here

**Comment by vivekratnavel** [comment] 2022-03-14 05:36
It will be nice to have this in UI once we support key bindings

<img width="159" alt="Screen Shot 2022-03-13 at 10 35 01 PM" src="https://user-images.githubusercontent.com/1051198/158111266-2efc147f-82ea-428b-85fa-59c5c2624aa1.png">

**Comment by harshach** [comment] 2022-07-04 18:23
@Sachin-chaurasiya FYI, lets fix it in 0.11.1 release

**Comment by Sachin-chaurasiya** [comment] 2022-07-20 04:58
Duplicate of #5381

**Closed by Sachin-chaurasiya** 2022-07-20 04:58 UTC
Labels: backlog, P1, UI
