### ISSUE TITLE
Data Profiler & MySQL Zero Date issue

### ISSUE THREAD

**Issue by svermeulen-smartbit** [open-metadata/OpenMetadata#15455] opened 2024-03-05 10:44 UTC
**Affected module**
Ingestion Framework

**Describe the bug**
Running a Profiler Ingestion flow on a MySQL table which contains a date/datetime column with a zero date (i.e. **0000-00-00 00:00:00**) gives the following error:

```
[2024-03-05, 10:30:48 UTC] {core.py:680} ERROR - Cannot transform profiler results to TableProfile: 5 validation errors for ColumnProfile
min
  value is not a valid float (type=type_error.float)
min
  value is not a valid integer (type=type_error.integer)
min -> __root__
  invalid datetime format (type=value_error.datetime)
min -> __root__
  invalid time format (type=value_error.time)
min -> __root__
  invalid date format (type=value_error.date)

[2024-03-05, 10:30:48 UTC] {status.py:76} WARNING - Unexpected exception processing entity test mysql local.default.test.with_zero: 5 validation errors for ColumnProfile
min
  value is not a valid float (type=type_error.float)
min
  value is not a valid integer (type=type_error.integer)
min -> __root__
  invalid datetime format (type=value_error.datetime)
min -> __root__
  invalid time format (type=value_error.time)
min -> __root__
  invalid date format (type=value_error.date)
```

**To Reproduce**

1. Create a MySQL tables with 1 datetime column, containing a zero date record.
```
CREATE TABLE `with_zero` (
  `with_zero` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```
![image](https://github.com/open-metadata/OpenMetadata/assets/159910871/f5ecf773-160c-47f8-8f85-8a244b93d0fc)

2. Create a Data Profiler Ingestion flow in the OpenMetaData UI & run the flow on the created table

**Expected behavior**
No errors when running the Data Profiler on a table which contains date/datetime columns with zero dates.

**Version:**
 - OpenMetadata version: 1.3.0

**Comment by TeddyCr** [comment] 2024-04-04 09:03
Closing as not update from OP and not able to reproduce it. @svermeulen-smartbit profiling is supported for MySQL 8+ (lower version have reached EOL). If you are using 8+ please reopen the issue with the steps to load zero date value.

**Closed by TeddyCr** 2024-04-04 09:03 UTC
Labels: validation
