### ISSUE TITLE
Delete thread_entity after deleting the entity

### ISSUE THREAD

**Issue by DenisKirichenko24** [open-metadata/OpenMetadata#12641] opened 2023-07-28 14:12 UTC
**Is your feature request related to a problem? Please describe.**
Database's size increases with large `thread_entity` table 

**Describe the solution you'd like**
After deleting the entity all `thread_entity` relation with this entity should be deleted as well

**Comment by sureshms** [comment] 2023-08-04 01:20
Duplicate of #11305

**Closed by sureshms** 2023-08-04 01:20 UTC
Labels: enhancement, backend
