### ISSUE TITLE
Replace System.out and System.err by a logger

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#1986] opened 2021-12-31 19:16 UTC
See details here:
https://sonarcloud.io/project/issues?id=open-metadata_OpenMetadata&resolved=false&rules=java%3AS106&severities=MAJOR

**Comment by Trite8Q1** [comment] 2021-12-31 21:20
Hi,
I'd like to take that.

**Comment by sureshms** [comment] 2021-12-31 21:24
@Trite8Q1 assigned the issue to you. Thank you for volunteering 🙏🏼

**Comment by mohangpatil** [comment] 2022-07-24 00:13
Hi @sureshms  - I have learnt about this project from @ankumar. Wanted to try my hands on this project. So picked this and did a commit. Please review and help me if you see something which is not as per the standard.

**Comment by sureshms** [comment] 2022-07-24 10:37
@mohangpatil welcome! Assigned the issue to you.

**Comment by sureshms** [comment] 2022-07-26 02:29
@mohangpatil the latest pull request has extraneous changes. Can you please follow the process documented here for pull request - https://docs.open-metadata.org/developer/how-to-contribute

**Comment by shivamshrey** [comment] 2022-10-11 17:49
Hi @sureshms, 
Looks like no one's working on this one. I'd like to take it up. Could you assign this to me?

CC: @ayush-shah

**Comment by ayush-shah** [comment] 2022-10-11 17:54
Assigning you the same @shivamshrey.

**Comment by shivamshrey** [comment] 2022-10-12 18:23
Hey, I am getting the following error when I was [creating a distribution package](https://docs.open-metadata.org/developers/contribute/build-code-and-run-tests/openmetadata-server#create-a-distribution-packaging).

Some unit test is failing.

> [INFO]
[ERROR] Failures:
[ERROR]   CollectionRegistryTest.testCollections:30 expected: not equal but was: <0>
[INFO]
[ERROR] Tests run: 79, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for OpenMetadata-Platform 0.13.0-SNAPSHOT:
[INFO]
[INFO] OpenMetadata-Platform .............................. SUCCESS [  7.921 s]
[INFO] common ............................................. SUCCESS [ 20.383 s]
[INFO] openmetadata-spec .................................. SUCCESS [01:12 min]
[INFO] openmetadata-service ............................... FAILURE [01:45 min]
[INFO] openmetadata-ui .................................... SKIPPED
[INFO] OpenMetadata Distribution .......................... SKIPPED
[INFO] openmetadata-clients ............................... SKIPPED
[INFO] openmetadata-java-client ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:28 min
[INFO] Finished at: 2022-10-12T11:36:30+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (unit-tests) on project openmetadata-service: There are test failures.
[ERROR]
[ERROR] Please refer to D:\hacktoberfest\OpenMetadata\openmetadata-service\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (unit-tests) on project openmetadata-service: There are test failures.

> Please refer to D:\hacktoberfest\OpenMetadata\openmetadata-service\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

> Please refer to D:\hacktoberfest\OpenMetadata\openmetadata-service\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
    at org.apache.maven.plugin.surefire.SurefireHelper.throwException (SurefireHelper.java:283)
    at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution (SurefireHelper.java:171)
    at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary (SurefirePlugin.java:546)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:1183)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:931)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :openmetadata-service

**Comment by harshach** [comment] 2022-10-12 18:29
@shivamshrey it fixed in main. Can you rebase and try again.

**Comment by shivamshrey** [comment] 2022-10-13 17:40
@harshach it's still failing even after rebasing

**Comment by harshach** [comment] 2022-10-13 17:42
@shivamshrey can you open a PR I'll take a look

**Comment by harshach** [comment] 2022-10-13 18:33
@shivamshrey by the looks of it you are running it on windows. All of openmetadata-service uses docker to run the tests. I doubt the windows can run this natively you may need to setup ubuntu linux subsystem to get this going

**Comment by shivamshrey** [comment] 2022-10-13 19:33
@harshach PR is now open.

**Closed** 2022-10-14 04:39 UTC
Labels: good-first-issue, hacktoberfest
