### ISSUE TITLE
Tableau issue ingesting from UI - Tags

### ISSUE THREAD

**Issue by scaffarelli** [open-metadata/OpenMetadata#10827] opened 2023-03-29 12:55 UTC
**Affected module**
The impact is on the UI using the standard Tableau connector

**Describe the bug**
Not able to ingest Tableau data due to the process fail in the yield_tag step

**To Reproduce**
To reproduce the issue simple create a new Dashboard Tableau ingestion from UI and run it. You should get the screenshot below about the Tag Reg issue. 

<img width="1308" alt="Screenshot 2023-03-29 at 14 53 37" src="https://user-images.githubusercontent.com/30665842/228541441-f244f159-b057-409d-8d83-e594070cd04f.png">

**Expected behavior**
The ingestion process should be able to completed without any issue.

**Version:**
 - OS: [MAc]
 - Python version: 3.9
 - OpenMetadata version: 0.13.2
 - OpenMetadata Ingestion package version: openmetadata-ingestion[tableau]

**Comment by harshach** [comment] 2023-03-29 22:23
@OnkarVO7 we shouldn't failing the ingestion if we can't process tags . This should be consistent in all the connectors cc @ulixius9 @pmbrull

**Comment by OnkarVO7** [comment] 2023-04-03 07:15
The issue is fixed with https://github.com/open-metadata/OpenMetadata/pull/10695

**Closed by OnkarVO7** 2023-04-03 07:15 UTC
Labels: bug, Ingestion
