### ISSUE TITLE
Auto PII Tag failed when using Ingestion Profiler 

### ISSUE THREAD

**Issue by HongQuanVu** [open-metadata/OpenMetadata#11772] opened 2023-05-26 07:05 UTC
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Yes, it impacts the Ingestion Framework

**Describe the bug**
We run a Ingestion Profiler job on a PII table in order to  ingest sample data and tag PII but it is failed for tagging PII.
[2023-05-26, 02:12:22 UTC] {core.py:486} DEBUG - Fetching sample data for  xxxxx.open_metadata_pii_sample...
[2023-05-26, 02:12:26 UTC] {pii.py:131} WARNING - Downloading en_core_web_md language model for the spaCy
[2023-05-26, 02:13:20 UTC] {workflow_reporter.py:34} INFO - Source: Processed 0 records, filtered 0 records, found 0 errors
[2023-05-26, 02:13:20 UTC] {workflow_reporter.py:41} INFO - Sink: Processed 0 records, found 0 errors
[2023-05-26, 02:14:20 UTC] {workflow_reporter.py:34} INFO - Source: Processed 0 records, filtered 0 records, found 0 errors
[2023-05-26, 02:14:20 UTC] {workflow_reporter.py:41} INFO - Sink: Processed 0 records, found 0 errors
[2023-05-26, 02:15:20 UTC] {workflow_reporter.py:34} INFO - Source: Processed 0 records, filtered 0 records, found 0 errors
[2023-05-26, 02:15:20 UTC] {workflow_reporter.py:41} INFO - Sink: Processed 0 records, found 0 errors
[2023-05-26, 02:16:20 UTC] {workflow_reporter.py:34} INFO - Source: Processed 0 records, filtered 0 records, found 0 errors
[2023-05-26, 02:16:20 UTC] {workflow_reporter.py:41} INFO - Sink: Processed 0 records, found 0 errors
[2023-05-26, 02:17:20 UTC] {workflow_reporter.py:34} INFO - Source: Processed 0 records, filtered 0 records, found 0 errors
[2023-05-26, 02:17:20 UTC] {workflow_reporter.py:41} INFO - Sink: Processed 0 records, found 0 errors
[2023-05-26, 02:18:20 UTC] {workflow_reporter.py:34} INFO - Source: Processed 0 records, filtered 0 records, found 0 errors
[2023-05-26, 02:18:20 UTC] {workflow_reporter.py:41} INFO - Sink: Processed 0 records, found 0 errors
[2023-05-26, 02:19:20 UTC] {workflow_reporter.py:34} INFO - Source: Processed 0 records, filtered 0 records, found 0 errors
[2023-05-26, 02:19:20 UTC] {workflow_reporter.py:41} INFO - Sink: Processed 0 records, found 0 errors
[2023-05-26, 02:20:20 UTC] {workflow_reporter.py:34} INFO - Source: Processed 0 records, filtered 0 records, found 0 errors
[2023-05-26, 02:20:20 UTC] {workflow_reporter.py:41} INFO - Sink: Processed 0 records, found 0 errors
[2023-05-26, 02:21:10 UTC] {core.py:514} WARNING - Unexpected error while processing sample data for auto pii tagging - HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f949379a520>: Failed to establish a new connection: [Errno 110] Connection timed out'))
[2023-05-26, 02:21:10 UTC] {core.py:517} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/processor/pii.py", line 129, in __init__
    spacy.load(SPACY_EN_MODEL)
  File "/home/airflow/.local/lib/python3.9/site-packages/spacy/__init__.py", line 54, in load
    return util.load_model(
  File "/home/airflow/.local/lib/python3.9/site-packages/spacy/util.py", line 439, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_md'. It doesn't seem to be a Python package or a valid path to a data directory.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f949379a520>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f949379a520>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/processor/core.py", line 504, in process_pii_sensitive
    entity_scanner = NERScanner(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/processor/pii.py", line 134, in __init__
    download(SPACY_EN_MODEL)
  File "/home/airflow/.local/lib/python3.9/site-packages/spacy/cli/download.py", line 70, in download
    compatibility = get_compatibility()
  File "/home/airflow/.local/lib/python3.9/site-packages/spacy/cli/download.py", line 97, in get_compatibility
    r = requests.get(about.__compatibility__)
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f949379a520>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**To Reproduce**
[See the attachment file ]
Create a table containing PII sample data, in my case it is OPEN_METADATA_PII_SAMPLE
Ingest the metadata of this table successfully.
Create a Ingestion Profiler job, with Ingest Sample Data =Yes, Auto Tag PII=Yes
Run this profiler job in Airflow, Airflow job status = OK but there are error message in Airflow Log as below 
No PII tagging is done.
{core.py:514} WARNING - Unexpected error while processing sample data for auto pii tagging - HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f949379a520>: Failed to establish a new connection: [Errno 110] Connection timed out'))

OSError: [E050] Can't find model 'en_core_web_md'. It doesn't seem to be a Python package or a valid path to a data directory.

**Expected behavior**

PII Tagging is done and no error showing as above.

**Version:**
 - OS:   Ubuntu 
 - Python version: 3.9.13
 - OpenMetadata version: 1.0.0
 - OpenMetadata Ingestion package version: 1.0.0

**Additional context**

[Ingestion_Profiler_With_PII_Tag_Enable_Steps.docx](https://github.com/open-metadata/OpenMetadata/files/11572453/Ingestion_Profiler_With_PII_Tag_Enable_Steps.docx)

**Comment by svroonland** [comment] 2023-06-05 09:51
> Connection timed out
That's the cause of this issue. We ran into it as well, running on a K8s environment that has external traffic disabled by default. The solution was to configure the network policy to open up network access to raw.githubusercontent.com and github.com. Let me know if you're interested in the network policy spec.

**Comment by sureshms** [comment] 2023-06-29 00:45
@HongQuanVu, please see the comment by @svroonland. I am closing the issue for now. Reopen if you still run into it.

**Closed by sureshms** 2023-06-29 00:45 UTC
