### ISSUE TITLE
Owner doesn't show up after changing the owner

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#869] opened 2021-10-20 04:28 UTC
Steps to reproduce:
- Go to the Table your Team is the owner
- Change the Owner to your user
- Refresh the page

Expected Result:
Owner changed to your User

Actual Result:
Owner shows empty
<img width="1043" alt="Screenshot 2021-10-20 at 9 58 07 AM" src="https://user-images.githubusercontent.com/40225091/138028397-f163b0b1-a944-43c9-93b0-07fe785eed5b.png">

**Comment by harshach** [comment] 2021-10-20 04:37
```Request URL: https://sandbox.open-metadata.org/api/v1/tables/84ab7a06-d5f4-4560-a3bd-397fe8251982
Request Method: PATCH
Status Code: 200 OK
Remote Address: 65.21.204.83:443
Referrer Policy: strict-origin-when-cross-origin```

```{"id":"84ab7a06-d5f4-4560-a3bd-397fe8251982","name":"stg_listing_reports","description":"Staging table to compute the total tickets and revenue generated per listing at a venue.","href":"http://127.0.0.1:8585/api/v1/tables/84ab7a06-d5f4-4560-a3bd-397fe8251982","tableType":"Regular","fullyQualifiedName":"aws_redshift.public.stg_listing_reports","columns":[{"name":"list_id","dataType":"INT","dataLength":1,"dataTypeDisplay":"int","fullyQualifiedName":"aws_redshift.public.stg_listing_reports.list_id","tags":[],"constraint":"NULL","ordinalPosition":1},{"name":"seller_id","dataType":"INT","dataLength":1,"dataTypeDisplay":"int","fullyQualifiedName":"aws_redshift.public.stg_listing_reports.seller_id","tags":[],"constraint":"NULL","ordinalPosition":2},{"name":"venue_id","dataType":"INT","dataLength":1,"dataTypeDisplay":"int","fullyQualifiedName":"aws_redshift.public.stg_listing_reports.venue_id","tags":[],"constraint":"NULL","ordinalPosition":3},{"name":"num_tickets","dataType":"INT","dataLength":1,"dataTypeDisplay":"int","fullyQualifiedName":"aws_redshift.public.stg_listing_reports.num_tickets","tags":[],"constraint":"NULL","ordinalPosition":4},{"name":"total_price","dataType":"INT","dataLength":1,"dataTypeDisplay":"int","fullyQualifiedName":"aws_redshift.public.stg_listing_reports.total_price","tags":[],"constraint":"NULL","ordinalPosition":5}],"owner":{"id":"bf0a8a0a-075a-45c7-867c-3de8e290a621","type":"user","name":"harsha","href":"http://127.0.0.1:8585/api/v1/users/bf0a8a0a-075a-45c7-867c-3de8e290a621"},"database":{"id":"bfb736c4-88f9-411d-9c79-230d535fa76f","type":"database","name":"aws_redshift.public","href":"http://127.0.0.1:8585/api/v1/databases/bfb736c4-88f9-411d-9c79-230d535fa76f"},"tags":[{"tagFQN":"Tier.Tier4","labelType":"Manual","state":"Confirmed"}]}```
Patch call is successful

**Comment by Sachin-chaurasiya** [comment] 2021-11-17 12:58
The issue with root cause #1154,  For the owner placeholder we are using `displayName` but if the owner is admin then we are not getting disaplyName that's why the owner name is not showing up.

Closing this issue as its taken care of by #1166

**Closed by Sachin-chaurasiya** 2021-11-17 12:58 UTC
Labels: bug
