### ISSUE TITLE
Druid Profiler Ingestion Failed

### ISSUE THREAD

**Issue by Supan90-Shah3006** [open-metadata/OpenMetadata#12819] opened 2023-08-09 12:24 UTC
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ans : Backend, Ingestion Framework

**Describe the bug**
In Druid Connector, Profiler Ingestion is failing for all databases & throwing below error.
![image](https://github.com/open-metadata/OpenMetadata/assets/71488507/c0a61713-192a-4954-bbe6-8459ec6b9451)

**To Reproduce**
These are the Schema For All the databases that I have.
![image](https://github.com/open-metadata/OpenMetadata/assets/71488507/81b8f52a-a176-4f70-8108-0ecda2bd8f14)
![image](https://github.com/open-metadata/OpenMetadata/assets/71488507/98ecd14f-7ad9-41fe-b1e6-746ce4a1fb10)
![image](https://github.com/open-metadata/OpenMetadata/assets/71488507/04347c2a-74b0-4318-a0f7-f0dbcb44694e)
![image](https://github.com/open-metadata/OpenMetadata/assets/71488507/a0df59f3-8c11-4aaa-bb15-4b83e95b3741)

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - OpenMetadata version: 1.1.0, 1.1.1

**Additional context**

**Comment by pmbrull** [comment] 2023-10-09 15:36
@ayush-shah please correct me if I am wrong but most of the issues should be solved in 1.2.0.

For the sampling error, looks like the table might be empty, since we could not reproduce it.

@ayush-shah could we close this?

**Comment by ayush-shah** [comment] 2023-10-09 15:43
@pmbrull we can close this, 1.2.0 should resolve most the issues, table being empty, we won't profile it, we will have a check for it in the future release that would take care of other issues that we see in the above traceback.

@Supan90-Shah3006 feel free to open the issue if you face similar troubles in the latest release around ProgrammingError.
Closing this ticket, Thanks.

**Closed by ayush-shah** 2023-10-09 15:43 UTC
Labels: bug, Ingestion
