### ISSUE TITLE
[SNOWFLAKE] Ingestion fails to retrieve sample data

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#2413] opened 2022-01-25 10:05 UTC
Snowflake Ingestion fails to retrieve sample data with the below error -

```
Failed to generate sample data for table_name - (snowflake.connector.errors.ProgrammingError) 002003 (02000): SQL compilation error:
Schema 'DATABASE_NAME."schema_name"' does not exist or not authorized.
[SQL: select * from "schema_name"."<table_name>" Limit 50]
```

It seems snowflake requires all values of Table Name, Database Name, Schema Name to be in UPPER Case while query in format of "DATABASE_NAME"."SCHEMA_NAME"."TABLE_NAME" as fully qualified table name.

I added query in json config to look like below -
```
{
 "source" : {
    "config": {
        ....
        "query": "select * from \"{}\".\"{}\" Limit 50",
        "include_views": "false",
        ....
    }
  }
}
```

cc - @ayush-shah , @harshach

**Comment by codingwithabhi** [comment] 2022-02-03 05:12
I will work on this

**Comment by shahsank3t** [comment] 2022-02-03 05:15
Assigned it to you @codingwithabhi

**Comment by harshach** [comment] 2022-02-06 18:33
@codingwithabhi @ayush-shah any updates?

**Comment by ayush-shah** [comment] 2022-02-08 08:42
Couldn't reproduce this issue, labelling it as backlog.

**Comment by shannonbradshaw** [comment] 2022-03-25 19:15
I think I've bumped into this. I created a table called testdb.cookies in our snowflake test instance. When I ingest metadata into my docker deployment of OM using the Snowflake connector, I don't see the sample data for the cookies table (or others). I'm using:

**Closed** 2022-05-16 06:22 UTC
Labels: bug, Ingestion
