### ISSUE TITLE
Ingestion: Databricks profiler not working when  `Use Unity Catalog` enabled

### ISSUE THREAD

**Issue by ebongzzang** [open-metadata/OpenMetadata#12885] opened 2023-08-16 09:38 UTC
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
- It seems like relates to ingestion Framework

**Describe the bug**

- Databricks profiler not working when enabled `Use Unity Catalog`.  After disabling it, it works as expected. here is stacktrace.

```
--------------------------------------------------------------------------------
[2023-08-16, 12:00:13 KST] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-08-16, 12:00:13 KST] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-16, 12:00:14 KST] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): profiler_task> on 2023-08-15 03:00:00+00:00
[2023-08-16, 12:00:14 KST] {standard_task_runner.py:52} INFO - Started process 111 to run task
[2023-08-16, 12:00:14 KST] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'databricks_profiler_IExXS4Tl', 'profiler_task', 'scheduled__2023-08-15T03:00:00+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/databricks_profiler_IExXS4Tl.py', '--cfg-path', '/tmp/tmp1035sahv', '--error-file', '/tmp/tmpgfbidpwv']
[2023-08-16, 12:00:14 KST] {standard_task_runner.py:80} INFO - Job 187: Subtask profiler_task
[2023-08-16, 12:00:14 KST] {task_command.py:371} INFO - Running <TaskInstance: databricks_profiler_IExXS4Tl.profiler_task scheduled__2023-08-15T03:00:00+00:00 [running]> on host databricksprofileriexxs4tlprof-3282af2414ec45609b1768e3ef16d9c1
[2023-08-16, 12:00:15 KST] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/models/renderedtifields.py:249 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-08-16, 12:00:15 KST] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=databricks_profiler_IExXS4Tl
AIRFLOW_CTX_TASK_ID=profiler_task
AIRFLOW_CTX_EXECUTION_DATE=2023-08-15T03:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-15T03:00:00+00:00
[2023-08-16, 12:00:17 KST] {test_connections.py:215} INFO - Test connection results:
[2023-08-16, 12:00:17 KST] {test_connections.py:216} INFO - failed=[] success=["'CheckAccess': Pass", "'GetDatabases': Pass", "'GetSchemas': Pass", "'GetTables': Pass", "'GetViews': Pass", "'GetQueries': Pass"] warning=[]
[2023-08-16, 12:00:17 KST] {workflow.py:128} INFO - Starting profiler for service databricks:databricks
[2023-08-16, 12:00:18 KST] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/ingestion/profiler.py", line 49, in profiler_workflow
    workflow.execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/api/workflow.py", line 326, in execute
    raise err
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/api/workflow.py", line 317, in execute
    profile = self.run_profiler(entity, profiler_source)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/api/workflow.py", line 269, in run_profiler
    profiler_runner: Profiler = profiler_source.get_profiler_runner(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/source/base_profiler_source.py", line 205, in get_profiler_runner
    profiler_interface = self.create_profiler_interface(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/source/base_profiler_source.py", line 185, in create_profiler_interface
    ] = ProfilerProtocol.create(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/interface/profiler_protocol.py", line 99, in create
    return cls.subclasses[_profiler_type](
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/profiler/interface/sqlalchemy/profiler_interface.py", line 109, in __init__
    self.set_catalog(self.session)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/mixins/sqalchemy/sqa_mixin.py", line 94, in set_catalog
    bind.execute(
AttributeError: 'WorkspaceClient' object has no attribute 'execute'
```

**To Reproduce**

1. Create `Databricks` Connection with `Use unity catalog` enabled.
2. Add profiler Ingestion.
3. View logs in open-metdata airflow tasks

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - OS: Running in k8s env, using offical openmetadata helm chart
 - Python version: 3.9.12
 - OpenMetadata version: 1.1.0
 - OpenMetadata Ingestion package version: I don't know which version of used in docker images. i've used `openmetadata/ingestion:1.1.0` image

**Additional context**

- IMHO, the below line should be fixed.
	- https://github.com/open-metadata/OpenMetadata/blob/9e6e00caf9c90dd2a1de6f53311058f0fd7445a1/ingestion/src/metadata/ingestion/source/database/databricks/connection.py#L57-L61

**Comment by ulixius9** [comment] 2023-09-06 10:59
closing this ticket as duplicate of #12947

**Closed by ulixius9** 2023-09-06 10:59 UTC
Labels: Ingestion
