### ISSUE TITLE
Custom Login Logo does not change after adding new custom logo

### ISSUE THREAD

**Issue by CheyenneRobinson** [open-metadata/OpenMetadata#11503] opened 2023-05-09 13:53 UTC
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
It affects the UI.

**Describe the bug**
I have followed the directions located on the url provided on changing the custom log but after completing the changes the Login logo does not change to the new custom logo. The application was also stop and started again.  The navigation logo changed successfully although it flickers back to the default log if you click it.  It then changes back to the new custom logo.

https://docs.open-metadata.org/v1.0.0/how-to-guides/how-to-add-custom-logo

**To Reproduce**
Follow the instructions from the above URL and then test whether is was applied.  Stop and the start OpenMetadata.

Screenshots or steps to reproduce
<img width="282" alt="Screenshot 2023-05-09 072919" src="https://github.com/open-metadata/OpenMetadata/assets/131470710/4f1e2498-05ad-4d44-81fc-ffd279ceebf8">
<img width="408" alt="Screenshot 2023-05-09 072731" src="https://github.com/open-metadata/OpenMetadata/assets/131470710/cd1fc54c-9ed1-4d70-96e8-b490c5985168">
<img width="1340" alt="Screenshot 2023-05-09 072305" src="https://github.com/open-metadata/OpenMetadata/assets/131470710/45913b74-a983-4ab7-b2ae-cef201ba4875">

**Expected behavior**
I expected the Login log to change to the new custom logo as the directions states.

**Version:**
 - OS: RHEL 8.6
 - Python version: 3.9.13
 - OpenMetadata version: 1.0
 - OpenMetadata Ingestion package version: openmetadata-ingestion==1.0.0.0

**Additional context**

**Comment by Sachin-chaurasiya** [comment] 2023-05-09 14:33
Hello @CheyenneRobinson , Thanks for filing an issue, however, it's not reproducible on our end.

Here is the config I tried with and it worked as expected.

```
applicationConfig:
  logoConfig:
    customLogoUrlPath: ${OM_CUSTOM_LOGO_URL_PATH:-"https://user-images.githubusercontent.com/59080942/155874645-939f754a-35ee-4fed-a68a-465f55981a7f.png"} #login page logo
    customMonogramUrlPath: ${OM_CUSTOM_MONOGRAM_URL_PATH:-"https://user-images.githubusercontent.com/59080942/155874645-939f754a-35ee-4fed-a68a-465f55981a7f.png"} #nav bar logo
```


https://github.com/open-metadata/OpenMetadata/assets/59080942/8feb0b3e-b828-48c4-beae-90967f02d614


Can you check if you get the proper `logoConfig` from this endpoint `api/v1/system/config/applicationConfig` response?
Also, may I know, if both images are hosted on the same domain?

**Comment by CheyenneRobinson** [comment] 2023-05-09 16:24
here is the response from "api/v1/system/config/applicationConfig"

{"logoConfig":{"customLogoUrlPath":"https://host:port/om_nasa_logo.png","customMonogramUrlPath":"https://host:port/om_nasa_logo_monogram.png"},"loginConfig":{"maxLoginFailAttempts":3,"accessBlockTime":600,"jwtTokenExpiryTime":3600}}

**Comment by harshach** [comment] 2023-05-09 16:31
@Sachin-chaurasiya @mohityadav766 lets move this setting out of the configuration into UI -> Settings -> OpenMetadata section. It will be easier for users to add and change those.

**Comment by Sachin-chaurasiya** [comment] 2023-05-09 17:51
> Both images are hosted on the same domain. Everything is on the same server.
> 
> Unfortunately i can not post the video of it as it would contain information that we can not display.
> 
> Could it be that we are using Keycloak as an authentication piece? Our login screen is different as it says Keycloak
> 
> <img alt="Screenshot 2023-05-09 112102" width="1277" src="https://user-images.githubusercontent.com/131470710/237158300-2806a7b0-bf96-4251-a0cb-f284a2a691a4.png">

@CheyenneRobinson, No that could not be the case because we are using the same component, and based on auth provider we show different Elements, however, we will try it out with that as well.

**Comment by CheyenneRobinson** [comment] 2023-05-10 20:31
Ok so we were able to get the custom logo to appear once we changed our provider.  Before we were using keycloak so the provider was custom-oidc.  Today we began using the integrated SAML configuration and so we changed the provider to saml.  Once we restarted OM the custom logo was there so it does seem to be based on the provider that you are using.  Thanks for looking into this.

**Comment by Sachin-chaurasiya** [comment] 2023-05-11 05:53
> Ok so we were able to get the custom logo to appear once we changed our provider. Before we were using keycloak so the provider was custom-oidc. Today we began using the integrated SAML configuration and so we changed the provider to saml. Once we restarted OM the custom logo was there so it does seem to be based on the provider that you are using. Thanks for looking into this.

Thanks, @CheyenneRobinson , for the update, we will try it out with different providers.

**Comment by Sachin-chaurasiya** [comment] 2023-05-16 06:05
Hello @CheyenneRobinson , we found the issue and will fix it.

**Comment by CheyenneRobinson** [comment] 2023-05-16 12:45
> Hello @CheyenneRobinson , we found the issue and will fix it.

Thanks!

**Comment by Sachin-chaurasiya** [comment] 2023-05-16 12:52
Reopening as PR is not merged yet https://github.com/open-metadata/OpenMetadata/pull/11597

**Closed** 2023-05-17 05:56 UTC
Labels: UI, backend
