### ISSUE TITLE
Hive Connector doesn't work with tables with high number of partitions

### ISSUE THREAD

**Issue by pjain-branch** [open-metadata/OpenMetadata#7359] opened 2022-09-09 16:05 UTC
**Affected module**
Hive connector - Ingestion Framework

**Describe the bug**
Hi, so I took openmetadata to production and the hive connector can’t finish ingesting metadata from tables. Openmetadata uses Describe <table_name> to get metadata of tables from hive and also gets getPartitionsByNames_ which is taking a whopping 125 seconds for tables with a lot of partitions. This isn't sustainable with hive. Is there a way to go around this issue because a few of our important tables have a lot of partitions. Logs from hiveserver2:
```
17:58:51.249 [8be7349c-a48a-4025-894c-f2769b677c06 HiveServer2-Handler-Pool: Thread-76185] DEBUG hive.ql.exec.DDLTask - DDLTask: got data for card_dimension_dict
17:58:51.249 [8be7349c-a48a-4025-894c-f2769b677c06 HiveServer2-Handler-Pool: Thread-76185] DEBUG hive.log - DDL: struct card_dimension_dict { i64 timestamp, string app_id, string publisher_id, string dimension, string dimension_value, i64 freq}
18:00:59.317 [8be7349c-a48a-4025-894c-f2769b677c06 HiveServer2-Handler-Pool: Thread-76185] DEBUG hive.ql.exec.DDLTask - DDLTask: written data for card_dimension_dict
18:00:59.317 [8be7349c-a48a-4025-894c-f2769b677c06 HiveServer2-Handler-Pool: Thread-76185] DEBUG org.apache.hadoop.hive.ql.log.PerfLogger - </PERFLOG method=runTasks start=1662659931216 end=1662660059317 duration=128101 from=org.apache.hadoop.hive.ql.Driver>
18:00:59.317 [8be7349c-a48a-4025-894c-f2769b677c06 HiveServer2-Handler-Pool: Thread-76185] DEBUG org.apache.hadoop.hive.ql.log.PerfLogger - </PERFLOG method=Driver.execute start=1662659931216 end=1662660059317 duration=128101 from=org.apache.hadoop.hive.ql.Driver>
18:00:59.317 [8be7349c-a48a-4025-894c-f2769b677c06 HiveServer2-Handler-Pool: Thread-76185] INFO hive.ql.metadata.Hive - Dumping metastore api call timing information for : execution phase
18:00:59.317 [8be7349c-a48a-4025-894c-f2769b677c06 HiveServer2-Handler-Pool: Thread-76185] DEBUG hive.ql.metadata.Hive - Total time spent in each metastore function (ms): {isCompatibleWith_(HiveConf, )=0, getTable_(String, String, )=33, listPartitionNames_(String, String, short, )=2431, getPartitionsByNames_(String, String, List, )=125196}
18:00:59.317 [8be7349c-a48a-4025-894c-f2769b677c06 HiveServer2-Handler-Pool: Thread-76185] INFO hive.ql.metadata.Hive - Total time spent in this metastore function was greater than 1000ms : listPartitionNames_(String, String, short, )=2431
18:00:59.317 [8be7349c-a48a-4025-894c-f2769b677c06 HiveServer2-Handler-Pool: Thread-76185] INFO hive.ql.metadata.Hive - Total time spent in this metastore function was greater than 1000ms : getPartitionsByNames_(String, String, List, )=125196
18:00:59.317 [8be7349c-a48a-4025-894c-f2769b677c06 HiveServer2-Handler-Pool: Thread-76185] INFO org.apache.hadoop.hive.ql.Driver - Completed executing command(queryId=root_20220908175851_a8f81bcc-7570-472f-8306-3ec578b98835); Time taken: 128.101 seconds
```

Is there a reason we get partition information from hive? I have run the same query with presto connector  and that takes like a second or 2.
Right now it is not working for tables with large number of partitions. The connection drops with hive and I think Openmetadata doesn't retry and fails.

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: 0.11.4
 - OpenMetadata Ingestion package version:  openmetadata-ingestion[hive]==0.11.4.0
 - Hive version - 2.3.3

**Additional context**

**Comment by harshach** [comment] 2022-09-12 03:17
@pjain-branch I am closing this since the issue is not related to hive connector

**Closed by harshach** 2022-09-12 03:17 UTC
Labels: P2, Ingestion
