### ISSUE TITLE
No Schema name in Database service yet it is showing on front

### ISSUE THREAD

**Issue by ManiarSagar** [open-metadata/OpenMetadata#12968] opened 2023-08-23 05:26 UTC
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion

**Describe the bug**
First of all if we perform a metadata ingestion in snowflake database service. It is taking proper database, schema and table. and after that if we perform a profiler ingestion it is succesing.
But if i go and rename the schema name from snowflake . and again if i perform metadata ingestion. It is taking new renamed schema name but along with that it is also showing old schema name too. and after that if i perform profiler ingestion, it is failing as no such schema name is found.

**To Reproduce**
Perform snowflake connection, metadata ingestion and then rename the schema name from snowflake. and again perform metadata ingestion in same connection of snowflake.

**Expected behavior**
To show the latest schema names present on the snowflake.

**Version:**
 - OpenMetadata version: 1.1.1

**Additional context**

**Comment by ulixius9** [comment] 2023-09-15 08:41
Hey @ManiarSagar, in case you are renaming and removing any schema from snowflake/data source and if you want to reflect the same in OpenMetadata you will have to enable the "Mark All Deleted Tables" in your ingestion pipeline and this should resolve your error. closing this ticket as this is not a bug let us know in the OpenMetadata Slack Support channel if you still face this issue.

![image](https://github.com/open-metadata/OpenMetadata/assets/39544459/6215432e-7489-4e21-b586-1dc267a44a71)

**Closed by ulixius9** 2023-09-15 08:41 UTC
Labels: Ingestion, validation
