### ISSUE TITLE
Change default lineage display depth

### ISSUE THREAD

**Issue by datapopcorn** [open-metadata/OpenMetadata#16711] opened 2024-06-19 06:11 UTC
**Is your feature request related to a problem? Please describe.**
For now, the default depth display on lineage page is 3,
we have to change it to other number we need every time.

**Describe the solution you'd like**

I hope there are configuration we can add to set the default depth we need. 

**Describe alternatives you've considered**

we have to change it to other number every time.

**Additional context**

**Comment by harshach** [comment] 2024-06-20 02:27
@sonika-shah we talked about adding global settings for such use-cases cc @mohityadav766

**Comment by karanh37** [comment] 2024-06-25 10:37
Duplicate of #15408

**Closed by karanh37** 2024-06-25 10:37 UTC
Labels: enhancement, P2, Lineage-Editor
