### ISSUE TITLE
Ingest the policy tags exactly as they are in the BigQuery

### ISSUE THREAD

**Issue by juliasouza7** [open-metadata/OpenMetadata#9851] opened 2023-01-20 20:51 UTC
**Is your feature request related to a problem? Please describe.**
Open Metadata does not ingest taxonomies along with policy tags. For example: instead of #BigQueryPolicyTags.name, bring #PII.name

**Describe the solution you'd like**
Basically I need the ingestion of policy tags to be the same way as BQ. Another point: not having to add the Category Name field to ingestion.

![whatsapp_image_2023-01-18_at_18 08 41__1_](https://user-images.githubusercontent.com/66895551/213802739-f3c26d46-6715-49c8-b00e-19eb5723c9a8.jpeg)
<img width="450" alt="MicrosoftTeams-image (13)" src="https://user-images.githubusercontent.com/66895551/213802778-5fe9d749-7c88-4997-a55b-ff2d0ff399cd.png">
![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/66895551/213802830-91f07641-8122-4ae2-9417-f4d972832401.png)

**Comment by ayush-shah** [comment] 2023-02-03 06:49
duplicate of #9830

**Closed by ayush-shah** 2023-02-03 06:49 UTC
Labels: enhancement, Ingestion
