### ISSUE TITLE
Database Page fails to load

### ISSUE THREAD

**Issue by juliarvalenti** [open-metadata/OpenMetadata#1876] opened 2021-12-21 16:48 UTC
Hello, 

Visiting the database page gives a "TypeError: i is undefined" error and the page goes completely blank rendering the application unusable.  Please see the attached video for details.

https://user-images.githubusercontent.com/42276144/146967518-7ed17066-774c-415a-8b74-fb3c6569e6fc.mov

**Comment by harshach** [comment] 2021-12-22 23:55
@juliarvalenti if you don't mind can you provide some details on what you getting in the APIs. We tried to reproduce this on our side but couldn't find the issue.

**Comment by Sachin-chaurasiya** [comment] 2022-01-07 06:29
Closing this issue because We tried to reproduce this on our side but couldn't find the issue.

**Comment by juliarvalenti** [comment] 2022-01-19 16:28
So sorry for the very late response, but I can still reproduce this on v0.7.

The API responses are as follows: 

The APIResponse from /api/databases/name/world_x_db.world_x is
```
{"id":"c41bbae2-d680-41f4-bade-da4fe8da7a3d","name":"world_x","fullyQualifiedName":"world_x_db.world_x","version":0.1,"updatedAt":1642608122717,"updatedBy":"anonymous","href":"http://localhost:8585/api/v1/databases/c41bbae2-d680-41f4-bade-da4fe8da7a3d","service":{"id":"980863b2-a215-4a8a-8821-8b39f2370cf6","type":"databaseService","name":"world_x_db","description":"This is a demo ingestion of a database for integration testing.\n\nThe database is called \"world_x\" and the connection url is \"redacted\"","href":"http://localhost:8585/api/v1/services/databaseServices/980863b2-a215-4a8a-8821-8b39f2370cf6"},"serviceType":"MySQL"}
```

The APIResponse from /api/v1/tables?fields=owner,tags,columns,usageSummary&database=world_x_db.world_x is
```
{"data":[{"id":"c4fe497e-5b99-44b9-99f3-e959ccfb0e1f","name":"city","fullyQualifiedName":"world_x_db.world_x.city","description":"","version":0.1,"updatedAt":1642608123130,"updatedBy":"anonymous","href":"http://localhost:8585/api/v1/tables/c4fe497e-5b99-44b9-99f3-e959ccfb0e1f","tableType":"Regular","columns":[{"name":"ID","dataType":"INT","dataLength":1,"dataTypeDisplay":"int(1)","fullyQualifiedName":"world_x_db.world_x.city.ID","tags":[],"constraint":"NOT_NULL","ordinalPosition":1},{"name":"Name","dataType":"STRING","dataLength":1,"dataTypeDisplay":"string(1)","fullyQualifiedName":"world_x_db.world_x.city.Name","tags":[],"constraint":"NOT_NULL","ordinalPosition":2},{"name":"CountryCode","dataType":"STRING","dataLength":1,"dataTypeDisplay":"string(1)","fullyQualifiedName":"world_x_db.world_x.city.CountryCode","tags":[],"constraint":"NOT_NULL","ordinalPosition":3},{"name":"District","dataType":"STRING","dataLength":1,"dataTypeDisplay":"string(1)","fullyQualifiedName":"world_x_db.world_x.city.District","tags":[],"constraint":"NOT_NULL","ordinalPosition":4},{"name":"Info","dataType":"JSON","dataLength":1,"dataTypeDisplay":"json(1)","fullyQualifiedName":"world_x_db.world_x.city.Info","tags":[],"constraint":"NULL","ordinalPosition":5}],"database":{"id":"c41bbae2-d680-41f4-bade-da4fe8da7a3d","type":"database","name":"world_x_db.world_x","href":"http://localhost:8585/api/v1/databases/c41bbae2-d680-41f4-bade-da4fe8da7a3d"},"service":{"id":"980863b2-a215-4a8a-8821-8b39f2370cf6","type":"databaseService","name":"world_x_db","description":"This is a demo ingestion of a database for integration testing.\n\nThe database is called \"world_x\" and the connection url is \"redacted\""},"serviceType":"MySQL","tags":[],"usageSummary":{"dailyStats":{"count":0,"percentileRank":0.0},"weeklyStats":{"count":0,"percentileRank":0.0},"monthlyStats":{"count":0,"percentileRank":0.0},"date":"2022-01-19"}},{"id":"b9711620-0fa7-4f14-8f4a-86b4319fda1b","name":"country","fullyQualifiedName":"world_x_db.world_x.country","description":"","version":0.1,"updatedAt":1642608142045,"updatedBy":"anonymous","href":"http://localhost:8585/api/v1/tables/b9711620-0fa7-4f14-8f4a-86b4319fda1b","tableType":"Regular","columns":[{"name":"Code","dataType":"STRING","dataLength":1,"dataTypeDisplay":"string(1)","fullyQualifiedName":"world_x_db.world_x.country.Code","tags":[],"constraint":"NOT_NULL","ordinalPosition":1},{"name":"Name","dataType":"STRING","dataLength":1,"dataTypeDisplay":"string(1)","fullyQualifiedName":"world_x_db.world_x.country.Name","tags":[],"constraint":"NOT_NULL","ordinalPosition":2},{"name":"Capital","dataType":"INT","dataLength":1,"dataTypeDisplay":"int(1)","fullyQualifiedName":"world_x_db.world_x.country.Capital","tags":[],"constraint":"NULL","ordinalPosition":3},{"name":"Code2","dataType":"STRING","dataLength":1,"dataTypeDisplay":"string(1)","fullyQualifiedName":"world_x_db.world_x.country.Code2","tags":[],"constraint":"NOT_NULL","ordinalPosition":4}],"database":{"id":"c41bbae2-d680-41f4-bade-da4fe8da7a3d","type":"database","name":"world_x_db.world_x","href":"http://localhost:8585/api/v1/databases/c41bbae2-d680-41f4-bade-da4fe8da7a3d"},"service":{"id":"980863b2-a215-4a8a-8821-8b39f2370cf6","type":"databaseService","name":"world_x_db","description":"This is a demo ingestion of a database for integration testing.\n\nThe database is called \"world_x\" and the connection url is \"redacted\""},"serviceType":"MySQL","tags":[],"usageSummary":{"dailyStats":{"count":0,"percentileRank":0.0},"weeklyStats":{"count":0,"percentileRank":0.0},"monthlyStats":{"count":0,"percentileRank":0.0},"date":"2022-01-19"}},{"id":"0511fd52-d1a1-4a20-945a-36f9721df21e","name":"countryinfo","fullyQualifiedName":"world_x_db.world_x.countryinfo","description":"","version":0.1,"updatedAt":1642608155270,"updatedBy":"anonymous","href":"http://localhost:8585/api/v1/tables/0511fd52-d1a1-4a20-945a-36f9721df21e","tableType":"Regular","columns":[{"name":"doc","dataType":"JSON","dataLength":1,"dataTypeDisplay":"json(1)","fullyQualifiedName":"world_x_db.world_x.countryinfo.doc","tags":[],"constraint":"NULL","ordinalPosition":1},{"name":"_id","dataType":"BYTES","dataLength":1,"dataTypeDisplay":"bytes(1)","fullyQualifiedName":"world_x_db.world_x.countryinfo._id","tags":[],"constraint":"NULL","ordinalPosition":2},{"name":"_json_schema","dataType":"JSON","dataLength":1,"dataTypeDisplay":"json(1)","fullyQualifiedName":"world_x_db.world_x.countryinfo._json_schema","tags":[],"constraint":"NULL","ordinalPosition":3}],"database":{"id":"c41bbae2-d680-41f4-bade-da4fe8da7a3d","type":"database","name":"world_x_db.world_x","href":"http://localhost:8585/api/v1/databases/c41bbae2-d680-41f4-bade-da4fe8da7a3d"},"service":{"id":"980863b2-a215-4a8a-8821-8b39f2370cf6","type":"databaseService","name":"world_x_db","description":"This is a demo ingestion of a database for integration testing.\n\nThe database is called \"world_x\" and the connection url is \"redacted\""},"serviceType":"MySQL","tags":[],"usageSummary":{"dailyStats":{"count":0,"percentileRank":0.0},"weeklyStats":{"count":0,"percentileRank":0.0},"monthlyStats":{"count":0,"percentileRank":0.0},"date":"2022-01-19"}},{"id":"19170aff-ecf9-4b40-b66a-4a772feff12a","name":"countrylanguage","fullyQualifiedName":"world_x_db.world_x.countrylanguage","description":"","version":0.1,"updatedAt":1642608219278,"updatedBy":"anonymous","href":"http://localhost:8585/api/v1/tables/19170aff-ecf9-4b40-b66a-4a772feff12a","tableType":"Regular","columns":[{"name":"CountryCode","dataType":"STRING","dataLength":1,"dataTypeDisplay":"string(1)","fullyQualifiedName":"world_x_db.world_x.countrylanguage.CountryCode","tags":[],"constraint":"NOT_NULL","ordinalPosition":1},{"name":"Language","dataType":"STRING","dataLength":1,"dataTypeDisplay":"string(1)","fullyQualifiedName":"world_x_db.world_x.countrylanguage.Language","tags":[],"constraint":"NOT_NULL","ordinalPosition":2},{"name":"IsOfficial","dataType":"ENUM","dataLength":1,"dataTypeDisplay":"enum(1)","fullyQualifiedName":"world_x_db.world_x.countrylanguage.IsOfficial","tags":[],"constraint":"NOT_NULL","ordinalPosition":3},{"name":"Percentage","dataType":"INT","dataLength":1,"dataTypeDisplay":"int(1)","fullyQualifiedName":"world_x_db.world_x.countrylanguage.Percentage","tags":[],"constraint":"NOT_NULL","ordinalPosition":4}],"database":{"id":"c41bbae2-d680-41f4-bade-da4fe8da7a3d","type":"database","name":"world_x_db.world_x","href":"http://localhost:8585/api/v1/databases/c41bbae2-d680-41f4-bade-da4fe8da7a3d"},"service":{"id":"980863b2-a215-4a8a-8821-8b39f2370cf6","type":"databaseService","name":"world_x_db","description":"This is a demo ingestion of a database for integration testing.\n\nThe database is called \"world_x\" and the connection url is \"redacted\""},"serviceType":"MySQL","tags":[],"usageSummary":{"dailyStats":{"count":0,"percentileRank":0.0},"weeklyStats":{"count":0,"percentileRank":0.0},"monthlyStats":{"count":0,"percentileRank":0.0},"date":"2022-01-19"}}],"paging":{"total":4}}
```

![image](https://user-images.githubusercontent.com/42276144/150172784-5f73b7e8-52c2-4c0b-91de-92b4c1acc9d1.png)

**Comment by harshach** [comment] 2022-01-19 16:38
@juliarvalenti this looks like the issue with ingestion. We are using "." as separator for our FQDN
example {service_name}.{database_name}.{schema_name}.{col_name} to refer a entity directly.
if we find any "." in table or column we are replacing that "_DOT_" looks like we missed doing it for database name.
UI assumes that "." is separating entities and I am sure thats what causing the issue
Let me address this on the ingestion side. 
Thanks for reporting the issue.

**Comment by harshach** [comment] 2022-01-21 05:44
@sureshms it would be better if we handle this on server side of replacing "." with "_DOT_" . what you think? otherwise we will keep missing it somewhere and also APIs can break if others don't follow the same convention.
assigning it to you for now.

**Comment by harshach** [comment] 2022-02-06 18:27
@amiorin the ask is to remove "." from any names across the entities and replace it with "_DOT_" this should happen on the backend side.

**Comment by harshach** [comment] 2022-02-06 18:28
Lets make sure we resolve this in Milestone 2

**Comment by harshach** [comment] 2022-02-08 21:37
@amiorin are you picking this up?

**Comment by amiorin** [comment] 2022-02-09 08:37
I'm on it.

**Closed** 2022-02-17 07:21 UTC
Labels: bug, blocker, P0
