### ISSUE TITLE
Error in Profiler Ingestions when upgrading from 1.4.3 to 1.5.1

### ISSUE THREAD

**Issue by tanigawa-haruka** [open-metadata/OpenMetadata#17791] opened 2024-09-11 02:39 UTC
**Affected module**
Ingestion Framework

**Describe the bug**
Upgrading from 1.4.3 to 1.5.1, I get the following error even with Profiler Ingestions without filter conditions.
“databaseFilterPattern returned 0 result. At least 1 database must be returned by the filter pattern”.

**To Reproduce**
Upgrade from 1.4.3 to 1.5.1

**Expected behavior**
Profiler Ingestions run successfully

**Version:**
 - OS:  Linux
 - OpenMetadata version:  1.5.1
 - docker version: 20.10.25

**Additional context**
slack queries
https://openmetadata.slack.com/archives/C02B6955S4S/p1725960392869339

error log
[snowflake_profiler_YCPBp2Md-profiler.log](https://github.com/user-attachments/files/16957069/snowflake_profiler_YCPBp2Md-profiler.log)

**Comment by rchlz** [comment] 2024-09-27 03:54
I got the same error
version：1.5.5

**Comment by TeddyCr** [comment] 2024-10-11 08:40
@rchlz @tanigawa-haruka can you share more information regarding how you are running the profiler for what service and any ingestion filter that might be applied.

Going through 1.4.3 -> 1.5.1 upgrade path with a MySQL service running from the UI I could not reproduce it. Additional information may help us here. 

thanks

**Comment by tanigawa-haruka** [comment] 2024-10-15 05:49
@TeddyCr 
Thank you for reaching out!
The database uses Snowflake, and the profiler was run manually. 
We have not specified any ingestion filters. 
Please kindly check the other details in our [Slack](https://openmetadata.slack.com/archives/C02B6955S4S/p1725960392869339) conversation.

**Comment by TeddyCr** [comment] 2024-10-16 12:50
Thanks @tanigawa-haruka by manually do you mean via the yaml config file? If so could you share it please (please maks sensitive info)

**Comment by tanigawa-haruka** [comment] 2024-10-17 01:13
@TeddyCr 
I'm doing it manually from the OpenMetadata screen. I'm not using any particular file to run it. The Profiler Ingestion settings are as shown in the image.

![image](https://github.com/user-attachments/assets/9fbdca64-4fbf-43dd-9865-3eaacc6f1a3b)
![image](https://github.com/user-attachments/assets/c21c948e-3b04-4281-9484-94ce30ada581)
![image](https://github.com/user-attachments/assets/b2cef981-3444-4dcf-9a88-65061071ea96)

**Comment by TeddyCr** [comment] 2024-10-17 06:09
And you have the same error with the latest version right?

**Comment by tanigawa-haruka** [comment] 2024-10-17 06:25
@TeddyCr 
Yes, it happens in version 1.5.6 as well.

**Comment by TeddyCr** [comment] 2024-10-17 08:42
Have you redeployed the workflow after upgrading?

**Comment by tanigawa-haruka** [comment] 2024-10-17 09:46
@TeddyCr 
Yes, I'm still encountering the error even after redeploying.

**Comment by TeddyCr** [comment] 2024-10-18 10:05
@tanigawa-haruka can you try to create a new one and let me know if you it runs correctly?

**Comment by tanigawa-haruka** [comment] 2024-10-21 01:08
@TeddyCr 
I got the same error when I created a new one.
[snowflake_profiler_uU6zs1Cp-profiler.log](https://github.com/user-attachments/files/17452792/snowflake_profiler_uU6zs1Cp-profiler.log)

**Comment by tanigawa-haruka** [comment] 2024-10-23 04:28
@TeddyCr 
I’m very sorry. If possible, I would appreciate it if you could communicate with me via chat, as I do not speak English.

**Comment by tanigawa-haruka** [comment] 2024-10-25 06:08
@TeddyCr 
Thank you for the advice!!
I wasn't able to solve the problem by simply upgrading to version 1.5.7. However, I was able to resolve the issue by recreating the server and installing 1.5.7.

**Comment by TeddyCr** [comment] 2024-10-25 08:32
Thank you for the information. Could you share more details regarding the steps you took to recreate the server?

**Comment by KazushiMatsuda** [comment] 2024-10-25 08:49
@TeddyCr 
I will answer on behalf of Ms. Tanigawa.
The server is created in AWS (os: aws linux2).
The commands to be executed within linux are as follows

```
sudo amazon-linux-extras install -y docker
```

```
DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
mkdir -p $DOCKER_CONFIG/cli-plugins
curl -SL https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
```
```
sudo usermod -aG docker $USER
exit
```
```
sudo systemctl start docker
```
```
mkdir openmetadata-docker && cd openmetadata-docker
curl -sL -o docker-compose.yml https://github.com/open-metadata/OpenMetadata/releases/download/1.5.7-release/dock
```
```
docker compose -f docker-compose.yml up --detach
```

**Comment by TeddyCr** [comment] 2024-11-07 14:20
Thank you for the information. I'll close this ticket for now.

**Closed by TeddyCr** 2024-11-07 14:20 UTC
Labels: bug, validation
