### ISSUE TITLE
Search by custom properties

### ISSUE THREAD

**Issue by joshliberty** [open-metadata/OpenMetadata#13038] opened 2023-08-30 09:59 UTC
**Is your feature request related to a problem? Please describe.**
We use a lot of custom properties, but they're not really useful since it's not possible to search by their values.
For example, we use the "size" tag to denote bucket sizes. It would have been really useful to be able to search for large buckets, but that's not possible.

**Describe the solution you'd like**
the search page should allow searching by custom property values

**Describe alternatives you've considered**
Using tags, but that's cumbersome and requires us to know in advance what sort of queries we'll want to run, so it's not a good solution. It also requires a lot of manual work to do the tagging, or building it into our connector - which means even more inflexibility in terms of what we can search for.

**Comment by karanh37** [comment] 2023-09-26 11:39
Duplicate of #7058

**Closed** 2023-10-13 11:44 UTC
Labels: enhancement
