### ISSUE TITLE
Athena Profiler Issue 

### ISSUE THREAD

**Issue by SagarManiar9** [open-metadata/OpenMetadata#13116] opened 2023-09-08 06:28 UTC
Affected module
backend

Describe the bug
Athena connector's Profiler ingestion failing and also it is keep in running state only.
The Main Error it shows is HIVE_BAD_DATA.
Here is schema for reference. 

<img width="1457" alt="Screenshot 2023-09-01 at 6 41 29 PM" src="https://github.com/open-metadata/OpenMetadata/assets/128776331/e42a30c2-8687-494b-99c3-94b3e9aa2b59">

also it is not showing sample data too , instead it shows error as below:
No data available.
To view Sample Data, run the Profiler Ingestion. Please refer to this doc to schedule the [Profiler Ingestion]

To Reproduce
Run profiler ingestion in athena connector.

Expected behavior
Proflier ingestion should run successfully. and dont get hive_bad_data error

Version:

OpenMetadata version: 1.1.1
Additional context

**Comment by TeddyCr** [comment] 2023-10-06 12:46
@SagarManiar9 can you share the error log from the profiler ingestion workflow. This will help us understand a bit better what is going on.

**Comment by pmbrull** [comment] 2023-11-02 12:10
Hi @SagarManiar9 looks like this error is related to your storage layer (the actual data files) based on this https://repost.aws/knowledge-center/athena-hive-bad-data-parsing-field-value

Closing this one as we cannot reproduce with "proper" data

**Closed by pmbrull** 2023-11-02 12:10 UTC
Labels: bug, profiler
