### ISSUE TITLE
Ingestion cannot start on Postgres. (2013, 'Lost connection to MySQL server during query') 

### ISSUE THREAD

**Issue by YuriyMaksym** [open-metadata/OpenMetadata#7602] opened 2022-09-20 15:15 UTC
**Affected module**
openmetadata-ingestion
**Describe the bug**
Hi, l'v started OpenMetadata on PostgresDb in  Docker and got the sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query') on openmetadata ingestion service.

**To Reproduce**

![image](https://user-images.githubusercontent.com/113980396/191218914-74387978-ca34-45ae-83cc-3439db3b48b8.png)

**Expected behavior**
ingestion service falls
**Version:**
metadata, version metadata 0.12.0.1 from C:\Users\Yuri\openmetadata-docker\env\lib (python 3.9)

**Additional context**

**Comment by ayush-shah** [comment] 2022-09-20 17:33
Fix for the above issue has been merged in https://github.com/open-metadata/OpenMetadata/pull/7600

**Closed by ayush-shah** 2022-09-20 17:33 UTC
Labels: docker, support, devops

**Comment by akash-jain-10** [comment] 2022-09-20 18:04
Hello, Providing the root cause and commit at 0.12.0 Branch - https://github.com/open-metadata/OpenMetadata/commit/cc4cc25d9724646bcba5bc78e3ec448551d4ae7e
This is the actual fix for the issue being faced.

The root cause is a misconfigured [environment variable ](https://github.com/open-metadata/OpenMetadata/blob/1790b4ebd7a208a21c223f8e9a9bb00cfabe631b/docker/metadata/docker-compose-postgres.yml#L145)configured (Image attached)!
We are not using the AIRFLOW_DB_SCHEME under [ingestion_dependency.sh](https://github.com/open-metadata/OpenMetadata/blob/1790b4ebd7a208a21c223f8e9a9bb00cfabe631b/ingestion/ingestion_dependency.sh#L18)
Instead, we are using DB_SCHEME which forms our SQL Alchemy connection string!

t had a wrong scheme being used and hence the MYSQL error on starting with postgres db :slightly_smiling_face:
This is fixed now in Release Branch as well as release bits are updated for Github Release 0.12.0!

We will be doing a minor Ingestion Python package  release which will enable usage of this fix with metadata docker CLI.
