### ISSUE TITLE
Handle the elastic search errors gracefully

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#385] opened 2021-09-02 20:56 UTC
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/38649/131914871-881e9c89-cba6-4814-897d-90fa642dfa35.png">
Instead of showing a pop up screen we should show helpful error messages without screen going blank.

**Comment by shahsank3t** [comment] 2021-09-03 05:07
Duplicate of #382

**Closed by shahsank3t** 2021-09-03 05:07 UTC
Labels: bug
