### ISSUE TITLE
Unable to expand lineage

### ISSUE THREAD

**Issue by aballiet** [open-metadata/OpenMetadata#18677] opened 2024-11-18 15:18 UTC
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

UI

**Describe the bug**

Cannot expand lineage as we could do before with "+" button.
Showing the bug in this loom: https://www.loom.com/share/05b13fd2e40c4dc69ddb19c8d2b1f4d9?sid=6be213bd-56cb-4c43-b73e-660cc3a9aea5

**To Reproduce**

You can directly go to Collate sandbox deployment

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by chillerno1** [comment] 2024-11-19 04:50
Yep, we've also noticed this issue after upgrading to 1.5.11. This is a major blocker for us upgrading until it's resolved.

**Comment by a-chumagin** [comment] 2024-11-26 08:28
it is duplicate of https://github.com/open-metadata/OpenMetadata/issues/18612

**Comment by TeddyCr** [comment] 2024-11-26 15:45
@a-chumagin @aballiet closing this as fixed in 1.5.12 😊

**Closed by TeddyCr** 2024-11-26 15:45 UTC
