### ISSUE TITLE
Athena connector fails to ingest `array` types

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#8127] opened 2022-10-13 06:47 UTC
**Affected module**
Ingestion Framework

**Describe the bug**
Athena tables with an `array` type are not appropriately ingested and sometimes fail.
- `array <string>` : wrong type
- `array<string>`: ingestion fail

**To Reproduce**
Try to ingest a created table with the following query:
```sql
CREATE EXTERNAL TABLE IF NOT EXISTS test_table(
  test_array_str array<string>
)
LOCATION 's3://bucket/'
```

**Expected behavior**
It must be ingested with the right type.

**Version:**
 - OpenMetadata version: 0.12.1

**Additional context**
We need to add an extra case when we call `_get_column_type` in the `Athena` connector. Also, parse the array type correctly when there is a space on it, e.g. `array <string>`.

It also fails with the `profiler`.

**Comment by flaviomax** [comment] 2022-10-19 21:21
I can confirm the error also happens for `struct` data types.
Also, this is a possible duplicate of Issue #8070

**Closed** 2022-11-02 06:06 UTC
Labels: bug, Ingestion
