### ISSUE TITLE
error while scanning redash dashboard with non ANSI symbols in parameters with next log

### ISSUE THREAD

**Issue by mitgard** [open-metadata/OpenMetadata#7763] opened 2022-09-27 19:36 UTC
**Affected module**
Ingestion frameworks

**Describe the bug**
While scanning redash dashboards with non ANSI symbols in url( in parameter). 
```
[2022-09-26, 12:00:03 UTC] {dashboard_service.py:284} WARNING - Cannot extract dashboard details from {'id': 563, 'slug': 'ab-1234-pr', 'name': 'AB-1234 Dashboard', 'user_id': 303, 'user': {'id': 303, 'name': 'Name', 'email': 'name@abcd.net', 'profile_image_url': 'https://www.gravatar.com/avatar/15c155412eaa0610b97aab6a43384bfa?s=40&d=identicon'}, 'layout': [], 'dashboard_filters_enabled': False, 'widgets': None, 'options': {}, 'is_archived': False, 'is_draft': False, 'tags': [], 'updated_at': '2022-09-20T13:13:46.744+03:00', 'created_at': '2022-09-20T12:07:32.105+03:00', 'version': 2, 'is_favorite': False}: 500 Server Error: INTERNAL SERVER ERROR for url: https://redash.internal.tech/api/dashboards/ab-1234-pr
```
But I guess, and addition another problen. For dashboard from log, correct url is  `https://redash.internal.tech/api/dashboards/563-ab-1234-pr` i.e. id plus dashboard name. 
But pipeline finished successfully. 

**Version:**
 - OS: ubuntu 20.04
 - Python version: 
 - OpenMetadata version: 0.12.0(run with docker compose and postgres)
 - Redash version: 11.0.0-dev

**Comment by konnectr** [comment] 2022-10-11 08:08
I can request get query from only ID dashboards. Slug all response errors

**Comment by OnkarVO7** [comment] 2022-11-15 10:27
Hi @mitgard we tried to ingest dashboards with names similar to `'name': 'AB-1234 Dashboard'` and other names with non-ANSI symbols, we are successfully able to ingest that and not able to reproduce the issue.

Is is possible for you to give us some more details on exactly what is the name/url of your dashboard in redash that is giving the issue?

Also in the issue above you have mentioned your redash version to be `11.0.0-dev`. However the latest stable version according to redash [docs](https://version.redash.io/) is `8.0.0` Can you also try with that and let us know.

**Comment by pmbrull** [comment] 2022-11-23 09:46
@OnkarVO7 we can try to replicate with the exact same name `'Молоко. ВСД'`. Worst case scenario, let's set the dashboard ID as the name and use the `name` as the displayName

**Comment by OnkarVO7** [comment] 2022-11-23 09:52
Yes @pmbrull will try with that

**Comment by pmbrull** [comment] 2022-12-01 10:53
hi @mitgard we might need some more details here. We were actually not able to reproduce the issue 

![image](https://user-images.githubusercontent.com/35870520/205034648-2d082a8f-34c3-4954-b5d2-1ab580ee0e3f.png)

**Comment by pmbrull** [comment] 2022-12-01 10:57
hi @mitgard, actually I believe that the issue is on your Redash instance and not related to the Ingestion Framework of OpenMetadata.

The error you are seeing `Cannot extract dashboard details from` is raised when we cannot extract the dashboard details from the Redash API. I got confused here and I thought that we have some issues with the alphabet in the name, but that is proved to be fine.

The issue is that your dashboard has the slug `-`. You can see this from your logs `'slug': '-'`. This is the data that is received from Redash directly. As the ingestion won't be stopping for these scenarios and the issue is not on the OpenMetadata side, we'll be closing this.

Thanks

**Closed by pmbrull** 2022-12-01 10:57 UTC
Labels: bug, Ingestion, support
