### ISSUE TITLE
UI is taking around 50% of build time 

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#1660] opened 2021-12-10 04:54 UTC
<img width="673" alt="image" src="https://user-images.githubusercontent.com/38649/145519387-7662c1f9-02fa-4104-96af-8b377c1ccbfb.png">
can we improve this
cc @shahsank3t

**Comment by shahsank3t** [comment] 2022-06-22 04:37
This is a duplicate of https://github.com/open-metadata/OpenMetadata/issues/5538 so closing this one.

**Closed by shahsank3t** 2022-06-22 04:37 UTC
Labels: P2
