### ISSUE TITLE
Release 1.1 - UI Feedback for Tasks functionality

### ISSUE THREAD

**Issue by sureshms** [open-metadata/OpenMetadata#11212] opened 2023-04-22 18:32 UTC
- [x] Change the breadcrumb to the standard one. Along with the display name, we can add a / and Create Task
- [ ] While creating the task, we don't need the right panel 
<img width="189" alt="image" src="https://user-images.githubusercontent.com/1417689/233800985-dad40ea1-a470-4c0c-bee7-6dd3e4618dc1.png">

- [x] After creating a task, we should go back to the dataset details page instead of showing a task?

- [x] When showing a task, use the standard breadcrumb 
<img width="615" alt="image" src="https://user-images.githubusercontent.com/1417689/233801044-6f65095b-6edf-463b-9d7b-68845f12a5ab.png">

- [x] Tasks layout needs to be reworked. Not sure why Description should be a separate card. 
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/1417689/233801065-62191d37-5583-46ad-a784-b60b13cf1c83.png">

- [x] Accepting a suggestion for a description does not update the description of the table.

**Comment by sureshms** [comment] 2023-04-22 21:58
- [ ] Tasks should have drop-down menu worded as "All" and not "All Activity" 
<img width="382" alt="image" src="https://user-images.githubusercontent.com/1417689/233808179-4dd6bcc5-3fc0-4e7d-be4e-49a842f5a21b.png">

- [ ] Task filter "Assigned To Me" does not show the task assigned to me.

**Comment by harshach** [comment] 2023-04-23 00:30
@sureshms 
" If a table has an owner, creating a task by default should choose the owner instead of showing it as blank. Task creator can change the assignee if he wants."
This part works in our Current Task opening flow
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/38649/233813026-4385ef18-bad4-45d7-a696-0da11ea9db05.png">

**Comment by harshach** [comment] 2023-04-23 19:38
- [ ] Assignee drop-down should be the same component as assigning the owner. But allow multi-selection as there can be multiple assignees.
<img width="893" alt="image" src="https://user-images.githubusercontent.com/38649/233861230-57dae19f-2cae-4e28-87ed-5a655a0c417c.png">

**Comment by harshach** [comment] 2023-04-26 19:27
- [ ] we should have preivous styling. Applying this across the site especially in charts doesn't make sense. @chirag-madlani lets make sure we get this into in-place relase
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/38649/234682052-30679821-687e-430e-a1cf-296d268eff91.png">

**Comment by harshach** [comment] 2023-04-27 15:56
- [ ] Request Description doesn't assign the owner as the assignee by default.  **1.0.1**
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/38649/234918449-8188c457-234a-47b9-899d-a5e60c58975d.png">

**Comment by harshach** [comment] 2023-04-27 17:53
- [ ] Accepting the suggested description doesn't add that to the column ** Regression ** ** Release 1.0.1 **

https://user-images.githubusercontent.com/38649/234950755-549a75f2-e22a-4016-9b00-9835c75c867a.mov

**Comment by chirag-madlani** [comment] 2023-05-25 06:38
@harshach will be holding this for new mocks right?

**Comment by harshach** [comment] 2023-05-25 06:50
@chirag-madlani yes

**Comment by chirag-madlani** [comment] 2023-06-24 07:11
Majority of the feedback have been taken care, Since we upgrade UI many feedback are not valid hence closing it

**Closed** 2023-06-24 07:11 UTC
Labels: UI
