### ISSUE TITLE
Link to share advanced search results

### ISSUE THREAD

**Issue by gnomolio** [open-metadata/OpenMetadata#11484] opened 2023-05-08 13:03 UTC
**Is your feature request related to a problem? Please describe.**
I applied advanced search in UI and want to send a link on found objects to my colleagues. 
I copied URL, but if my colleague will open link, advanced search will not be applied.

**Describe the solution you'd like**
Opportunity to share advanced search results with links. 

**Describe alternatives you've considered**
No alternatives 

**Additional context**
This is an important issue when it comes to communication about sets of data entities. For example, I want data owner to renew descriptions of his tier1 data assets, but instead of sharing link I have to instruct him, how to find assets with advanced search.

**Comment by karanh37** [comment] 2023-05-09 06:25
@gnomolio - which version of OMD are you using ?
I tried in 1.0 and it seems to be working fine for me.
Also if you can provide more information on how to reproduce it or maybe a video will be great.

**Comment by chirag-madlani** [comment] 2023-05-10 10:16
@gnomolio Closing this hence unable to replicate with our latest release. Feel free to re-open or reach out if you face the same

**Closed by chirag-madlani** 2023-05-10 10:16 UTC
Labels: enhancement, UI
