### ISSUE TITLE
PostgreSQL table and schema asset link is missing from the announcement header

### ISSUE THREAD

**Issue by hejatibor** [open-metadata/OpenMetadata#14061] opened 2023-11-21 18:09 UTC
**Affected module**
UI

**Describe the bug**
In the announcement header the asset link is missing. The asset is a PostgreSQL table or schema.

**To Reproduce**
1. Select an asset with the menitioned type
2. create an announcement for that asset, save
3. check the appearing announcement header ("USER posted on table "

Screenshots or steps to reproduce
![image](https://github.com/open-metadata/OpenMetadata/assets/6572345/33ad4a8b-2e20-4ea9-8d1e-30708cb969a4)

**Expected behavior**
A link should be in the header, with the asset name or description

**Version:**
 - OS: docker
 - Python version: docker
 - OpenMetadata version: 1.2.0
 - OpenMetadata Ingestion package version: ?

**Additional context**

**Comment by Ashish8689** [comment] 2023-11-23 07:18
@hejatibor I am not able to reproduce the issue on Postgres or any other service. On [Sandbox](https://sandbox.open-metadata.org/my-data) it's working fine. can you help me with more details and api response for the same so we can track the exact issue here. 
<img width="396" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/a0fa7a67-5c9b-4666-bda8-1a91b831c2f8">

**Comment by hejatibor** [comment] 2023-11-23 11:52
I found other strange behavior which lead me to that idea, maybe the non-ascii characters in the database service name causes this problem.
![image](https://github.com/open-metadata/OpenMetadata/assets/6572345/46c9aaa0-4392-44e4-b525-3ebb5fac7493)
At the task view:
![image](https://github.com/open-metadata/OpenMetadata/assets/6572345/79c8f3bb-13c3-40d6-af2f-06edf7a146be)
Now I can't delete and recreate with ascii-name the db service, on next Monday I can do that.

**Comment by Ashish8689** [comment] 2023-11-24 06:02
@hejatibor This was the issue previously and we have fixed it in the `1.2.1` release with this [PR](https://github.com/open-metadata/OpenMetadata/pull/13826). Please update your OM to the latest version.

Closing this issue for now. Let us know if this issue still persists by re-opening the same issue with more details.

**Closed by Ashish8689** 2023-11-24 06:02 UTC
Labels: UI
