### ISSUE TITLE
Add Documentation for SAML setup

### ISSUE THREAD

**Issue by mohityadav766** [open-metadata/OpenMetadata#10758] opened 2023-03-24 16:28 UTC
**Is some content missing, wrong or not clear?**
A clear and concise description of what the problem is and the source URL. Ex. Page [...] is not clear.

**Describe the solution you'd like**
Let us know what could help us improve the docs.

**Additional context**

**Comment by pmbrull** [comment] 2024-02-08 07:14
duplicate of #11445

**Closed by pmbrull** 2024-02-08 07:14 UTC
Labels: documentation
