### ISSUE TITLE
Enhancement request to support for microservices / web services within the catalogue

### ISSUE THREAD

**Issue by aormerod-gs** [open-metadata/OpenMetadata#8108] opened 2022-10-12 10:46 UTC
Currently there is support for services like: Database, Dashboard, etc. (https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/entity/services/serviceType.json) and their data lineage / dependencies can be documented.

This enhancement request is for there to be an ability to create a service to represent an application web service and the data dependencies that it has.  (Suggested name from brief discussion in Slack was: Microservice).

To start discussion on modelling / information required: 
* A microservice should contain the base URL of the service (i.e. web protocol, host name, port, base path)
* For a given endpoint / path within the service, we'd like to be able to capture 1) the schema of the result from the service 2) the linage to the source datasets it depends on
* The lineage of different URI sub-paths may be different (e.g. I might have a two completely separate APIs on the same web service, and each of them depends on separate datasets to source the relevant results)
* Other services (e.g. pipelines) should be able to express lineage dependencies to a microservice

Is this something that aligns with the thinking / direction of services?

Thanks,

**Comment by harshach** [comment] 2024-06-22 21:31
duplicate of this https://github.com/open-metadata/OpenMetadata/issues/10933

**Closed by harshach** 2024-06-22 21:31 UTC
