### ISSUE TITLE
Data product list error

### ISSUE THREAD

**Issue by karanh37** [open-metadata/OpenMetadata#13153] opened 2023-09-12 13:11 UTC
**Describe the bug**
When fetching Data Products using GET API, it doesn't take into consideration value passed in `domain` field.
The API results all the data products, instead it should only provide data products for that domain

**Comment by sureshms** [comment] 2023-09-13 00:28
@karanh37 , let's use Elastic Search API for getting data products by domain instead of list APIs. CC @harshach

**Comment by sureshms** [comment] 2023-09-27 19:07
Duplicate of #13255

**Closed by sureshms** 2023-09-27 19:07 UTC
Labels: backend
