### ISSUE TITLE
UI : Homepage incorrect total services count

### ISSUE THREAD

**Issue by dvecerdea** [open-metadata/OpenMetadata#3701] opened 2022-03-28 12:35 UTC
**Affected module**
UI

**Describe the bug**
In homepage, total service count is capped to 10 for Database Services (maximum per page). When clicking on Service Page, however, the correct total count is displayed

home page:
![image](https://user-images.githubusercontent.com/92868540/160394617-9b0dec86-0364-46bf-a067-8ad78ea22738.png)
services page:
![image](https://user-images.githubusercontent.com/92868540/160394766-8abfabf2-321b-497b-b64b-a6c9717b81c6.png)

**To reproduce**
Ingest more than 10 database services

**Expected behavior**
From homepage, the correct number of total of services (28 in this case) should be displayed

**Version:**
 - OpenMetadata version: 0.9.0

**Additional context**
Problem seems to occur for each service type with more than 10 services.
The total service count uses the length of the response from this request: https://github.com/open-metadata/OpenMetadata/blob/144e0b3cf31fcf5c7b6876452950b32fce0bc0ea/openmetadata-ui/src/main/resources/ui/src/axiosAPIs/serviceAPI.ts#L26, which is paginated. instead of response.data.length, response.paging.total can be used

**Comment by darth-coder00** [comment] 2022-03-29 05:20
Duplicate of #3596 
Resolved in #3646 

@dvecerdea Thanks for reporting this

**Closed by darth-coder00** 2022-03-29 05:20 UTC
Labels: bug, UI
