### ISSUE TITLE
Handling TableConstraints - UI

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#2887] opened 2022-02-21 04:51 UTC
Ingestion is now providing TableConstraints as there are cases where a table can have multiple primary keys. 
UI to be added inorder to distinguish Table Constraints.

**Comment by Sachin-chaurasiya** [comment] 2022-05-25 06:00
Duplicate of #5129

**Closed by Sachin-chaurasiya** 2022-05-25 06:00 UTC
Labels: P0, UI
