### ISSUE TITLE
The usage percentile is not getting updated after successful usage workflow.

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#11085] opened 2023-04-17 10:18 UTC
**Affected module**
UI

**Describe the bug**
The usage percentile is not getting updated after usage workflow.

Screenshots or steps to reproduce
<img width="764" alt="image" src="https://user-images.githubusercontent.com/110607559/232455663-a265056b-9567-4e93-9b45-00b14351b210.png">

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/110607559/232455963-5d740a46-7d63-44de-ad6e-7445f7b9bb1f.png">
[redshiftusageusagetask-46f0f310f01f.txt](https://github.com/open-metadata/OpenMetadata/files/11248901/redshiftusageusagetask-46f0f310f01f.txt)

usage logs are attached.

**Version:**
13.2.8

**Comment by ayush-shah** [comment] 2023-05-02 13:56
Hello @lailapatel the usage is working as expected..Tried with real time data.
The reasons for the usage pctile not showing up, maybe the weekly usage count came in as 0 or else it's has the lowest count compared to all other tables computed that day.

and the reason for count coming in as 0 maybe, no query was parsed due to no usage / some error.
Can you add debug logs so that we can debug it better?

but to close this thread, it's not an issue with percentile, but maybe parsing of queries.

**Comment by ayush-shah** [comment] 2023-05-03 09:38
Closing this thread as the issue is not with the usage percentile. Will reopen if reproduced by the users, with the debug logs available and if the cause is distinguished to be of percentile.

**Closed** 2023-05-03 09:39 UTC
Labels: bug, Ingestion, support
