### ISSUE TITLE
Ingestion Pipeline Deployment takes several minutes

### ISSUE THREAD

**Issue by cdoron** [open-metadata/OpenMetadata#7512] opened 2022-09-16 09:52 UTC
I deploy OpenMetadata through the `openmetadata-dependencies` and `openmetadata` helm charts.
After moving from OM 0.11.4 to 0.12.0, it takes several minutes (~5 minutes) from the moment I deploy an ingestion pipeline until I can run it.
Here is the `openmetadata_airflow_api.log` from the `openmetadata-dependencies-web` pod:
```
[2022-09-16 05:35:44,680] INFO     {AirflowOperations:deploy:56} - Received the following Airflow Configuration: pausePipeline=False concurrency=1 startDate=None endDate=None pipelineTimezone='UTC' retries=3 retryDelay=300 pipelineCatchup=False scheduleInterval=None maxActiveRuns=1 workflowTimeout=None workflowDefaultView='tree' workflowDefaultViewOrientation='LR' email=None
[2022-09-16 05:35:44,680] INFO     {AirflowOperations:deploy:56} - Received the following Airflow Configuration: pausePipeline=False concurrency=1 startDate=None endDate=None pipelineTimezone='UTC' retries=3 retryDelay=300 pipelineCatchup=False scheduleInterval=None maxActiveRuns=1 workflowTimeout=None workflowDefaultView='tree' workflowDefaultViewOrientation='LR' email=None
[2022-09-16 05:35:44,681] INFO     {AirflowOperations:deploy:152} - Config file under /opt/airflow/dags/qqq_metadata_5reKHTmZ.json
[2022-09-16 05:35:44,681] INFO     {AirflowOperations:deploy:152} - Config file under /opt/airflow/dags/qqq_metadata_5reKHTmZ.json
[2022-09-16 05:35:44,681] INFO     {AirflowOperations:deploy:71} - Saving file to /opt/airflow/dags/qqq_metadata_5reKHTmZ.json
[2022-09-16 05:35:44,681] INFO     {AirflowOperations:deploy:71} - Saving file to /opt/airflow/dags/qqq_metadata_5reKHTmZ.json
[2022-09-16 05:35:45,082] INFO     {AirflowWorkflow:workflow_factory:79} - Registered the dag: qqq_metadata_5reKHTmZ
[2022-09-16 05:35:45,082] INFO     {AirflowWorkflow:workflow_factory:79} - Registered the dag: qqq_metadata_5reKHTmZ
[2022-09-16 05:35:45,088] INFO     {AirflowOperations:deploy:123} - dagbag size 1
[2022-09-16 05:35:45,088] INFO     {AirflowOperations:deploy:123} - dagbag size 1
[2022-09-16 05:35:45,162] INFO     {AirflowWorkflow:workflow_factory:79} - Registered the dag: qqq_metadata_5reKHTmZ
[2022-09-16 05:35:45,162] INFO     {AirflowWorkflow:workflow_factory:79} - Registered the dag: qqq_metadata_5reKHTmZ
[2022-09-16 05:35:45,163] INFO     {AirflowOperations:deploy:125} - processed dags [<DAG: qqq_metadata_5reKHTmZ>, <DAG: qqq_metadata_5reKHTmZ>]
[2022-09-16 05:35:45,163] INFO     {AirflowOperations:deploy:125} - processed dags [<DAG: qqq_metadata_5reKHTmZ>, <DAG: qqq_metadata_5reKHTmZ>]
[2022-09-16 05:35:45,209] INFO     {AirflowOperations:deploy:134} - dag_model:<DAG: qqq_metadata_5reKHTmZ>
[2022-09-16 05:35:45,209] INFO     {AirflowOperations:deploy:134} - dag_model:<DAG: qqq_metadata_5reKHTmZ>
[2022-09-16 05:39:44,783] INFO     {AirflowWorkflow:workflow_factory:79} - Registered the dag: qqq_metadata_5reKHTmZ
[2022-09-16 05:39:44,783] INFO     {AirflowWorkflow:workflow_factory:79} - Registered the dag: qqq_metadata_5reKHTmZ
```

Note the 4-minute gap between `05:35:45` and `05:39:44`.
In the interval between `05:35:45` and `05:39:44`  the Airflow UI does not display the `qqq_metadata_5reKHTmZ` dag, and the corresponding ingestion pipeline cannot be run.

@harshach and @pmbrull suggested a **temporary** workaround: setting the `AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL` variable to 5 seconds (the default is 300 seconds).
https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#dag-dir-list-interval

As a result, deployment takes seconds rather than minutes.
I hope you can fix the problem and make deployment instantaneous, as it was before.

Thanks!

**Comment by harshach** [comment] 2022-11-28 05:04
Unable to reproduce closing this out

**Closed by harshach** 2022-11-28 05:04 UTC
Labels: bug, Ingestion, support
