### ISSUE TITLE
Loading screen is displayed while editing and deleting ingestion

### ISSUE THREAD

**Issue by kshinde2512** [open-metadata/OpenMetadata#3271] opened 2022-03-08 13:56 UTC
**Affected module**
UI, backend

**Describe the bug**
Upon editing and deleting ingestion loading screen is displayed

**To Reproduce**

1. Navigate to ingestion tab in service page
2. Create an ingestion 
3. Click on edit ingestion
4. Click on Next and Deploy
5. Loading screen is displayed
6. Same issue exists while deleting the ingestion

https://user-images.githubusercontent.com/67048554/157251845-ed402f85-7808-4b9d-b464-c4aed63fabdd.mp4

**Expected behavior**

**Version:**
 - OpenMetadata version: 0.9.0

**Additional context**
NA

**Comment by ayush-shah** [comment] 2022-03-16 07:41
Not able to reproduce - Fixed. Closing this issue.

**Closed by ayush-shah** 2022-03-16 07:41 UTC
Labels: P1, UI, Ingestion
