### ISSUE TITLE
Adding tags to glossary term does not propagate to linked assets

### ISSUE THREAD

**Issue by jvanelteren** [open-metadata/OpenMetadata#11930] opened 2023-06-08 10:12 UTC
**Affected module**
Backend I think

**Describe the bug**
When adding an asset to a glossary term, all the tags from the glossary term are propagated. 
However:
When adding a tag to the glossary term, the tag does not propagate to linked assets

This behaviour is inconsistent. Either propagate tags to linked assets or don't. 
As an aside, for us the propagation of additional tags to a glossary term to the linked assets is not always helpful. We use the glossary for administration of data products. Certain tags can be relevant only for the data product (glossary term) but not for the table. 

**To Reproduce**
- Make a glossary and glossary term
- Add a tag to the glossary term
- Add an asset --> the existing tags propagate to the linked asset
- Add a tag to the glossary term --> the added tag does not propagate to the linked assets

**Expected behavior**
Either propagate additional tags or not. Or give the user a choice.

**Version:**
 - OS: Windows 10
 - Python version: Don't know
 - OpenMetadata version: 1.0

**Comment by fstuijt** [comment] 2023-06-12 11:30
A bit of context first: at this moment, I'm are planning to use the glossary as a catalog for data products. A data product may consist of one or more assets. The other way round: an asset may belong to zero or more data products. 

In this situation, if I want to specify e.g. a confidentiality tag on a data product (and thus on a glossary item), this tag  should not automatically apply to all related assets. 

It is just one of these situations that may ask for making this propagation an optional feature, so please do consider this (or give me some advice on an alternative how to combine assets into data products ;-) )

**Comment by harshach** [comment] 2023-11-30 19:19
@fstuijt we shipped data products as part of our domains and data products. Please take a look with the latest release

**Comment by sureshms** [comment] 2023-11-30 19:28
> This behaviour is inconsistent. Either propagate tags to linked assets or don't.
As an aside, for us the propagation of additional tags to a glossary term to the linked assets is not always helpful. We use the glossary for administration of data products. Certain tags can be relevant only for the data product (glossary term) but not for the table.

@jvanelteren, I am not sure what the expectation is. First line says either propagate tags or don't. The next statement says propagation is not always helpful.

The way the feature works is if there are tags at the time of adding a glossary term as a label, those tags are propagated.

**Comment by sureshms** [comment] 2023-11-30 19:30
Marking this as a duplicate of #13094

**Closed by sureshms** 2023-11-30 19:30 UTC
