### ISSUE TITLE
(psycopg2.errors.UndefinedColumn) column "relispartition" does not exist

### ISSUE THREAD

**Issue by oliverzgy** [open-metadata/OpenMetadata#9983] opened 2023-01-29 02:10 UTC
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: 0.13.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
Postgresql Server 9.6 

[2023-01-29 01:00:33,426] {common_db_source.py:242} WARNING - Fetching tables names failed for schema information_schema due to - (psycopg2.errors.UndefinedColumn) column "relispartition" does not exist
LINE 5: ...formation_schema' AND c.relkind in ('r', 'p') AND relisparti...
                                                             ^
[SQL: /* {"app": "OpenMetadata", "version": "0.13.1.8"} */
    SELECT c.relname FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = %(schema)s AND c.relkind in ('r', 'p') AND relispartition = false
]
[parameters: {'schema': 'information_schema'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2023-01-29 01:00:33,575] {common_db_source.py:242} WARNING - Fetching tables names failed for schema public due to - (psycopg2.errors.UndefinedColumn) column "relispartition" does not exist
LINE 5: ...spname = 'public' AND c.relkind in ('r', 'p') AND relisparti...
                                                             ^
[SQL: /* {"app": "OpenMetadata", "version": "0.13.1.8"} */
    SELECT c.relname FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = %(schema)s AND c.relkind in ('r', 'p') AND relispartition = false
]
[parameters: {'schema': 'public'}]

**Comment by pmbrull** [comment] 2023-01-31 09:15
hi @oliverzgy please double check your postgres version. We only support from 11 onwards (based on the official postgres support https://www.postgresql.org/support/versioning/).

I believe this issue is caused by a version older than that. @ayush-shah please let's add this to the docs as well.

**Comment by oliverzgy** [comment] 2023-01-31 10:04
> hi @oliverzgy please double check your postgres version. We only support from 11 onwards (based on the official postgres support https://www.postgresql.org/support/versioning/).
> 
> I believe this issue is caused by a version older than that. @ayush-shah please let's add this to the docs as well.

Yes, you're right, my postgres version is 9.6. Thanks for pionting this out, @pmbrull

**Comment by pmbrull** [comment] 2023-01-31 10:21
Thanks for confirming. We'll address this clearly in the docs to avoid further confusion. Closing this out.

**Closed by pmbrull** 2023-01-31 10:21 UTC
Labels: documentation, Ingestion
