### ISSUE TITLE
Table columns should be represented everywhere by "DisplayName", not "name"

### ISSUE THREAD

**Issue by AlekseevVadim** [open-metadata/OpenMetadata#14068] opened 2023-11-22 10:09 UTC
**Affected module**
UI

**Describe the bug**
On the tables page, in the "Profile & Data Quality" tab in the "Column Profiler" section, "name", and not "DisplayName" are given in the table with the profile as the name for the columns. It would be more convenient if "DisplayName" were specified as the name, as well as on the "Schema" tab.
![naming_problem](https://github.com/open-metadata/OpenMetadata/assets/61934044/e14848cf-cf4a-477e-b50f-82ccef7cf559)

Also, the search bar for the filter of the desired column searches by "name", not "DisplayName". Since the display name is "DisplayName", then the search must be performed on it.
This is true for the search bar on the "Schema" tab, but taking into account the correction of the problem described above, this will also be true for the line in the "Column Profiler" section on the "Profiler & Data Quality" tab.
![naming_filter_problem](https://github.com/open-metadata/OpenMetadata/assets/61934044/311f37d2-ced4-4c31-aa04-f0e70e2831d5)

**Version:**
 - OpenMetadata version: 1.1.7

**Comment by ShaileshParmar11** [comment] 2024-01-18 12:59
the issue is already fixed in PR #14542

**Closed by ShaileshParmar11** 2024-01-18 12:59 UTC
Labels: UI
