### ISSUE TITLE
My Data or Following sections in homepage should only display a maximum of 8 entities

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#6164] opened 2022-07-18 18:25 UTC
**Affected module**
UI

**Describe the bug**
When a user owns a lot of entities, the My Data section displays almost 30 entities on the homepage.

**To Reproduce**
Make a user owner for a lot of entities and visit the homepage

**Expected behavior**
Only 8-10 entities are displayed

**Comment by ShaileshParmar11** [comment] 2022-07-19 07:25
Hey @vivekratnavel it seems like this is an issue from the backend,
API call -> `http://localhost:3000/api/v1/search/query?q=* AND (owner.id:b3919e58-1102-4dcc-8d36-751f402a5884)&from=0&size=8&index=dashboard_search_index,table_search_index,topic_search_index,pipeline_search_index,mlmodel_search_index`

but from backend we are getting all the data

**Comment by vivekratnavel** [comment] 2022-07-19 07:27
cc @harshach

**Comment by ShaileshParmar11** [comment] 2022-07-29 05:43
Duplicate of https://github.com/open-metadata/OpenMetadata/issues/4391

**Closed by ShaileshParmar11** 2022-07-29 05:43 UTC
Labels: UI, backend
