### ISSUE TITLE
support for custom endpoints of blob storage systems

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#7841] opened 2022-10-01 09:29 UTC
Support `endpoint_url` parameter for custom S3-like blob storage systems.

https://openmetadata.slack.com/archives/C02B6955S4S/p1664612492333519

**Comment by pmbrull** [comment] 2022-11-23 14:15
```
https://docs.open-metadata.org/openmetadata/connectors/database/datalake/cli does not show a URL for a custom S3 like minio. How can a custom URL like localhost be specified for a minio instance when connecting OM to that S3 (mock)?
```

**Comment by pmbrull** [comment] 2022-12-09 07:37
closing as a dupe of https://github.com/open-metadata/OpenMetadata/issues/9217

**Closed by pmbrull** 2022-12-09 07:37 UTC
Labels: duplicate, Ingestion, support
