### ISSUE TITLE
MSSQL Profiler fails to PUT sample data because utf-8 codec isn't able to serialize unicode to JSON

### ISSUE THREAD

**Issue by pinkerltm** [open-metadata/OpenMetadata#12966] opened 2023-08-22 19:29 UTC
**Affected module**
Ingestion Framework

**Describe the bug**
A profiler ingestion writes a lot of WARNINGs (see "reproduce") into the log (basically for every table) of a MSSQL Database Connection. The job returns then with "Partially Success". Although it was configured to load 100 Sample Data Records for each table, no sample data is loaded. Other Profiler metrics (sum, mean, etc..) work as expected

**To Reproduce**

![grafik](https://github.com/open-metadata/OpenMetadata/assets/6107708/f8f5112d-c4c5-41ad-8a2d-37dedd963f1e)
 
 The log says 
_{table_mixin.py:74} WARNING - Error trying to PUT sample data for xxxxx.yyyy.zzz: 'utf-8' codec can't decode byte 0x94 in position 10: invalid start byte_

...with different bytes for every table. The trace _'table_mixin.py'_ basically points to the API call which tries to serialize the collected sample data into a JSON and PUT it to the Table.

So my guess is, that the sample data contains UNICODE (UTF-16? - as every SQL Server contains only that) and the serializer uses an utf-8 codec which fails then.

**Expected behavior**
At least the codec should fallback to 'latin-1' and the already collected sample data can be put to the table profile accordingly.

**Version:**
 - OpenMetadata version: [e.g. 1.1.1 - official Docker Images]

**Additional context**
SQL Server Build Version is 15.0.2101 (SQL Server 2019)

**Comment by ayush-shah** [comment] 2023-09-13 10:02
similar error found in bigquery:

[2023-09-13, 15:29:07 IST] {table_mixin.py:74} WARNING - Error trying to PUT sample data for xxx.xxx.xxxx.bytes_tables: 'utf-8' codec can't decode byte 0x9e in position 1: invalid start byte
[2023-09-13, 15:29:07 IST] {status.py:57} WARNING - Error trying to ingest sample data for table

**Comment by ayush-shah** [comment] 2023-09-25 06:16
@pinkerltm can you share the debug logs and schema of the table as well where it's failing

**Comment by ayush-shah** [comment] 2023-09-27 09:47
Closing this issue as no reply from @pinkerltm and we cannot reproduce it. will reopen if there is any comment

**Closed by ayush-shah** 2023-09-27 09:47 UTC
Labels: bug, profiler
