### ISSUE TITLE
Improve error message InvalidServiceConnectionException for service [BigQuery] due to [Failed to encrypt connection instance of BigQuery].

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#13849] opened 2023-11-04 12:29 UTC
**Affected module**
Backend

**Describe the bug**
Whenever the user changes JWT Tokens or for some other reason, the server fails with a mysterious error like
InvalidServiceConnectionException for service [BigQuery] due to [Failed to encrypt connection instance of BigQuery].
This doesn't give much detail on why it's failing 
1. In some cases the ingestion bot token is expired @pmbrull 
2. In other cases backend can throw this error during the server start @mohityadav766 

This adds unnecessary load to the support channel.

**Comment by pmbrull** [comment] 2023-11-13 05:55
I could only reproduce this by changing the Fernet key, which not sure how typical of an operation that is, and I assume it would have other side effects.

Updating the JWT certs and IDs does not trigger this. Updating the db directly by "breaking" the shape of the connector also does not trigger this.

@mohityadav766 I could use some help on finding which is the root cause we need to improve here to send the right message

**Comment by pmbrull** [comment] 2023-11-29 09:59
fixed by https://github.com/open-metadata/OpenMetadata/commit/27fa5b34bb873d3e9b309c7fd80363827b798ab8

**Closed** 2023-12-18 05:43 UTC
