### ISSUE TITLE
UI: Markdown text editor is broken

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#3202] opened 2022-03-07 07:50 UTC
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI: Markdown text editor

**Describe the bug**
The write mode and preview mode is showing the same raw format of text instead of rendering the markdown

**To Reproduce**
Try to enter a new line by pressing Shift+Return or try to add a bold text

**Expected behavior**
Markdown is rendered in preview mode

<img width="999" alt="Screen Shot 2022-03-06 at 11 48 00 PM" src="https://user-images.githubusercontent.com/1051198/156989632-e27c5d76-ad25-4d5f-8bd6-359eaebd6c03.png">

**Comment by Sachin-chaurasiya** [comment] 2022-03-07 08:24
Duplicate of #3163.

**Comment by harshach** [comment] 2022-03-08 22:02
@Sachin-chaurasiya please take a look ^

**Closed** 2022-04-07 11:50 UTC
Labels: bug, P1, UI
