### ISSUE TITLE
Button "Next"is not work (setting -> team -> asset)

### ISSUE THREAD

**Issue by Alexandr-Nedomets** [open-metadata/OpenMetadata#15675] opened 2024-03-22 15:28 UTC
**Affected module**
Does it impact the UI

**Describe the bug**
Button "Next"is not work (setting -> team -> asset)
direct link http://{host}/settings/members/teams/TeamAssert?activeTab=assets
There is no team in the sandbox with a lot of assets

**To Reproduce**
![image](https://github.com/open-metadata/OpenMetadata/assets/55582159/3d81e0c8-d38d-4d4a-a047-2604e34fbb29)

**suspected cause of error**

![image](https://github.com/open-metadata/OpenMetadata/assets/55582159/54199a88-ed34-486e-8cdb-e8b7d4cb9d66)

**Expected behavior**
Button "Next"is work (setting -> team -> asset)

**Version:**
 - Python version:
 - OpenMetadata version: [1.2.5 or more]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by Alexandr-Nedomets** [comment] 2024-03-22 15:29
I'm ready to do this issue
if all ok, assign to me

**Comment by TeddyCr** [comment] 2024-03-22 16:33
@Alexandr-Nedomets can you upgrade to the latest version. I am unable to reproduce it in the latest stable version. https://sandbox.open-metadata.org/settings/members/teams/Accounting?activeTab=assets

**Comment by TeddyCr** [comment] 2024-03-22 16:34
Closing for now. Feel free to reopen if it still occurs in the latest with any error logs you can see from the browser

**Closed by TeddyCr** 2024-03-22 16:34 UTC
