### ISSUE TITLE
Rule creation fails while filling out form

### ISSUE THREAD

**Issue by jvanelteren** [open-metadata/OpenMetadata#11520] opened 2023-05-10 09:00 UTC
**Affected module**
UI

**Describe the bug**
After clicking 'Add rule' a form appears. When typing in the 'rule name' field, the pages suddenly changes into an error.
Something went wrong
Cannot read properties of null (reading 'value')

**To Reproduce**
Click add rule and start typing in the rule name.

**Expected behavior**
No error page

**Version:**
 - OpenMetadata version: [e.g. 1.0]
 - Browser: Problem manifests at least for Chrome and edge
 - 

**Additional context**
I looked at the developer console:
![Screenshot 2023-05-10 105745](https://github.com/open-metadata/OpenMetadata/assets/24619938/c0daadc1-c7ac-494e-a2cf-111a93556599)
![Screenshot 2023-05-10 105814](https://github.com/open-metadata/OpenMetadata/assets/24619938/84b09f5d-2fa9-48f3-876b-574a7692427b)

**Comment by sureshms** [comment] 2023-05-11 03:57
> After clicking 'Add rule' a form appears. 
Can you describe steps before this?

**Comment by jvanelteren** [comment] 2023-05-11 08:19
Hi Suresh, sure:
- login with keycloack
- click on teams (menu left side)
- click on policies
- select 'organization policy'
- click on 'add rule'
- when typing in the 'rule name' field, at some point the error occurs. Can be with the first character already, or after some seconds. But always after a keystroke (so doing nothing doen't trigger the error). And it occurs only on the rule name field.

Let me know if I can troubleshoot further

**Comment by sureshms** [comment] 2023-06-28 20:14
@jvanelteren, can you provide details on what are you typing and why the error is occurring?

**Comment by jvanelteren** [comment] 2023-06-30 08:54
For example as a test I was typing the letter 'a' in the rule name field. The 16th time I pressed the 'a' button, the screen changed to "Something went wrong Cannot read properties of null (reading 'value')".

I tested again with just pressing the letter 'a'. This time the screen changed the 6th time I pressed the 'a' button, so the behaviour seems stochastic.

As a workaround I type the rule name in notepad and I ctrl-c ctrl-v the desired name in the field. This works, although if I repeatedly ctrl-v some characters it eventually also gives the error.

**Comment by harshach** [comment] 2023-07-30 00:15
@jvanelteren we are unable to reproduce this issue in Chrome, safari browsers. If you can reproduce, please capture a screen recording and please do use the latest release or use https://sandbox.open-metadata.org. 
For now we are closing this as unable to reproduce. Please re-open if you still experiencing the issue with latest release

**Closed by harshach** 2023-07-30 00:15 UTC
