### ISSUE TITLE
Oracle connector in UI

### ISSUE THREAD

**Issue by jlanka8** [open-metadata/OpenMetadata#5879] opened 2022-07-06 07:08 UTC
**Affected module**
backend

**Describe the bug**
Then I'm trying to test the connection to oracle in the new version, but I get an error both with the specified databases and without it.

**To Reproduce**
`Failed to test connection due to {"error": "Internal error testing connection 'OracleConnection' object has no attribute 'database' - Traceback (most recent call last):\n File \"/home/airflow/.local/lib/python3.9/site-packages/openmetadata/api/rest_api.py\", line 202, in test_connection\n response = test_source_connection(test_service_connection)\n File \"/home/airflow/.local/lib/python3.9/site-packages/openmetadata/operations/test_connection.py\", line 36, in test_source_connection\n connection = get_connection(test_service_connection.connection.config)\n File \"/usr/local/lib/python3.9/functools.py\", line 877, in wrapper\n return dispatch(args[0].__class__)(*args, **kw)\n File \"/home/airflow/.local/lib/python3.9/site-packages/metadata/utils/connections.py\", line 162, in get_connection\n return create_generic_connection(connection, verbose)\n File \"/home/airflow/.local/lib/python3.9/site-packages/metadata/utils/connections.py\", line 139, in create_generic_connection\n get_connection_url(connection),\n File \"/usr/local/lib/python3.9/functools.py\", line 877, in wrapper\n return dispatch(args[0].__class__)(*args, **kw)\n File \"/home/airflow/.local/lib/python3.9/site-packages/metadata/utils/source_connections.py\", line 154, in _\n assert not connection.database\nAttributeError: 'OracleConnection' object has no attribute 'database'\n"}`

[slack thread](https://openmetadata.slack.com/archives/C02B6955S4S/p1657089755419869)

**Expected behavior**
successful connection

**Version:**
 - OpenMetadata version: 0.11

**Comment by harshach** [comment] 2022-07-06 15:34
looks like a duplicate of this https://github.com/open-metadata/OpenMetadata/issues/5877

**Comment by pmbrull** [comment] 2022-07-11 05:21
closed by https://github.com/open-metadata/OpenMetadata/pull/5889

**Closed by pmbrull** 2022-07-11 05:21 UTC
Labels: bug, Ingestion
