### ISSUE TITLE
UI: Use Rest APIs for "My Data" and "Following" sections in the homepage

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#6421] opened 2022-07-29 05:40 UTC
Currently, we are using the Elastic Search indexes for populating the "My Data" and "Following" sections in the homepage. We should use REST APIs to populate this data since those calls are anyways made on the homepage and it will be more accurate to rely on.

<img width="314" alt="Screen Shot 2022-07-28 at 10 40 45 PM" src="https://user-images.githubusercontent.com/1051198/181690394-740895c3-573d-4e7a-acf6-469da846d4f9.png">

**Comment by Sachin-chaurasiya** [comment] 2022-07-29 05:41
Duplicate of https://github.com/open-metadata/OpenMetadata/issues/4391

**Comment by Sachin-chaurasiya** [comment] 2022-07-29 05:41
@vivekratnavel , I'm working on this https://github.com/open-metadata/OpenMetadata/issues/4391

**Closed by Sachin-chaurasiya** 2022-07-29 05:41 UTC
Labels: UI
