### ISSUE TITLE
No Ni-Fi pipelines after successful ingestion

### ISSUE THREAD

**Issue by mrkoloev** [open-metadata/OpenMetadata#12952] opened 2023-08-21 21:47 UTC
**Affected module**
I guess it is Ingestion Framework.

**Describe the bug**
I connected to ni-fi. Launched data ingestion. It was successful. But there is no pipelines.
Error logs during ingestion:
```
[2023-08-17T14:14:00.227+0000] {client.py:134} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/pipeline/nifi/client.py", line 126, in get
    return res.json()
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**To Reproduce**
![nifi1 (2)](https://github.com/open-metadata/OpenMetadata/assets/42695638/ccd4b56c-e683-4273-8f5c-e14db41451f3)

**Expected behavior**
I expected to see pipelines from ni-fi

**Version:**
 - OS: macOS 13.5, I launched OMD via docker local deployment https://docs.open-metadata.org/v1.0.0/quick-start/local-deployment
 - Python version: 3.9.5
 - OpenMetadata version: 1.1.1
 - OpenMetadata Ingestion package version: 1.1.1.1
 - Ni-fi version: 1.15.3

**Additional context**
I tried with both authentications types. 
Also checked ni-fi api via postman and it's OK

**Comment by pmbrull** [comment] 2023-11-09 05:57
We just got the following message in support:

after the release of version 1.2.0, I attempted to connect Apache NiFi to OpenMetadata again, and it seems like I'm encountering the same errors as before. Here's the error output:

```
"                           [2023-11-08T14:38:15.958+0000] {test_connections.py:198} WARNING - GetPipelines-Expecting value: line 1 column 1 (char 0)
[2023-11-08T14:38:15.958+0000] {test_connections.py:215} INFO - Test connection results:
[2023-11-08T14:38:15.959+0000] {test_connections.py:216} INFO - failed=["'GetPipelines': This is a mandatory step and we won't be able to extract necessary metadata. Failed due to: Expecting value: line 1 column 1 (char 0)"] success=[] warning=[]
[2023-11-08T14:38:15.959+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
 File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
 return_value = self.execute_callable()
 File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
 return self.python_callable(*self.op_args, **self.op_kwargs)
 File "/home/airflow/.local/lib/python3.9/site-packages/openmetadata_managed_apis/workflows/ingestion/common.py", line 201, in metadata_ingestion_workflow
 workflow = MetadataWorkflow.create(config)
 File "/home/airflow/.local/lib/python3.9/site-packages/metadata/workflow/base.py", line 218, in create
 return cls(config)
 File "/home/airflow/.local/lib/python3.9/site-packages/metadata/workflow/base.py", line 123, in __init__
 self.set_steps()
 File "/home/airflow/.local/lib/python3.9/site-packages/metadata/workflow/metadata.py", line 35, in set_steps
 self.source = self._get_source()
 File "/home/airflow/.local/lib/python3.9/site-packages/metadata/workflow/metadata.py", line 54, in _get_source
 source: Source = source_class.create(self.config.source.dict(), self.metadata)
 File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/pipeline/nifi/metadata.py", line 91, in create
 return cls(config, metadata)
 File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/pipeline/pipeline_service.py", line 137, in __init__
 self.test_connection()
 File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/pipeline/pipeline_service.py", line 204, in test_connection
 test_connection_fn(self.metadata, self.connection_obj, self.service_connection)
 File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/source/pipeline/nifi/connection.py", line 67, in test_connection
 test_connection_steps(
 File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/connections/test_connections.py", line 265, in test_connection_steps
 return timeout(timeout_seconds)(_test_connection_steps)(
 File "/home/airflow/.local/lib/python3.9/site-packages/metadata/utils/timeout.py", line 54, in inner
 result = fn(*args, **kwargs)
 File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/connections/test_connections.py", line 104, in _test_connection_steps
 _test_connection_steps_during_ingestion(steps=steps)
 File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/connections/test_connections.py", line 219, in _test_connection_steps_during_ingestion
 raise SourceConnectionException(
metadata.ingestion.connections.test_connections.SourceConnectionException: Some steps failed when testing the connection: [failed=["'GetPipelines': This is a mandatory step and we won't be able to extract necessary metadata. Failed due to: Expecting value: line 1 column 1 (char 0)"] success=[] warning=[]]
[2023-11-08T14:38:15.964+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=tstt_metadata_DEOxeNDP, task_id=ingestion_task, execution_date=20231108T143814, start_date=20231108T143815, end_date=20231108T143815
[2023-11-08T14:38:15.964+0000] {common.py:278} INFO - Sending failed status from callback...
[2023-11-08T14:38:15.965+0000] {server_mixin.py:63} DEBUG - Validating client and server versions
[2023-11-08T14:38:15.968+0000] {common.py:284} INFO - Sending status to Ingestion Pipeline tstt.tstt_metadata_DEOxeNDP
[2023-11-08T14:38:15.984+0000] {ingestion_pipeline_mixin.py:51} DEBUG - Created Pipeline Status for pipeline tstt.tstt_metadata_DEOxeNDP: {'eventType': 'entityUpdated', 'entityType': 'ingestionPipeline', 'entityId': 'ca6850ed-e4dd-4c42-9cff-ccc16b9c3a33', 'entityFullyQualifiedName': 'tstt.tstt_metadata_DEOxeNDP', 'previousVersion': 0.2, 'currentVersion': 0.2, 'userName': 'admin', 'timestamp': 1699454295983, 'changeDescription': {'fieldsAdded': [], 'fieldsUpdated': [{'name': 'pipelineStatus', 'oldValue': {'runId': '88d0151d-7fc4-4087-8af5-ab4111fd940b', 'pipelineState': 'running', 'startDate': 1699454295234, 'timestamp': 1699454295234}, 'newValue': {'runId': '88d0151d-7fc4-4087-8af5-ab4111fd940b', 'pipelineState': 'failed', 'startDate': 1699454295234, 'timestamp': 1699454295234, 'endDate': 1699454295975}}], 'fieldsDeleted': [], 'previousVersion': 0.2}, 'entity': {'id': 'ca6850ed-e4dd-4c42-9cff-ccc16b9c3a33', 'name': 'tstt_metadata_DEOxeNDP', 'displayName': 'tstt_metadata_DEOxeNDP', 'pipelineType': 'metadata', 'fullyQualifiedName': 'tstt.tstt_metadata_DEOxeNDP', 'sourceConfig': {'config': {'type': 'PipelineMetadata', 'includeTags': True, 'includeOwners': True, 'includeLineage': True, 'markDeletedPipelines': True, 'pipelineFilterPattern': {'excludes': [], 'includes': []}}}, 'airflowConfig': {'pausePipeline': False, 'concurrency': 1, 'startDate': 1699228800000, 'pipelineTimezone': 'UTC', 'retries': 0, 'retryDelay': 300, 'pipelineCatchup': False, 'scheduleInterval': '0 * * * *', 'maxActiveRuns': 1, 'workflowDefaultView': 'tree', 'workflowDefaultViewOrientation': 'LR'}, 'loggerLevel': 'DEBUG', 'deployed': True, 'enabled': True, 'href': 'http://openmetadata-server:8585/api/v1/services/ingestionPipelines/ca6850ed-e4dd-4c42-9cff-ccc16b9c3a33', 'version': 0.2, 'updatedAt': 1699361213699, 'updatedBy': 'admin', 'changeDescription': {'fieldsAdded': [], 'fieldsUpdated': [{'name': 'deployed', 'oldValue': False, 'newValue': True}], 'fieldsDeleted': [], 'previousVersion': 0.1}, 'deleted': False, 'provider': 'user'}}
[2023-11-08T14:38:15.995+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 158 for task ingestion_task (Some steps failed when testing the connection: [failed=["'GetPipelines': This is a mandatory step and we won't be able to extract necessary metadata. Failed due to: Expecting value: line 1 column 1 (char 0)"] success=[] warning=[]]; 40750)
[2023-11-08T14:38:16.005+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-11-08T14:38:16.015+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by ayush-shah** [comment] 2023-11-20 07:22
Not able to reproduce, we have added more troubleshooting section, proper error handling.
Make sure the creds are right, nifi policy created properly, and it should work. Thanks.
Closing this.
cc: @open-metadata/ingestion

**Closed by ayush-shah** 2023-11-20 07:22 UTC
Labels: bug, P0, Ingestion

**Comment by mrkoloev** [comment] 2023-11-20 07:57
@ayush-shah test connection is OK 🤔 
However got the same error on 1.2.0

**Comment by ayush-shah** [comment] 2023-11-21 10:47
@mrkoloev can you check the policies? if there are no policies found, or there are any policy related permission issue, that it may cause that error.
ref: https://openmetadata.slack.com/archives/C02B6955S4S/p1699905381327759?thread_ts=1696598804.389129&cid=C02B6955S4S
<img width="659" alt="Screenshot 2023-11-21 at 4 16 51 PM" src="https://github.com/open-metadata/OpenMetadata/assets/40225091/cfc44669-97cd-46a5-9919-828f12ff1a01">
https://community.cloudera.com/t5/Support-Questions/API-call-to-nifi-api-resources-results-in-quot-No-applicable/td-p/363534
