### ISSUE TITLE
Kafka schemaRegistryURL SSL issue 

### ISSUE THREAD

**Issue by SharpLu** [open-metadata/OpenMetadata#14107] opened 2023-11-24 10:43 UTC
**Is your feature request related to a problem? Please describe. 

Yes, currently we have deployed the Open-metadata to AWS EKS cluster (helm-chart)
The background is in an enterprise a lot of infrastructures are separated system , our Kafka schema registry has self-signed SSL certificate [https://xxxx.cp-schema-registry.svc.cluster.local:443], so when airflow trying to send request to this url fetch the schema we got error 

[2023-11-24, 09:11:01 UTC] {common_broker_source.py:202} WARNING - Failed to get schema for topic [affordabilityDetection-UkMatchingCustomerEvent-dlq]: HTTPSConnectionPool(host='xxx.cp-schema-registry.svc.cluster.local', port=443): Max retries exceeded with url: /subjects/affordabilityDetection-UkMatchingCustomerEvent-dlq-value/versions/latest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))

**Describe the solution you'd like**

Would be great that we can attach the SSL certificate with the helm-chart deployment and this certificate need to be trusted by system level, because in future users could be use the OM to fetch third party services right?  So, SSL certificate need to be flexible to deploy to OM.

**Describe alternatives you've considered**
Not sure if there have better alternatives, maybe users can config the SSL from airflow UI? but not sure how to do that
 

**Additional context**
https://openmetadata.slack.com/archives/C02B6955S4S/p1700817488301879

**Comment by ayush-shah** [comment] 2023-11-27 08:55
![image](https://github.com/open-metadata/OpenMetadata/assets/40225091/80583bec-b64c-4b7d-95bf-306443a6c419)
ref: https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html

**Comment by pmbrull** [comment] 2023-12-12 08:17
let's think how to put an "upload file" button

**Comment by ayush-shah** [comment] 2024-04-18 10:06
will be taken care of in #15828 and is a duplicate of #14113, closing this

**Closed by ayush-shah** 2024-04-18 10:06 UTC
Labels: enhancement, Ingestion
