### ISSUE TITLE
Implement Teradata connector for Ingestion

### ISSUE THREAD

**Issue by rich-clarke** [open-metadata/OpenMetadata#11611] opened 2023-05-16 07:21 UTC
**Is your feature request related to a problem? Please describe.**
Currently there is no support for Teradata but having recently moved to SQLFluff as a parser for SQLLineage(which supports Teradata), I think supporting Teradata would make sense. Teradata does currently not have any out of the box lineage tools available and requires manual development, OMD would solve a large gap in the Teradata community. 

**Describe the solution you'd like**
Support a Teradata connector

**Describe alternatives you've considered**
- Using the OpenMetadata Ingestion API to manually push Teradata tables/columns and lineage into OpenMetadata.

**Comment by harshach** [comment] 2024-03-17 17:47
duplicate of #1077

**Closed by harshach** 2024-03-17 17:47 UTC
Labels: enhancement, good-first-issue, connectors, Collate
