### ISSUE TITLE
Insights Experience has several bugs

### ISSUE THREAD

**Issue by trillhaa** [open-metadata/OpenMetadata#10138] opened 2023-02-07 23:47 UTC
**Affected module**
Not sure

**Describe the bug**
There are a number of bugs in Insights section

1. Scrolling down is sometimes not possible, takes 2seconds and requires another click.
2. **{Organization} health section at a glance** does not adjust to timerange, takes only last day's data ✅
3. **Most Viewed Data Assets** does not adjust to timerange, takes only last day's data 👀
4. For **Most Viewed Data Assets**, can you show top 50 and paginate it? https://github.com/open-metadata/OpenMetadata/issues/9275
5. **Most Active Users** is completly broken. - https://github.com/open-metadata/OpenMetadata/issues/10018
6. Unable to select "None" in Tier drop down (not every table might have a tier). https://github.com/open-metadata/OpenMetadata/issues/10139

**Suggestions**
- Show top page views by Team or Tier (not Data Assets).

**Version:**
 - OS: Chrome
 - OpenMetadata version: 0.13.1

**Comment by TeddyCr** [comment] 2023-02-08 05:35
@trillhaa thank you for this feedback. A few questions:
- for 1) would you be able to connect so we can take a look -- @ShaileshParmar11 let us know if there is additional info you need here
- 2) and 3) "{Organization} health section at a glance" this is by intention, this shows you the latest state of the data. Let me circle back to you on "Most Viewed Data Assets" section.
- 4) https://github.com/open-metadata/OpenMetadata/issues/9275 we have an issue open for this
- 5) This was fixed in latest released ✅
- 6) this was by designed. I opened an issue to allow filtering on None https://github.com/open-metadata/OpenMetadata/issues/10139

**Comment by trillhaa** [comment] 2023-02-08 18:30
For 2/3, I may want to clarify that I'm refering to "App Analytics", not "Data Assets": It makes sense for "Data Assets" to show latest status, but not for "App Analytics". Here I'd want to see # of page views / users over the selected days, yesterday's data is not very insightful.

Further, the "Team" filter only seems to apply to users, but not to Assets. This prevents me from looking at the metrics for certain schemas. I find it more interesting to understand how many views a team is receiving on their data assets (because it's actionable: helps the team understand which tables to prioritize for metadata collection), versus understand how active members of a particular team is using OM (not actionable).

I have more feedback in case you guys are interested, we can also hop on a call if needed.

**Comment by TeddyCr** [comment] 2023-03-13 16:15
@trillhaa I am closing this issue as we'll be tracking these bugs in this issue https://github.com/open-metadata/OpenMetadata/issues/10204 with additional improvements. 🙂

**Closed by TeddyCr** 2023-03-13 16:15 UTC
Labels: epic
