### ISSUE TITLE
Custom Properties Knowledge Panel should be displayed in all of the entities right side panel

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#13329] opened 2023-09-25 16:50 UTC
**Feature**
Custom Properties Knowledge Panel should be displayed in all of the entities right side panel.
Users have to switch to custom properties tab to see all the properties available today.
We should build a knowledge panel that allows users to view some of the properties right in the landing page.

**Describe the task**

**Comment by chirag-madlani** [comment] 2023-11-28 13:05
[#13822](https://github.com/open-metadata/OpenMetadata/issues/13822)

**Comment by Sachin-chaurasiya** [comment] 2024-01-04 07:22
Duplicate of #13822

**Closed by Sachin-chaurasiya** 2024-01-04 07:22 UTC
Labels: UI
