### ISSUE TITLE
Split `connection.py` to resolve `too-many-lines` lint error 

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#8215] opened 2022-10-18 12:31 UTC
split connection.py into multiple files to avoid  [too-many-lines](https://github.com/open-metadata/OpenMetadata/blob/9cc90e42fc1d5554a664fad9f983f187acb89fe7/ingestion/src/metadata/utils/connections.py#L1) lint error

**Comment by katebmckay** [comment] 2022-10-19 05:15
Hello, I am interested in doing this issue. Are there any guidelines for how you would like this file split up? Any additional assistance would be appreciated.

**Comment by pmbrull** [comment] 2022-10-19 11:00
hi @katebmckay sorry this issue is actually a duplicate of https://github.com/open-metadata/OpenMetadata/issues/8088

**Comment by pmbrull** [comment] 2022-10-19 11:01
I'll be closing this issue now. You can take a look at what other issues we have labelled as good first issues or for hacktoberfest. Thanks

**Closed by pmbrull** 2022-10-19 11:01 UTC
Labels: P2, Ingestion, cleanup
