### ISSUE TITLE
Getting multiple sources from SQLLineageException text

### ISSUE THREAD

**Issue by jetpacula** [open-metadata/OpenMetadata#12075] opened 2023-06-21 16:29 UTC
**Is your feature request related to a problem? Please describe.**
When parsing query strings with sqllineage.runner.LineageRunner().source_tables (usually happens with aliased tables in queries and queries containing `JOIN`s) SQLLineageException is raised, with text `An Identifier is expected, got Operation[value: database_name.schema_name.table_name] instead.` containing only first source table name. 
**Describe the solution you'd like**
A complete list of source tables, caused SQLLineageException, so it would be possible to retrieve all source table names from exception, or "coerce" mode of parsing, which appends possible source tables that raised SQLLineageExceptions.
**Describe alternatives you've considered**
No workaround was found, only first potential source table could be parsed from SQLLineageException text.

**Comment by pmbrull** [comment] 2023-06-27 08:47
hi @jetpacula please share the full query. These issues are usually related to specific syntax rather than missing a full feature support. If you share the query with us, we can improve the parsing of that specific scenario.

Thanks

**Comment by jetpacula** [comment] 2023-06-28 06:24
obfuscated query below:
```
DELETE FROM databasePlaceholder.schemaPlaceholder.tablePlaceholder1
WHERE datePlaceholder BETWEEN DATE_ADD('{{ds}}', INTERVAL -{{ params.calc_period }} DAY)
                AND DATE('{{ds}}');
INSERT INTO databasePlaceholder.schemaPlaceholder.tablePlaceholder1
SELECT * FROM databasePlaceholder.recalcSchemaPlaceholder.tablePlaceholder1;

DELETE FROM databasePlaceholder.schemaPlaceholder.tablePlaceholder2
WHERE datePlaceholder BETWEEN DATE_TRUNC(DATE_ADD('{{ds}}', INTERVAL -{{ params.calc_period }} DAY), MONTH)
                AND LAST_DAY(DATE('{{ds}}'), MONTH);
INSERT INTO databasePlaceholder.schemaPlaceholder.tablePlaceholder2
SELECT * FROM databasePlaceholder.recalcSchemaPlaceholder.tablePlaceholder2;

DELETE FROM databasePlaceholder.schemaPlaceholder.tablePlaceholder3
WHERE datePlaceholder BETWEEN DATE_TRUNC(DATE_ADD('{{ds}}', INTERVAL -{{ params.calc_period }} DAY), WEEK(MONDAY))
                AND DATE_ADD(DATE_TRUNC(DATE('{{ds}}'), WEEK(MONDAY)), INTERVAL 6 DAY);
INSERT INTO databasePlaceholder.schemaPlaceholder.tablePlaceholder3
SELECT * FROM databasePlaceholder.recalcSchemaPlaceholder.tablePlaceholder3;

DELETE FROM databasePlaceholder.schemaPlaceholder.tablePlaceholder4
WHERE datePlaceholder BETWEEN DATE_ADD('{{ds}}', INTERVAL -{{ params.calc_period }} DAY)
                /* some same lines */
INSERT INTO databasePlaceholder.schemaPlaceholder.tablePlaceholder5
SELECT * FROM databasePlaceholder.recalcSchemaPlaceholder.tablePlaceholder5;

DELETE FROM databasePlaceholder.schemaPlaceholder.tablePlaceholder6
where orderDatePlaceholder BETWEEN DATE_TRUNC(DATE_ADD('{{ds}}', INTERVAL -{{ params.calc_period }} DAY), WEEK(MONDAY))
                                         AND DATE_ADD(DATE_TRUNC(DATE('{{ds}}'), WEEK(MONDAY)), INTERVAL 6 DAY);
INSERT INTO databasePlaceholder.schemaPlaceholder.tablePlaceholder6
SELECT * FROM databasePlaceholder.recalcSchemaPlaceholder.tablePlaceholder6;

DELETE FROM databasePlaceholder.schemaPlaceholder.tablePlaceholder7
where orderDatePlaceholder BETWEEN DATE_TRUNC(DATE_ADD('{{ds}}', INTERVAL -{{ params.calc_period }} DAY), MONTH)
                                         AND LAST_DAY(DATE('{{ds}}'), MONTH);
INSERT INTO databasePlaceholder.schemaPlaceholder.tablePlaceholder7
SELECT * FROM databasePlaceholder.recalcSchemaPlaceholder.tablePlaceholder7;

DELETE FROM databasePlaceholder.schemaPlaceholder.tablePlaceholder8
where orderDatePlaceholder BETWEEN DATE_TRUNC(DATE_ADD('{{ds}}', INTERVAL -{{ params.calc_period }} DAY), WEEK(MONDAY))
                                         AND DATE_ADD(DATE_TRUNC(DATE('{{ds}}'), WEEK(MONDAY)), INTERVAL 6 DAY);
INSERT INTO databasePlaceholder.schemaPlaceholder.tablePlaceholder8
SELECT * FROM databasePlaceholder.recalcSchemaPlaceholder.tablePlaceholder8;
```
but sadly when I run unobfuscated version it gives a normal result: the list of source tables.
the scenario is when a query like this is parsed without specifying dialect for validation (and non-validating mode is used by default) the error is raised like
'An Identifier is expected, got Operation[value: database_name.schema_name.table_name] instead.'
which contains valid source, like database_name.schema_name.table_name, however the other tables are not in the exception text, and this is a point of this feature request, if this exception is raised, for it to contain all the possible source tables, not just the first that raised the exception.
the actual queries are with Big Query dialect.

Hope that helps!

**Comment by jetpacula** [comment] 2023-06-28 09:12
But what is weird, after obfuscating the sources parsed fine. Probable cause is that original table/schema/db names had the numbers and "-" symbols.

**Comment by pmbrull** [comment] 2023-06-28 13:56
hi @jetpacula if you could share some example of the "weird" names with symbols we could try to replicate with them too. It could possibly be breaking the parsing. Also, this query looks like it comes from airflow. When it gets picked up by the lineage, I guess that it does not keep the jinja macros `{{ ds }}` etc. but rather real values right?

**Comment by pmbrull** [comment] 2023-09-14 10:43
hi @jetpacula please we'd need some more information here. Otherwise, we'll need to close this since we cannot reproduce the issue

**Closed** 2023-09-21 05:49 UTC
Labels: enhancement, Ingestion, lineage
