### ISSUE TITLE
Global Search Suggestion

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#405] opened 2021-09-06 00:03 UTC
http://localhost:8585/api/v1/search/suggest?q=fc*&index=dashboard_search_index,topic_search_index,table_search_index

```{
  "suggest": {
    "table-suggest": [
      {
        "text": "fc*",
        "offset": 0,
        "length": 3,
        "options": [
          {
            "text": "FCC New Coder Survey 2018",
            "_index": "dashboard_search_index",
            "_type": "_doc",
            "_id": "ea537986-2d64-4d22-928f-059d98f3ea86",
            "_score": 10,
            "_source": {
              "dashboard_id": "ea537986-2d64-4d22-928f-059d98f3ea86",
              "service": "sample_superset",
              "service_type": "Superset",
              "dashboard_name": "FCC New Coder Survey 2018",
              "suggest": [
                {
                  "input": [
                    "FCC New Coder Survey 2018"
                  ],
                  "weight": 10
                }
              ],
              "description": "",
              "last_updated_timestamp": 1630886488,
              "chart_names": [
                "Boy Name Cloud",
                "Box plot",
                "Arcs",
                "Average and Sum Trends"
              ],
              "chart_descriptions": [
                "",
                "",
                "",
                ""
              ],
              "tags": [],
              "fqdn": "sample_superset.11",
              "tier": null,
              "owner": "",
              "followers": []
            }
          },
          {
            "text": "Fc_dim_address",
            "_index": "table_search_index",
            "_type": "_doc",
            "_id": "c8efd722-aab6-4ad1-af7c-358e93adda71",
            "_score": 10,
            "_source": {
              "table_id": "c8efd722-aab6-4ad1-af7c-358e93adda71",
              "database": "shopify",
              "service": "bigquery",
              "service_type": "BigQuery",
              "table_name": "Fc_dim_address",
              "suggest": [
                {
                  "input": [
                    "bigquery.shopify.Fc_dim_address"
                  ],
                  "weight": 5
                },
                {
                  "input": [
                    "Fc_dim_address"
                  ],
                  "weight": 10
                }
              ],
              "description": "This dimension table contains the billing and shipping addresses of customers. You can join this table with the sales table to generate lists of the billing and shipping addresses. Customers can enter their addresses more than once, so the same address can appear in more than one row in this table. This table contains one row per customer address.",
              "table_type": "Regular",
              "last_updated_timestamp": 1630886487,
              "column_names": [
                "address_id",
                "shop_id",
                "first_name",
                "last_name",
                "address1",
                "address2",
                "company",
                "city",
                "region",
                "zip",
                "country",
                "phone"
              ],
              "column_descriptions": [
                "Unique identifier for the address.",
                "The ID of the store. This column is a foreign key reference to the shop_id column in the dim_shop table.",
                "First name of the customer.",
                "Last name of the customer.",
                "The first address line. For example, 150 Elgin St.",
                "The second address line. For example, Suite 800.",
                "The name of the customer's business, if one exists.",
                "The name of the city. For example, Palo Alto.",
                "The name of the region, such as a province or state, where the customer is located. For example, Ontario or New York. This column is the same as CustomerAddress.province in the Admin API.",
                "The ZIP or postal code. For example, 90210.",
                "The full name of the country. For example, Canada.",
                "The phone number of the customer."
              ],
              "monthly_stats": 0,
              "monthly_percentile_rank": 0,
              "weekly_stats": 0,
              "weekly_percentile_rank": 0,
              "daily_stats": 0,
              "daily_percentile_rank": 0,
              "tags": [],
              "fqdn": "bigquery.shopify.Fc_dim_address",
              "tier": null,
              "schema_description": null,
              "owner": "",
              "followers": []
            }
          },
          {
            "text": "fc_customer_events",
            "_index": "topic_search_index",
            "_type": "_doc",
            "_id": "8ccd1f78-d2f8-49d7-abc7-10345d6e0428",
            "_score": 10,
            "_source": {
              "topic_id": "8ccd1f78-d2f8-49d7-abc7-10345d6e0428",
              "service": "sample_kafka",
              "service_type": "Kafka",
              "topic_name": "fc_customer_events",
              "suggest": [
                {
                  "input": [
                    "sample_kafka.fc_customer_events"
                  ],
                  "weight": 5
                },
                {
                  "input": [
                    "fc_customer_events"
                  ],
                  "weight": 10
                }
              ],
              "description": "Kafka topic to capture the customer events such as location updates or profile updates",
              "last_updated_timestamp": 1630886488,
              "tags": [],
              "fqdn": "sample_kafka.fc_customer_events",
              "tier": null,
              "schema_description": null,
              "owner": "",
              "followers": []
            }
          }
        ]
      }
    ]
  }
}```

**Comment by Sachin-chaurasiya** [comment] 2021-09-06 08:31
Duplicate of #362

**Closed by Sachin-chaurasiya** 2021-09-06 08:31 UTC
