### ISSUE TITLE
UI: Improve UX for Queries tab -> Table entity page

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#8270] opened 2022-10-19 18:16 UTC
For inspiration
https://uploads-ssl.webflow.com/6087db3cbaa248cd720ccdc5/6228c32bfe5d98946ea96c47_Leverage%20work%20done%20by%20your%20peers.png

**Comment by Sachin-chaurasiya** [comment] 2022-11-25 05:29
duplicate of #8096

**Closed by Sachin-chaurasiya** 2022-11-25 05:29 UTC
Labels: P2, UI
