### ISSUE TITLE
Vertica Timestamp column fix

### ISSUE THREAD

**Issue by codingwithabhi** [open-metadata/OpenMetadata#2945] opened 2022-02-23 09:14 UTC
**Describe the bug**
Ingestion fails in Vertica with Timestamp Column.

**Comment by harshach** [comment] 2022-02-25 17:53
@ayush-shah moving this to 0.10

**Comment by ayush-shah** [comment] 2022-03-08 13:40
Couldn't reproduce the same, should we close the issue for now and reopen if reproduced in the future?
cc: @harshach

**Comment by harshach** [comment] 2022-03-12 16:50
closing this. Please re-open if you see this issue again

**Closed by harshach** 2022-03-12 16:50 UTC
Labels: P1, Ingestion
