### ISSUE TITLE
search indexing failure for firstname.lastname in dbt tests

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#16771] opened 2024-06-24 11:29 UTC
**Affected module**
search indexing

**Describe the bug**
search indexing failure for firstname.lastname in dbt tests

```
 [message]: OpenSearchException[OpenSearch exception [type=document_parsing_exception, reason=[1:334] failed to parse field [updatedBy] of type [text] in document with id 'd5825400-62d1-4c32-9a9f-b5ad01de8392'. Preview of field's value: '{deleted=false, displayName=ingestion-bot, name=ingestion-bot, id=38dda5c7-d381-4477-b6dd-cc8f14cf797c, type=user, fullyQualifiedName=ingestion-bot}']]; nested: OpenSearchException[OpenSearch exception [type=illegal_state_exception, reason=Can't get text on a START_OBJECT at 1:170]];
  [3]:
    [entity]: 3
    [message]: OpenSearchException[OpenSearch exception [type=document_parsing_exception, reason=[1:221] failed to parse field [updatedBy] of type [text] in document with id 'cbcdbce7-12aa-47a3-9c02-4e3487e51c1e'. Preview of field's value: '{type=User, fullyQualifiedName=firstname.lastname}']]; nested: OpenSearchException[OpenSearch exception [type=illegal_state_exception, reason=Can't get text on a START_OBJECT at 1:170]];
  [4]:
    [entity]: 4
    [message]: OpenSearchException[OpenSearch exception [type=document_parsing_exception, reason=[1:745] failed to parse field [updatedBy] of type [text] in document with id '8ee7f5d8-67a5-45c2-b9f3-30730a2507f3'. Preview of field's value: '{deleted=false, displayName=firstname.lastname, name=firstname.lastname, id=4550617d-4b99-488e-9cdb-0f504251219b, type=user, fullyQualifiedName="firstname.lastname"}']]; nested: OpenSearchException[OpenSearch exception [type=illegal_state_exception, reason=Can't get text on a START_OBJECT at 1:577]];
  [5]:
    [entity]: 5
    [message]: OpenSearchException[OpenSearch exception [type=document_parsing_exception, reason=[1:385] failed to parse field [updatedBy] of type [text] in document with id 'ef908d31-bdd8-46d6-a48c-953e8804a50f'. Preview of field's value: '{type=User, fullyQualifiedName=other_firstname.other_lastname}']]; nested: OpenSearchException[OpenSearch exception [type=illegal_state_exception, reason=Can't get text on a START_OBJECT at 1:335]];
  [6]:
    [entity]: 6
    [message]: OpenSearchException[OpenSearch exception [type=document_parsing_exception, reason=[1:335] failed to parse field [updatedBy] of type [text] in document with id '892e0322-e5a9-4af3-a6ea-3daf0798343f'. Preview of field's value: '{deleted=false, displayName=other_firstname.other_lastname, name=other_firstname.other_lastname, id=0d40b9c7-3e65-4fe9-8592-06e75f7f429c, type=user, fullyQualifiedName="other_firstname.other_lastname"}']]; nested: OpenSearchException[OpenSearch exception [type=illegal_state_exception, reason=Can't get text on a START_OBJECT at 1:170]];
  [7]:
    [entity]: 7
    [message]: OpenSearchException[OpenSearch exception [type=document_parsing_exception, reason=[1:334] failed to parse field [updatedBy] of type [text] in document with id 'e38d7481-01c7-4fa4-bde5-f5f798c2287a'. Preview of field's value: '{deleted=false, displayName=ingestion-bot, name=ingestion-bot, id=38dda5c7-d381-4477-b6dd-cc8f14cf797c, type=user, fullyQualifiedName=ingestion-bot}']]; nested: OpenSearchException[OpenSearch exception [type=illegal_state_exception, reason=Can't get text on a START_OBJECT at 1:170]];
[submittedCount]: 8
```

**To Reproduce**

dbt schema yaml with

```
  - name: my_dbt_model
    description: 'my description'
    +tags: "foo_tag"

    meta:
      owner: "firstname.lastname"
      openmetadata:
        tier: 'Tier.Tier2'
      my_custom_meta: mymeta
    columns:
      - name: id
        description: "A starter dbt model: which demonstrates an update on a column comment"
        tests:
          - unique
          - not_null

```

**Expected behavior**

indexing should not fail for user identifiers which include a dot (`.`)

**Version:**
- OM 1.4.3
- python ingestion 1.4.3.2

**Comment by harshach** [comment] 2024-06-24 15:27
@sonika-shah can you check here

**Comment by harshach** [comment] 2024-06-24 16:37
Thanks @sonika-shah . @OnkarVO7 lets address this.

**Comment by OnkarVO7** [comment] 2024-06-25 04:47
I'll take a look

**Comment by OnkarVO7** [comment] 2024-07-23 05:49
Hi @geoHeil tried to reproduce this but was unable to do so. Can you please share the steps to reproduce it.

Also since this is being cause by dbt test, will you be able to share the test details which test is causing it? Also if you can share the snippet from run_results.json it'll be helpful

**Comment by geoHeil** [comment] 2024-07-24 07:32
I fear after a recent change at my company in the last days I will not be able to hand this out any more. Worst case we will have to close this bug here for now

**Comment by OnkarVO7** [comment] 2024-07-25 06:16
Got it thanks. Closing the issue we can reopen if the issue happens again

**Closed by OnkarVO7** 2024-07-25 06:16 UTC
Labels: bug
