### ISSUE TITLE
DataBricks Sample Data Issue

### ISSUE THREAD

**Issue by Supan90-Shah3006** [open-metadata/OpenMetadata#13402] opened 2023-10-02 13:59 UTC
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ans : Ingestion Framework

**Describe the bug**
When i'm configuring Databricks as a Database Service, I found a bug in a sample data. There is no data available in sample data tab. Here I'm attaching a screenshot of it & schema of database for which i configured database service.
![image](https://github.com/open-metadata/OpenMetadata/assets/71488507/43bc8d1d-f30f-4b02-944d-fc735f6f671f)
![image](https://github.com/open-metadata/OpenMetadata/assets/71488507/5b6d8773-fe62-4195-8546-7d6c21222865)

**To Reproduce**

Create A Databricks Environment & Configure Database Service With Given Database Schema. Also, I'm providing a debug logs for your understanding.
![image](https://github.com/open-metadata/OpenMetadata/assets/71488507/0db6884d-ce8d-4bf3-a082-dd46f9e38bc1)

**Expected behavior**
It should show a sample data.

**Version:**
 - OpenMetadata version: 1.1.2

**Comment by know-jon** [comment] 2023-10-05 14:23
Sampling ingestion is separate from regular metadata ingestion, for data sources there are multiple types of ingestion: 
![image](https://github.com/open-metadata/OpenMetadata/assets/105928701/836bb767-4313-4b44-ba6f-4e865bab635e)

Can you confirm that you have added profiler ingestion and that it ran successfully?

**Comment by Supan90-Shah3006** [comment] 2023-10-06 05:19
Hey @know-jon , 
Thanks For Reply. 
I successfully ran profiler ingestion pipeline for the same. In Profiler & Data Quality Tab I saw Table Profile & Column Profile also.

**Comment by pmbrull** [comment] 2023-12-15 07:12
@ayush-shah let's review as well how we can bring databricks tags into OM

**Comment by NiharDoshi99** [comment] 2024-01-25 12:08
Hi, I would like to work on databricks tags issue.

**Comment by ayush-shah** [comment] 2024-01-25 13:50
<img width="1307" alt="Screenshot 2024-01-25 at 7 17 17 PM" src="https://github.com/open-metadata/OpenMetadata/assets/40225091/ffde665a-3d6b-475c-8619-888c2439be73">

<img width="804" alt="Screenshot 2024-01-25 at 7 19 01 PM" src="https://github.com/open-metadata/OpenMetadata/assets/40225091/950657f6-e19c-44d1-b665-fececf97b8a8">



@Supan90-Shah3006 couldn't reproduce the sample data issue that you are facing, can you try profiling in the latest version?

I was able to ingest the sample data without any issues for all the data types that can be seen above in the screenshot you attached. Try latest OM version, if it still persists, share the debug logs, sample data from that table and DDL of that table.

**Comment by pmbrull** [comment] 2024-01-26 06:08
Closing as we can't reproduce. @Supan90-Shah3006 feel free to reopen the issue if the behavior persists in the latest release

**Closed by pmbrull** 2024-01-26 06:08 UTC
Labels: bug, Ingestion
