### ISSUE TITLE
Data Quality test suite for the tables is only executing for the first test case.

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#12517] opened 2023-07-20 06:14 UTC
**Affected module**
UI - Data Quality

**Describe the bug**
Upon execution of the test suite against the tables, only the first test case gets executed and the job is being marked as success (completed).

**To Reproduce**

<img width="785" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/110607559/ac5f7f4b-f8dc-46bd-b731-5deccd9f56df">
[vehicle_maintenance_test suite _latest.txt](https://github.com/open-metadata/OpenMetadata/files/12102551/vehicle_maintenance_test.suite._latest.txt)

**Expected behavior**
The execution should include all the test case against the tables.

**Version:**
1.2

**Comment by lailapatel** [comment] 2023-07-20 06:15
log :

**Comment by DovileKr** [comment] 2023-07-21 08:02
similarly, I have three tests on bq table. the ingestion shown as success 
![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/ac6cb582-20ec-4130-a297-e0d8cccc9df9)


but one is still from two days ago:
![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/ed90ff6c-61d9-4d8f-898d-65850d33af4a)

**Comment by ayush-shah** [comment] 2023-07-27 10:05
On editing the test cases, the user gets
An exception with message [Cannot invoke "org.openmetadata.schema.type.EntityReference.getId()" because "ref" is null] was thrown while processing request.

cc: @open-metadata/backend

**Comment by DovileKr** [comment] 2023-07-27 14:48
new error: An exception with message [null] was thrown while processing request.

**Comment by DovileKr** [comment] 2023-07-28 13:21
@ayush-shah 
so I think I know what the problem is (but not a root cause). If I call GET api for those test cases that aren't executing, the only testSuite link is to the logical testSuite and there is no link to the "executable" testSuite.
the ones that are running ok - I get the executable testSuite as well. (on  the same table I would get one testCase with exec and logIcal and another one - just logical). Not sure, why, while creating testSuites pipelines for each table it worked for some testCases, but not for others. Maybe I clicked "create pipeline" , before all the testCases  were loaded on the UI (as we know it takes a long time for testCases to appear on the  UI).
I would like run POST on the testCase to attach the executable testSuite as well, but a single testCase can have multiple testSuites (one executable and many logical?), but api expects a [single fqn](https://docs.open-metadata.org/swagger.html#operation/createOrUpdateTest). I think.  So what would be correct API structure?
so on the POST I only then added the  executable testSuite. I got back 200 ok response, but testSuites on the testCase  weren't updated - still only showing the logical one. 
![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/00e97de6-9810-4d26-bf8e-4ac09d47fdf2)

![image](https://github.com/open-metadata/OpenMetadata/assets/26750060/beca8f04-a556-48c1-ad6f-7792e87a6a6d)

just a note that executable testSuite FQN is very strange :slightly_smiling_face: "testSuite": "\"a3e751027d6c61d44013b923e3f0f2a4.c6c668321cace9fabba65ba6c96b4554.d1df466337b117ecb4f339f6b7f17875.112d4a1db91c3bd743a21c6dfcde8553.be2115a37e73abc64be935171220c2f4\"". does  it represent anything?
so how could I add those executable testSuites to those erroring testCases?

**Comment by ayush-shah** [comment] 2023-07-29 18:30
Will be fixed in 1.1.1
identified as a bug, will have it fixed and keep things posted.

**Comment by pmbrull** [comment] 2023-08-04 04:54
validated with the latest code. It will be part of the 1.1.1 release

**Closed by pmbrull** 2023-08-04 04:54 UTC
Labels: Ingestion, validation

**Comment by lailapatel** [comment] 2023-08-15 08:50
After the deployment of release 1.1.1. the above DQ issues still persists.

1. DQ testsuite is not getting executed

<img width="774" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/110607559/c900ad9f-29c3-4abc-8e72-3cc1128f6882">
<img width="868" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/110607559/8f05da39-55c6-4186-83d5-21a2650aa95c">

2. Test case name cannot be updated
