### ISSUE TITLE
Selecting from table_entity fails due to wrong index selection

### ISSUE THREAD

**Issue by xenji** [open-metadata/OpenMetadata#3504] opened 2022-03-18 07:19 UTC
**Affected module**
backend

**Describe the bug**
While ingesting data from redshift, I encounter this exception:
```
{"responseMessage":"An exception with message [java.sql.SQLException: Out of sort memory, consider increasing server sort buffer size [statement:\"/* TableDAO.listAfter */ SELECT json FROM table_entity WHERE (fullyQualifiedName LIKE CONCAT(:fqnPrefix, '.%') OR :fqnPrefix IS NULL) AND fullyQualifiedName > :after AND (deleted = :deleted OR :deleted IS NULL) ORDER BY fullyQualifiedName LIMIT :limit\", arguments:{positional:{2:aws_redshift_cluster_main.global,3:101,4:,5:false}, named:{deleted:false,fqnPrefix:aws_redshift_cluster_main.global,limit:101,after:}, finder:[]}]] was thrown while processing request."}
```

Which basically means that the result is too large to be sorted properly. This happens normally if you don’t have a good selectivity on the index or you are not using any index at all.

The assembled query looks like this:
```sql
SELECT json
FROM table_entity
WHERE (fullyQualifiedName LIKE CONCAT('aws_redshift_cluster_main.global', '.%') OR 'aws_redshift_cluster_main.global' IS NULL)
  AND fullyQualifiedName > ''
  AND (deleted = false OR false IS NULL)
ORDER BY fullyQualifiedName
LIMIT 101;
```

The ORM is generating weird clauses, esp. checking for false being null or a value being null. Anyway, removing them does not change the result. For clarity, here is the reduced query:

```sql
SELECT json
FROM table_entity
WHERE fullyQualifiedName LIKE CONCAT('aws_redshift_cluster_main.global', '.%')
  AND deleted = false
ORDER BY fullyQualifiedName
LIMIT 101;
```
The database is an AWS RDS MySQL 8 instance with a db.m6g.large instance size and the default MySQL 8 parameter group.

```sql
SELECT count(*) from table_entity; -- 385
```
An explain on the query yields that there are two possible keys to use, unique_name and deleted. The optimizer selects the deleted index instead of the unique_name, which is the wrong choice because of the low selectivity. The query plan would then first select all false, then sort, and then apply the LIKE statement for efficiency - as far as I remember.

Anyway, nudging the query planner in the right direction fixes the problem:

```sql
SELECT json
FROM table_entity
FORCE INDEX (unique_name)
WHERE fullyQualifiedName LIKE CONCAT('aws_redshift_cluster_main.global', '.%')
   AND deleted = false
ORDER BY fullyQualifiedName
LIMIT 101;
```

I don’t think that changing the sort buffer would be a good solution, because the database is clearly capable of handling the workload with the correct index applied.

```sql
show variables like 'sort_buffer_size'; -- 262144
```

**To Reproduce**

see above

**Expected behavior**

**Version:**
 - OS: AWS RDS MySQL 8.0.27
 - OpenMetadata version: 0.9

**Comment by xenji** [comment] 2022-03-18 07:20
A little trick I used in the past would be to take the unwanted index from an equal check to an not-equal check:

```sql
SELECT json
FROM table_entity
WHERE fullyQualifiedName LIKE 'aws_redshift_cluster_main.global.%'
   AND deleted != true -- <- HERE
ORDER BY fullyQualifiedName
LIMIT 101;
```

**Comment by harshach** [comment] 2022-03-18 14:37
@sureshms this should've been fixed by your recent refactor right?

**Comment by harshach** [comment] 2022-03-18 14:57
@xenji Thanks for filing this. I assume you are using the release version not building it from main. I ask because we have instance running on AWS with RDS didn't see this issue. But will try to reproduce this.

**Comment by sureshms** [comment] 2022-03-21 23:18
@xenji, here is a link that might explain your query rewrite with `deleted != true` - https://stackoverflow.com/questions/6084460/mysql-not-using-index-when-checking-1-but-using-it-with-0

Can you check this same query with index for deleted column dropped and see if you can reproduce the problem?

**Comment by xenji** [comment] 2022-03-29 09:56
Hey @sureshms, if the index is not there, the only option for the optimiser is to use `fullyQualifiedName`. That would be the same as with my `FORCE INDEX` statement.

Here is the query plan after dropping the index:
```json
{
  "query_block": {
    "select_id": 1,
    "cost_info": {
      "query_cost": "105.50"
    },
    "ordering_operation": {
      "using_filesort": false,
      "table": {
        "table_name": "table_entity",
        "access_type": "index",
        "possible_keys": [
          "unique_name"
        ],
        "key": "unique_name",
        "used_key_parts": [
          "fullyQualifiedName"
        ],
        "key_length": "1026",
        "rows_examined_per_scan": 101,
        "rows_produced_per_join": 215,
        "filtered": "90.00",
        "cost_info": {
          "read_cost": "83.90",
          "eval_cost": "21.60",
          "prefix_cost": "105.50",
          "data_read_per_join": "469K"
        },
        "used_columns": [
          "id",
          "fullyQualifiedName",
          "json",
          "deleted"
        ],
        "attached_condition": "((`openmetadata_db`.`table_entity`.`fullyQualifiedName` like 'aws_redshift_cluster_main.global.%') and (`openmetadata_db`.`table_entity`.`deleted` <> true))"
      }
    }
  }
}
```

**Comment by sureshms** [comment] 2022-03-30 20:35
Marking this issue as resolved. All the queries now are simplified. Also `deleted` column index is removed in #3770.

**Closed by sureshms** 2022-03-30 20:35 UTC
Labels: bug, blocker, P0
