### ISSUE TITLE
Redshift usage ingestions failing after upgrade to 1.2.2

### ISSUE THREAD

**Issue by 17rahulsharma** [open-metadata/OpenMetadata#14259] opened 2023-12-06 03:43 UTC
**Affected module**
Ingestion framework: Ingestions process to ingest usage from Redshift setup 

**Describe the bug**
Usage ingestion job is not able to parse the query(es) and resulting into the failure of the ingestion pipeline  at Airflow. Here also attaching the logs from failed ingestion process
[log_redshift_usage_2023-12-05.txt](https://github.com/open-metadata/OpenMetadata/files/13575575/log_redshift_usage_2023-12-05.txt)

**To Reproduce**
![image](https://github.com/open-metadata/OpenMetadata/assets/131245764/ce219b6b-955b-47ad-91db-5098eb9620e3)

**Expected behavior**
Expected the ingestion process to ingest the usage details to OMD should run normally.

**Version:**
 - OpenMetadata version: 1.2.2 , earlier version was 1.1.7

**Additional context**
The slack thread details
https://openmetadata.slack.com/archives/C02B6955S4S/p1701769004936159

**Comment by ulixius9** [comment] 2024-01-18 05:36
closing this ticket as not able to reproduce by https://github.com/open-metadata/OpenMetadata/pull/14505

**Closed by ulixius9** 2024-01-18 05:36 UTC
Labels: bug, Ingestion, validation, lineage
