### ISSUE TITLE
Snowflake ingestion connector unable to parse VARIANT type

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#2870] opened 2022-02-20 01:06 UTC
**Affected module**
ingestion snowflake

**Describe the bug**
 Variant types are being converted into VARBINARY and failing _check_col_length
Possibly due to some regex mapping
Variant is a class when it is trying to compare against strings types

**To Reproduce**

Screenshots or steps to reproduce

**Comment by ayush-shah** [comment] 2022-02-22 04:36
Tested this issue out, not able to reproduce. Solved in column_type_parser. Closing this issue.

**Closed by ayush-shah** 2022-02-22 04:36 UTC
Labels: bug, P1, Ingestion
