### ISSUE TITLE
Subteams still count after deletion of parent team

### ISSUE THREAD

**Issue by kate-tester-de** [open-metadata/OpenMetadata#12928] opened 2023-08-18 21:48 UTC
**Affected module**
UI and maybe backend

**Describe the bug**
When a team of one the higher orders is created and a subteam created under it (example Department and Group), if the parent team is deleted, the subteam does not show in the list but it counted in the count of total teams for the organization

**To Reproduce**

<img width="1426" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/102185113/93fbce7f-8926-43fa-acd5-f0009405994f">

**Expected behavior**
I expected that either of the following things would happen:
1. The subteams are removed entirely (dangerous once the system is in use, but okay at the start of setup)
2. The subteams are made a part of the next parent. If there is no other parent, then it goes under the organization. However, this would mean that teams are movable, and I don't see that option right now.

**Version:**
 - OS: [e.g. iOS] iOS Ventura 13.5
 - Python version: 3.7.13
 - OpenMetadata version: [e.g. 0.8] 1.1
 - OpenMetadata Ingestion package version:1.1.1

**Additional context**

**Comment by sureshms** [comment] 2023-08-19 01:17
This is the intended behavior. When a parent team is deleted, organization is made the default parent of organization. In the end all the users and teams belong to an organization. 

Closing this as not an issue.

**Closed** 2023-08-19 01:18 UTC
