### ISSUE TITLE
Blank page is displayed on Roles page

### ISSUE THREAD

**Issue by kshinde2512** [open-metadata/OpenMetadata#4159] opened 2022-04-14 20:25 UTC
**Affected module**
UI

**Describe the bug**
A blank page is displayed after navigating to Roles page

**To Reproduce**
- Navigate to roles page from settings dropdown

https://user-images.githubusercontent.com/67048554/163469757-145169db-8366-4fc4-9d08-5ee8c8f5942b.mp4

**Expected behavior**
Roles page should be displayed 

**Version:**
 - OpenMetadata version: 0.9.0

**Additional context**
```http://localhost:8585/api/v1/roles?fields=policy,users,teams&limit=1000000```

**Comment by kshinde2512** [comment] 2022-04-14 20:25
@darth-coder00 @Sachin-chaurasiya

**Comment by Sachin-chaurasiya** [comment] 2022-04-14 20:27
Duplicate of #4130

**Closed by Sachin-chaurasiya** 2022-04-14 20:27 UTC
