### ISSUE TITLE
[BUG] Feature terms related in glossary does not save the term relationship

### ISSUE THREAD

**Issue by rogerzs** [open-metadata/OpenMetadata#9713] opened 2023-01-12 19:51 UTC
**Affected module**
No

**Describe the bug**
When i try to save a related term in some term of glossary the UI returns a error "glossary for instance ...... not found".
**To Reproduce**

1 - Try to edit some term
2 - ADD some realated term and save

after that you will receive something like that:

![Captura de tela de 2023-01-12 16-36-55](https://user-images.githubusercontent.com/56163805/212164893-8413560f-3d2c-4a3c-9907-8d018f21ef87.png)

When you leave the page, the related term will not have been saved

**Expected behavior**

Save the related term and not get an error.

**Version:**
 - OS: Linux
 - Python version: 3.10.7
 - OpenMetadata version: 0.13.11
 - OpenMetadata Ingestion package version: Latest
 
 I'm using OM in K8S

**Additional context**

**Comment by sureshms** [comment] 2023-01-12 20:07
I can also reproduce this on sandbox
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/1417689/212169912-3219baab-f598-42a2-855e-7d568980153c.png">

**Comment by Sachin-chaurasiya** [comment] 2023-01-13 05:11
Hello @rogerzs, Thanks for filing the ticket.
The fix for the issue is already merged and here is the working example.

https://user-images.githubusercontent.com/59080942/212242274-cab2c972-8074-4b87-bdc1-441b7c2a48c4.mov

cc: @sureshms

**Closed by Sachin-chaurasiya** 2023-01-13 05:11 UTC
