### ISSUE TITLE
generate sample data errors when schema name contains '-'

### ISSUE THREAD

**Issue by zlz-cn** [open-metadata/OpenMetadata#5769] opened 2022-06-30 06:24 UTC
**Affected module**
Ingestion Framework

**Describe the bug**
I  used mysql connector to generate sample data, but it went wrong. i see logs found : select * from  xxx-xxx-xxx. 

**To Reproduce**

to reproduce that, u can create a schema which named like "xxx-xxx"( name contains '-'), and then try to  used mysql connector to generate sample data

**Expected behavior**
the correct sql may like " select * from \`xxx-xxx-xxx\` ", \` make it "escapes"

**Version:**
 - Python version:
 - OpenMetadata version: 0.10.1
 - OpenMetadata Ingestion package version:  `openmetadata-ingestion[docker]==0.10.1`

**Additional context**
I had look logs, it is right when generated schema. so may some one foget to add `

**Comment by TeddyCr** [comment] 2022-09-06 07:36
@harshach this seems to be fixed in 0.12. @zlz-cn once 0.12 is available could you confirm this is fixed on your end as well? Thank you 🙏 

![Screenshot 2022-09-06 at 9 35 44 AM](https://user-images.githubusercontent.com/13626425/188574735-383fbe33-fee0-46a5-894f-a2a03ef5b7e1.png)

**Comment by zlz-cn** [comment] 2022-09-06 08:38
@TeddyCr of course ， i will confirm it at 0.12

**Comment by ayush-shah** [comment] 2022-09-13 04:57
@zlz-cn closing this ticket, if it's reproducible, do let us know and we can reopen the same.
Thanks.

**Closed by ayush-shah** 2022-09-13 04:57 UTC
Labels: P1, Ingestion
