### ISSUE TITLE
Oracle profiler ingestion returns invalid identifier error

### ISSUE THREAD

**Issue by vithushanms** [open-metadata/OpenMetadata#16497] opened 2024-05-31 10:48 UTC
**Affected module**
When I do the profiler ingestion with Oracle DB, I am getting the following error

<img width="1513" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/53653757/f4ac4928-722f-45fa-9c21-8d376d6526b9">

**Describe the bug**
The issue is with the query being generated. The following column name has to be wrapped within quotes, but here the quotes are missing in the OM query.

<img width="1101" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/53653757/c24f1e6f-8fa0-42f5-8540-6b80d9b0b293">

You can see the same query working after I added the double qoutes. 
<img width="1091" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/53653757/9f8dca32-c8dd-4fb1-ac34-e24061e484b4">

**Version:**
 - OS: ubuntu
 - Python version: 3.8
 - OpenMetadata version: tested in both 1.2.5 and 1.3.1
 - OpenMetadata Ingestion package version: 1.2.5

**Comment by vithushanms** [comment] 2024-06-07 07:18
Are there any updates on this team?

**Comment by harshach** [comment] 2024-06-22 20:53
@TeddyCr can you review this

**Comment by ayush-shah** [comment] 2024-08-05 14:08
We are not able to reproduce this error, if @vithushanms can provide the DDL, that would be great, we will validate the same and open the issue if reproduced, till then, closing this issue.

**Closed by ayush-shah** 2024-08-05 14:08 UTC
Labels: bug, P0, profiler
