### ISSUE TITLE
Last Update time for data assets

### ISSUE THREAD

**Issue by NithinKumaraNT** [open-metadata/OpenMetadata#10607] opened 2023-03-15 18:02 UTC
**Is your feature request related to a problem? Please describe.**
As a data consumer, I would like to know when the particular data asset was updated as a field. 

**Describe the solution you'd like**
It would be nice to have last updated timestamp pulled if available through the connectors. For example, every AWS glue table as a Last Updated property. However, the version number should not be bumped as it is not a data change.

<img width="1362" alt="aws_glue_snap" src="https://user-images.githubusercontent.com/42895864/225400054-1596f9c5-2025-4142-b11a-80697ae7ceba.png">

![Screenshot 2023-03-15 at 18 55 29](https://user-images.githubusercontent.com/42895864/225400851-db0db870-d194-45a6-b2c3-b4c677488f2e.png)

**Describe alternatives you've considered**
Another approach as suggested in the support channel was to use custom properties and use a custom ingestion to populate this field. This can be done but it is not straight forward for a consumer to check the custom properties fields to note the timestamp of updation as well there will be an update to the version as well, this also in my opinion should be avoided.

**Comment by TeddyCr** [comment] 2023-06-30 08:20
closing as duplicate of this one https://github.com/open-metadata/OpenMetadata/issues/11967

**Closed by TeddyCr** 2023-06-30 08:20 UTC
Labels: enhancement
