### ISSUE TITLE
UI: Add Support for Advanced search syntax

### ISSUE THREAD

**Issue by darth-coder00** [open-metadata/OpenMetadata#708] opened 2021-10-08 05:06 UTC
For instance: 

- column_names:<column name>
- description: <desc_text>

**Comment by harshach** [comment] 2022-03-12 17:34
We need to start supporting this in 0.9.2

**Comment by Sachin-chaurasiya** [comment] 2022-04-20 05:58
Duplicate of #4213

**Closed by Sachin-chaurasiya** 2022-04-20 05:58 UTC
Labels: P0, UI
