### ISSUE TITLE
Unable to ingest view lineage when ingesting across multiple Snowflake databases

### ISSUE THREAD

**Issue by fredriv** [open-metadata/OpenMetadata#9538] opened 2022-12-28 14:39 UTC
**Affected module**
Ingestion Framework

**Describe the bug**
I am trying to ingest tables and views from across multiple Snowflake databases, but the view lineage ingestion fails because it does not specify the database name in the SQL query.

**To Reproduce**
Set up two Snowflake databases and schemas, with a view in one database referencing a table in the other.

The ingestion will fail if the current database in the connection is not the same as the one where the view exists, as the generated SQL query in `get_view_definition` in `snowflake.py` (renamed to `snowflake/metadata.py` in `main` branch) only includes the schema name and not the database name.

SQL that fails:
```
SHOW /* sqlalchemy:get_view_definition */ VIEWS LIKE 'STG_USERS_USER' IN DBT_FREDRIV
```

**Expected behavior**
I expect to be able to generate view and table lineage across Snowflake databases.

This SQL works:
```
SHOW /* sqlalchemy:get_view_definition */ VIEWS LIKE 'STG_USERS_USER' IN ANALYTICS_DEV.DBT_FREDRIV
```
(alternatively do a `use analytics_dev` before the failing SQL above).

**Version:**
 - OS: Mac OS
 - Python version: 3.9.9
 - OpenMetadata version: 0.13.1
 - OpenMetadata Ingestion package version: openmetadata-ingestion[snowflake]==0.13.1

**Additional context**
Debug log from the CLI ingestion:
```
[2022-12-28 15:23:38] DEBUG    {Ingestion:common_db_source:266} - Traceback (most recent call last):
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 827, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/snowflake/connector/errors.py", line 275, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/snowflake/connector/errors.py", line 330, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/snowflake/connector/errors.py", line 209, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002043 (02000): SQL compilation error:
Object does not exist, or operation cannot be performed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/metadata/ingestion/source/database/common_db_source.py", line 256, in get_view_definition
    view_definition = inspector.get_view_definition(table_name, schema_name)
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 438, in get_view_definition
    return self.dialect.get_view_definition(
  File "<string>", line 2, in get_view_definition
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/metadata/ingestion/source/database/snowflake.py", line 87, in get_view_definition
    cursor = connection.execute(
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1365, in execute
    return self._exec_driver_sql(
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1669, in _exec_driver_sql
    ret = self._execute_context(
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 827, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/snowflake/connector/errors.py", line 275, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/snowflake/connector/errors.py", line 330, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/Users/fredriv/oda/de-hackathon/.venv/lib/python3.9/site-packages/snowflake/connector/errors.py", line 209, in default_errorhandler
    raise error_class(
sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 002043 (02000): SQL compilation error:
Object does not exist, or operation cannot be performed.
[SQL: /* {"app": "OpenMetadata", "version": "0.13.1.1"} */
SHOW /* sqlalchemy:get_view_definition */ VIEWS LIKE 'STG_USERS_USER' IN DBT_FREDRIV]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

**Comment by fredriv** [comment] 2022-12-29 06:56
Related to https://github.com/open-metadata/OpenMetadata/issues/9460 ?

**Comment by pmbrull** [comment] 2022-12-29 09:38
Thanks @fredriv , this is indeed a duplicate of #9460. Closing it in favor of the original

**Closed by pmbrull** 2022-12-29 09:38 UTC
Labels: bug, Ingestion, lineage
