### ISSUE TITLE
Clickhouse metadata ingestion raise 500 error on some tables

### ISSUE THREAD

**Issue by ruffury** [open-metadata/OpenMetadata#12463] opened 2023-07-17 13:50 UTC
**Affected module**
Ingestion Framework

**Describe the bug**
We use ingestion of Clickhouse metadata and getting 500 server error on some tables or mat views
`Failed to ingest CreateTableRequest [events_old] due to api request failure: 500 Server Error: Internal Server Error for url: https://omd/api/v1/tables`
trace on debug mode: 
```
[2023-07-17, 12:25:06 UTC] {topology_runner.py:77} DEBUG - Processing stage: type_=<class 'metadata.generated.schema.entity.data.table.Table'> processor='yield_table' context='table' ack_sink=True nullable=False must_return=False cache_all=False clear_cache=False overwrite=True consumer=['database_service', 'database', 'database_schema']
[2023-07-17, 12:25:06 UTC] {metadata_rest.py:126} DEBUG - Processing Create request <class 'metadata.generated.schema.api.data.createTable.CreateTableRequest'>
[2023-07-17, 12:25:06 UTC] {metadata_rest.py:148} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/sink/metadata_rest.py", line 136, in write_create_request
    created = self.metadata.create_or_update(entity_request)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/ometa_api.py", line 571, in create_or_update
    resp = self.client.put(
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/client.py", line 288, in put
    return self._request("PUT", path, data)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/client.py", line 189, in _request
    return self._one_request(method, url, opts, retry)
  File "/home/airflow/.local/lib/python3.9/site-packages/metadata/ingestion/ometa/client.py", line 212, in _one_request
    resp.raise_for_status()
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://omd/api/v1/tables
```

**To Reproduce**

Run Clickhouse metadata ingestion 

Table DDL:

```
CREATE TABLE clickstream.events_old
(
    `install_id` UUID,
    `device_id` UUID DEFAULT toUUIDOrZero(multiIf(platform = 'ANDROID', JSONExtractString(device_properties, 'gaid'), platform = 'IOS', JSONExtractString(device_properties, 'idfv'), '0')),
    `request_id` UUID,
    `event_id` UUID,
    `session_id` UUID,
    `session_event_counter` UInt32,
    `token` String,
    `account_id` UInt64,
    `logged_at` DateTime CODEC(Delta(4), LZ4),
    `logged_at_tz` LowCardinality(String),
    `received_at` DateTime CODEC(Delta(4), LZ4),
    `received_at_tz` LowCardinality(String),
    `stored_at` DateTime CODEC(Delta(4), LZ4),
    `platform` LowCardinality(String),
    `app_version` LowCardinality(String),
    `app_version_numeric` UInt64 DEFAULT toUInt64((((arrayMap(x -> toInt64OrZero(x), extractAll(app_version, '\\d+'))[1]) * 1000000000.) + ((arrayMap(x -> toInt64OrZero(x), extractAll(app_version, '\\d+'))[2]) * 1000000.)) + ((arrayMap(x -> toInt64OrZero(x), extractAll(app_version, '\\d+'))[3]) * 1000.)),
    `app_package` LowCardinality(String),
    `event_type` LowCardinality(String),
    `non_interaction_event` UInt8,
    `is_interaction_event` UInt8 ALIAS abs(non_interaction_event - 1),
    `with_invalid_data` UInt8,
    `ab_tags.experiment` Array(UInt16),
    `ab_tags.variation` Array(UInt16),
    `connection_type` LowCardinality(String),
    `ipv4` IPv4,
    `user_agent` String,
    `event_properties` String CODEC(ZSTD(5)),
    `user_properties` String CODEC(ZSTD(5)),
    `device_properties` String CODEC(ZSTD(5)),
    `app_properties` String CODEC(ZSTD(5)),
    `screen_resolution` LowCardinality(String),
    `device_manufacturer` LowCardinality(String),
    `os_name` LowCardinality(String),
    `os_version` LowCardinality(String),
    `device_locale` LowCardinality(String),
    `device_model` LowCardinality(String),
    `device_type` LowCardinality(String),
    `product_list_type` LowCardinality(String) DEFAULT upper(JSONExtractString(event_properties, 'product_list_type')),
    `position` UInt16 DEFAULT JSONExtractUInt(event_properties, 'position'),
    `product_id` UInt64 DEFAULT toUInt64OrZero(JSONExtractRaw(event_properties, 'product_id')) CODEC(T64, LZ4),
    `sku_group_id` UInt64 DEFAULT toUInt64OrZero(JSONExtractRaw(event_properties, 'sku_group_id')) CODEC(T64, LZ4),
    `sku_id` UInt64 DEFAULT toUInt64OrZero(JSONExtractRaw(event_properties, 'sku_id')) CODEC(T64, LZ4),
    `category_id` Int64 DEFAULT JSONExtractInt(event_properties, 'category_id') CODEC(T64, LZ4),
    `shop_id` UInt64 DEFAULT toUInt64OrZero(JSONExtractRaw(event_properties, 'shop_id')) CODEC(T64, LZ4),
    `page_type` LowCardinality(String) DEFAULT upper(JSONExtractString(event_properties, 'page_type')),
    `page_id` Int64 DEFAULT JSONExtractInt(event_properties, 'page_id') CODEC(T64, LZ4),
    `plid` Int64 DEFAULT JSONExtractInt(event_properties, 'plid'),
    `rid` UUID DEFAULT toUUIDOrZero(JSONExtractString(event_properties, 'rid')),
    `query` String DEFAULT substring(JSONExtractString(event_properties, 'query'), 1, 500) CODEC(ZSTD(3)),
    `widget_name` LowCardinality(String) DEFAULT toLowCardinality(JSONExtractString(event_properties, 'widget_name')),
    `popup_id` UUID DEFAULT toUUIDOrZero(JSONExtractString(event_properties, 'popup_id')),
    `badges` Array(UInt32) DEFAULT arrayMap(badge_id_str -> toUInt32OrZero(badge_id_str), JSONExtractArrayRaw(event_properties, 'badges')),
    `language` LowCardinality(String) DEFAULT JSONExtractString(user_properties, 'language')
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/clickstream/events', '{replica}')
PARTITION BY toYYYYMM(received_at)
ORDER BY (platform, event_type, received_at)
TTL stored_at + toIntervalDay(40) TO DISK 'object_storage'
SETTINGS index_granularity = 8192;
```

**Expected behavior**
All tables successfully ingested in OMD

**Version:**
 - OS: linux
 - Python version: 3.9
 - OpenMetadata version: 1.1.0
 - OpenMetadata Ingestion package version: 1.1.0

**Additional context**

**Comment by ayush-shah** [comment] 2023-07-17 13:52
@ruffury can you share which table it causes the error and share the schema ( columns and their data types ) of that table for it to be easily reproducible

**Comment by ulixius9** [comment] 2023-07-28 08:45
@ruffury just an update on this ticket we tried to reproduce the same ddl query but we were not able to reproduce the error, looks like it should be fixed with the latest version i.e 1.1.1 once it is release if not then you can reopen same ticket again

**Closed by ulixius9** 2023-07-28 08:45 UTC
Labels: bug, Ingestion
