### ISSUE TITLE
Glossary UI :  # or @ doesn't activate entity/user references

### ISSUE THREAD

**Issue by stephanesol** [open-metadata/OpenMetadata#11854] opened 2023-06-01 22:01 UTC
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

UI

**Describe the bug**

When using the Glossary, i believe users are allowed to reference entities using the `#` prefix or `@` mention teams within the glossary definition.  I don't see those features or prompts when i invoked them. See example.

**To Reproduce**

Screenshots or steps to reproduce
![2023-06-01_16-58-36 (1)](https://github.com/open-metadata/OpenMetadata/assets/6843613/e80899b1-aa28-463c-b015-c98e3d05e0b6)

**Expected behavior**

My expectation is that invoking # or @ would provide a list of entities or some kind of indication that i can reference objects.

**Version:**
 - Python version:
 - OpenMetadata version: 1.0.1
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by harshach** [comment] 2023-06-01 22:02
@Sachin-chaurasiya @chirag-madlani all markdown editors should have an ability to tag users and data assets like we do in conversations

**Comment by Sachin-chaurasiya** [comment] 2023-06-05 05:18
Duplicate of #9973

**Closed** 2023-06-05 08:43 UTC
Labels: UI
