### ISSUE TITLE
Use Search instead of Suggest in autocomplete dropdowns

### ISSUE THREAD

**Issue by karanh37** [open-metadata/OpenMetadata#11449] opened 2023-05-05 05:16 UTC
**Describe the task**
Currently we are using Elastic search suggester with prefix in our autocomplete dropdowns. So it is not searching within the keyword.
Replace them with Search API

**Comment by chirag-madlani** [comment] 2023-05-25 10:01
Duplicate of: #11375

**Closed by chirag-madlani** 2023-05-25 10:01 UTC
Labels: UI, support
