### ISSUE TITLE
[Feature-Request] Bulk Tagging

### ISSUE THREAD

**Issue by patrick-leclair-gsts** [open-metadata/OpenMetadata#10230] opened 2023-02-17 15:45 UTC
**Is your feature request related to a problem? Please describe.**
I have a variety of tables that all fall under one tag. I want to be able to tag all of them with the same tag at once instead of having to click on each individual table and tag it separately.

**Describe the solution you'd like**
I would like a multi select tool that allows me to select multiple tables and then apply similar characteristics to them such as tags and tiers

**Describe alternatives you've considered**

**Additional context**

**Comment by harshach** [comment] 2024-03-17 16:39
duplicate of Metadata Actions

**Closed by harshach** 2024-03-17 16:39 UTC
Labels: enhancement
