### ISSUE TITLE
Database not being created in Database Service through API

### ISSUE THREAD

**Issue by ArslanAmjadGondal** [open-metadata/OpenMetadata#11167] opened 2023-04-20 15:03 UTC
I have created a **hive** database service through API v1 and then tried to create a database for this database service. The same API call works in v0.13

**Endpoint**: https://open-metadata.domain.com/api/v1/databases/
**Body**:
{
  "name": "test_name",

  "service": {
    "id": "0000-0000-0000-0000-0000",
    "type": "databaseService"
  }
}

**Error**:

{
    "code": 400,
    "message": "Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 4, column: 14] (through reference chain: org.openmetadata.schema.api.data.CreateDatabase[\"service\"])"
}

OpenMetadata version: 1.0.0-beta

**Comment by sureshms** [comment] 2023-04-20 15:54
@ArslanAmjadGondal it would be good to confirm that this is indeed a bug in OpenMetadata #support slack channel before opening a bug. Is the UUID you are passing in the right format? Can you paste the real example?

**Comment by ulixius9** [comment] 2023-04-21 09:58
closing the ticket as this is not a bug, @ArslanAmjadGondal  you have to pass the `fullyQualifiedName` of the service instead of passing the `entityReference`

checkout this slack support thread for example: https://openmetadata.slack.com/archives/C02B6955S4S/p1682068665955649

**Closed by ulixius9** 2023-04-21 09:58 UTC
Labels: P0, backend
